{
  "hash": "bfc752ee73c0568458a64f6394818fd0",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Logistic Regression in Tidymodels\n\n> \"In God we trust, all others bring data.\" - W. Edwards Deming\n\nIn the previous chapter, we introduced logistic regression as a model for a binary response. This chapter shows how to fit, interpret, predict from, and evaluate a multiple logistic regression model using `tidymodels`.\n\n## Multiple Logistic Regression\n\nSimple logistic regression uses one predictor. Multiple logistic regression extends the same idea to several predictors.\n\nFor observation $i$, the model can be written as\n\n$$\n\\log\\left(\\frac{\\pi_i}{1-\\pi_i}\\right)=\\eta_i=\\mathbf{x}_i^\\prime\\boldsymbol{\\beta},\n$$\n\nwhere $\\pi_i=P(Y_i=1)$ and $\\eta_i$ is the **linear predictor**. Equivalently,\n\n$$\nE(Y_i)=\\pi_i=\n\\frac{\\exp(\\mathbf{x}_i^\\prime\\boldsymbol{\\beta})}\n{1+\\exp(\\mathbf{x}_i^\\prime\\boldsymbol{\\beta})}.\n$$\n\nLike the simple logistic response function, the multiple logistic response function is bounded between 0 and 1. The predictors may be quantitative variables, categorical variables represented by indicators, transformations, or interaction terms.\n\n::: {.callout-note collapse=\"false\" title=\"What changes in multiple logistic regression?\"}\n\nThe interpretation changes from a simple odds ratio to a **partial odds ratio**.\n\nFor a quantitative predictor, $\\exp(\\beta_j)$ is the multiplicative change in the odds of $Y=1$ for a one-unit increase in $x_j$, holding the other predictors fixed.\n\nFor an indicator predictor, $\\exp(\\beta_j)$ compares the odds for the group coded 1 to the odds for the reference group coded 0, holding the other predictors fixed.\n\n:::\n\n## Example Using Tidymodels\n\n:::: {#exm-24_1 .example title=\"Disease outbreak data and predictors\"}\n\nIn a health study of an epidemic outbreak spread by mosquitoes, individuals were randomly sampled within two sectors of a city. The response variable was coded as\n\n- $Y = 1$: disease present,\n- $Y = 0$: disease not present.\n\nThe predictors are:\n\n| Variable | Meaning |\n|---|---|\n| $X_1$ | Age |\n| $X_2$ | Indicator for middle socioeconomic class |\n| $X_3$ | Indicator for lower socioeconomic class |\n| $X_4$ | Indicator for sector 2 |\n\nSocioeconomic class is represented by two indicators:\n\n| Class | $X_2$ | $X_3$ |\n|---|---:|---:|\n| Upper | 0 | 0 |\n| Middle | 1 | 0 |\n| Lower | 0 | 1 |\n\nThus, upper class is the reference group. City sector is also represented by an indicator, where $X_4=0$ represents sector 1 and $X_4=1$ represents sector 2.\n\n::::\n\n:::: {#exm-24_2 .example title=\"Loading and exploring the disease outbreak data\"}\n\nWe first load the data, name the variables, and code the response as a factor. The factor levels are ordered as `0`, then `1`, so that the fitted logit corresponds to the disease-present event, $Y=1$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(GGally)\n\ntidymodels_prefer()\n\ndisease_data <- read.table(\"CH14TA03.txt\")\n\nnames(disease_data) <- c(\"id\", \"X1\", \"X2\", \"X3\", \"X4\", \"Y\")\n\ndisease_data <- disease_data |>\n  mutate(Y = factor(Y, levels = c(0, 1)))\n\ndisease_data |>\n  count(Y) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Y  |  n|\n|:--|--:|\n|0  | 67|\n|1  | 31|\n\n\n:::\n:::\n\n\nA scatterplot matrix gives a quick exploratory look at the response and predictors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggpairs(disease_data |> select(-id))\n```\n\n::: {.cell-output-display}\n![](24_Logistic2_files/figure-html/unnamed-chunk-2-1.png){fig-alt='Scatterplot matrix of the disease outbreak response and predictors.' width=576}\n:::\n:::\n\n\nThe scatterplot matrix is useful as a broad scan, but targeted plots are often easier to interpret. The next two plots focus on age and the indicator variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_data |>\n  ggplot(aes(x = Y, y = X1, color = Y)) +\n  geom_boxplot(outlier.shape = NA, alpha = 0.15) +\n  geom_jitter(width = 0.12, height = 0, alpha = 0.75) +\n  labs(\n    x = \"Disease status\",\n    y = \"Age\",\n    color = \"Y\",\n    title = \"Age by disease status\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](24_Logistic2_files/figure-html/unnamed-chunk-3-1.png){fig-alt='Boxplot and jittered points showing age by disease status.' width=576}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_indicator_rates <- disease_data |>\n  mutate(event = as.integer(as.character(Y))) |>\n  select(event, X2, X3, X4) |>\n  pivot_longer(\n    cols = X2:X4,\n    names_to = \"predictor\",\n    values_to = \"indicator_value\"\n  ) |>\n  group_by(predictor, indicator_value) |>\n  summarize(\n    disease_rate = mean(event),\n    n = n(),\n    .groups = \"drop\"\n  )\n\ndisease_indicator_rates |>\n  ggplot(aes(x = factor(indicator_value), y = disease_rate)) +\n  geom_col(fill = \"#0072B2\") +\n  geom_text(aes(label = paste0(\"n = \", n)), vjust = -0.25) +\n  facet_wrap(~ predictor) +\n  scale_y_continuous(\n    limits = c(0, 1),\n    labels = scales::label_percent()\n  ) +\n  labs(\n    x = \"Indicator value\",\n    y = \"Observed disease rate\",\n    title = \"Observed disease rate by indicator variable\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](24_Logistic2_files/figure-html/unnamed-chunk-4-1.png){fig-alt='Bar charts showing disease rate by indicator value for middle class, lower class, and sector 2.' width=576}\n:::\n:::\n\n\nThe targeted plots do not replace the model. They simply help us see how the observed disease rate relates to individual predictors before fitting the multiple logistic regression model.\n\n::::\n\n:::: {#exm-24_3 .example title=\"Fitting a multiple logistic regression workflow\"}\n\nWe can now set up the recipe, model, and workflow.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_recipe <- recipe(Y ~ X1 + X2 + X3 + X4, data = disease_data)\n\ndisease_model <- logistic_reg() |>\n  set_engine(\"glm\")\n\ndisease_workflow <- workflow() |>\n  add_recipe(disease_recipe) |>\n  add_model(disease_model)\n\ndisease_fit <- disease_workflow |>\n  fit(data = disease_data)\n\ndisease_fit |>\n  tidy() |>\n  knitr::kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |  -2.3129|    0.6426|   -3.5994|  0.0003|\n|X1          |   0.0298|    0.0135|    2.2033|  0.0276|\n|X2          |   0.4088|    0.5990|    0.6825|  0.4950|\n|X3          |  -0.3053|    0.6041|   -0.5053|  0.6134|\n|X4          |   1.5747|    0.5016|    3.1393|  0.0017|\n\n\n:::\n:::\n\n\nThe `tidy()` function returns the estimated coefficients on the log-odds scale. Exponentiating the coefficients gives estimated odds ratios. We can also request confidence intervals for the odds ratios.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_fit |>\n  tidy(exponentiate = TRUE, conf.int = TRUE) |>\n  select(term, estimate, conf.low, conf.high, p.value) |>\n  rename(\n    odds_ratio = estimate,\n    lower_95 = conf.low,\n    upper_95 = conf.high\n  ) |>\n  knitr::kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|term        | odds_ratio| lower_95| upper_95| p.value|\n|:-----------|----------:|--------:|--------:|-------:|\n|(Intercept) |     0.0990|   0.0254|   0.3233|  0.0003|\n|X1          |     1.0302|   1.0040|   1.0592|  0.0276|\n|X2          |     1.5050|   0.4639|   4.9600|  0.4950|\n|X3          |     0.7369|   0.2200|   2.4174|  0.6134|\n|X4          |     4.8295|   1.8460|  13.3851|  0.0017|\n\n\n:::\n:::\n\n\nBased on the fitted model:\n\n- For each one-unit increase in $X_1$ age, the estimated odds of disease presence are multiplied by about 1.03, holding the other predictors fixed.\n- For middle socioeconomic class compared to upper class, the estimated odds are multiplied by about 1.50, holding the other predictors fixed.\n- For lower socioeconomic class compared to upper class, the estimated odds are multiplied by about 0.74, holding the other predictors fixed.\n- For sector 2 compared to sector 1, the estimated odds are multiplied by about 4.83, holding the other predictors fixed.\n\nThe confidence interval gives a range of plausible odds ratios. If an interval contains 1, then the data are compatible with both lower and higher odds after adjusting for the other predictors.\n\nThese are model-based associations, not automatic causal effects.\n\n::::\n\n## Predictions\n\nAfter fitting the model, we can obtain predictions on three useful scales:\n\n- `type = \"raw\"` gives the fitted value on the logit scale,\n- `type = \"prob\"` gives predicted class probabilities,\n- `type = \"class\"` gives the predicted class using the default 0.5 probability threshold.\n\n:::: {#exm-24_4 .example title=\"Predicted logits, probabilities, and classes\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_predictions <- disease_data |>\n  select(Y) |>\n  bind_cols(\n    tibble(\n      .pred_logit = as.numeric(\n        predict(disease_fit, new_data = disease_data, type = \"raw\")\n      )\n    ),\n    predict(disease_fit, new_data = disease_data, type = \"prob\"),\n    predict(disease_fit, new_data = disease_data, type = \"class\")\n  )\n\ndisease_predictions |>\n  slice_head(n = 10) |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Y  | .pred_logit| .pred_0| .pred_1|.pred_class |\n|:--|-----------:|-------:|-------:|:-----------|\n|0  |      -1.331|   0.791|   0.209|0           |\n|0  |      -1.272|   0.781|   0.219|0           |\n|0  |      -2.134|   0.894|   0.106|0           |\n|0  |      -0.528|   0.629|   0.371|0           |\n|1  |      -2.083|   0.889|   0.111|0           |\n|0  |      -1.845|   0.864|   0.136|0           |\n|0  |      -2.440|   0.920|   0.080|0           |\n|1  |      -0.982|   0.727|   0.273|0           |\n|1  |      -1.131|   0.756|   0.244|0           |\n|0  |      -0.803|   0.691|   0.309|0           |\n\n\n:::\n:::\n\n\nThe `.pred_1` column is the fitted probability of disease presence. The `.pred_class` column converts those probabilities into predicted classes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_predictions |>\n  ggplot(aes(x = .pred_logit, y = .pred_1, color = Y)) +\n  geom_point(alpha = 0.8) +\n  geom_hline(yintercept = 0.5, linetype = \"dashed\") +\n  labs(\n    x = \"Fitted logit\",\n    y = \"Predicted P(Y = 1)\",\n    color = \"Observed Y\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](24_Logistic2_files/figure-html/unnamed-chunk-8-1.png){fig-alt='Predicted probability of disease presence plotted against the fitted logit, with points colored by the true disease status.' width=576}\n:::\n:::\n\n\nThe dashed line marks the default 0.5 threshold. Points above the line are classified as disease present, and points below the line are classified as disease not present. Misclassification occurs when the predicted class does not match the observed class.\n\n::::\n\n## Confusion Matrix\n\nA confusion matrix compares the predicted classes to the observed classes.\n\n:::: {#exm-24_5 .example title=\"Confusion matrix and classification metrics\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_confusion <- conf_mat(\n  disease_predictions,\n  truth = Y,\n  estimate = .pred_class\n)\n\ndisease_confusion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction  0  1\n         0 58 19\n         1  9 12\n```\n\n\n:::\n:::\n\n\nIn this table, disease present is the event class, $Y=1$. There are 9 false positives and 19 false negatives.\n\nWe can summarize the confusion matrix with several classification metrics. Because the event class is the second factor level, we use `event_level = \"second\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(disease_confusion, event_level = \"second\") |>\n  filter(.metric %in% c(\"accuracy\", \"sens\", \"spec\", \"ppv\", \"npv\")) |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|.metric  |.estimator | .estimate|\n|:--------|:----------|---------:|\n|accuracy |binary     |     0.714|\n|sens     |binary     |     0.387|\n|spec     |binary     |     0.866|\n|ppv      |binary     |     0.571|\n|npv      |binary     |     0.753|\n\n\n:::\n:::\n\n\nHere:\n\n- **Sensitivity** is the proportion of disease-present cases correctly predicted as disease present.\n- **Specificity** is the proportion of disease-absent cases correctly predicted as disease absent.\n- **Positive predictive value** is the proportion of predicted disease-present cases that truly had the disease.\n- **Negative predictive value** is the proportion of predicted disease-absent cases that truly did not have the disease.\n\n::::\n\n::: {.callout-note collapse=\"false\" title=\"Sensitivity and specificity depend on the event class\"}\n\nBefore computing classification metrics, decide which class is the event of interest. In this example, the event is disease present, $Y=1$.\n\nIn `yardstick`, we make that explicit with `event_level = \"second\"` because the factor levels are ordered as `0`, then `1`.\n\n:::\n\n## Thresholds\n\nThe default classification threshold is 0.5, but this is not always the best threshold. If false negatives are costly, we might lower the threshold so more observations are classified as disease present. If false positives are costly, we might raise the threshold.\n\n:::: {#exm-24_6 .example title=\"Changing the classification threshold\"}\n\nThe following table compares accuracy, sensitivity, and specificity for three possible thresholds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthreshold_summary <- map_dfr(c(0.25, 0.50, 0.75), function(cutoff) {\n  thresholded_results <- disease_predictions |>\n    mutate(\n      .pred_threshold = factor(\n        if_else(.pred_1 >= cutoff, \"1\", \"0\"),\n        levels = levels(Y)\n      )\n    )\n\n  summary(\n    conf_mat(thresholded_results, truth = Y, estimate = .pred_threshold),\n    event_level = \"second\"\n  ) |>\n    filter(.metric %in% c(\"accuracy\", \"sens\", \"spec\")) |>\n    select(.metric, .estimate) |>\n    pivot_wider(names_from = .metric, values_from = .estimate) |>\n    mutate(threshold = cutoff, .before = 1)\n})\n\nthreshold_summary |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| threshold| accuracy|  sens|  spec|\n|---------:|--------:|-----:|-----:|\n|      0.25|    0.694| 0.806| 0.642|\n|      0.50|    0.714| 0.387| 0.866|\n|      0.75|    0.735| 0.161| 1.000|\n\n\n:::\n:::\n\n\nLowering the threshold increases sensitivity but usually lowers specificity. Raising the threshold has the opposite effect. The best threshold depends on the context and on the consequences of different kinds of mistakes.\n\n::::\n\n::: {.callout-warning collapse=\"false\" title=\"The threshold should reflect the cost of mistakes\"}\n\nA 0.5 threshold treats false positives and false negatives as if they have similar consequences. That may not be reasonable.\n\nFor a disease screening problem, a false negative may be more costly than a false positive because a sick person is missed. In that case, a lower threshold may be preferred because it catches more true disease cases, even though it creates more false positives.\n\n:::\n\n:::: {#exm-24_7 .example title=\"Comparing thresholds with a simple cost rule\"}\n\nSuppose a false positive has cost 1 and a false negative has cost 5. These numbers are only for illustration, but they show how the preferred threshold can depend on the consequences of different errors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthreshold_costs <- map_dfr(c(0.25, 0.50, 0.75), function(cutoff) {\n  thresholded_results <- disease_predictions |>\n    mutate(\n      .pred_threshold = factor(\n        if_else(.pred_1 >= cutoff, \"1\", \"0\"),\n        levels = levels(Y)\n      )\n    )\n\n  thresholded_results |>\n    summarize(\n      false_positives = sum(Y == \"0\" & .pred_threshold == \"1\"),\n      false_negatives = sum(Y == \"1\" & .pred_threshold == \"0\")\n    ) |>\n    mutate(threshold = cutoff, .before = 1)\n}) |>\n  mutate(\n    total_cost = false_positives * 1 + false_negatives * 5\n  )\n\nthreshold_costs |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| threshold| false_positives| false_negatives| total_cost|\n|---------:|---------------:|---------------:|----------:|\n|      0.25|              24|               6|         54|\n|      0.50|               9|              19|        104|\n|      0.75|               0|              26|        130|\n\n\n:::\n:::\n\n\nUnder this example cost rule, the threshold with the lowest total cost would be preferred. A different application could lead to a different cost rule and therefore a different threshold.\n\n::::\n\n## ROC Curves\n\nA Receiver Operating Characteristic (ROC) curve summarizes how sensitivity and specificity change across all possible classification thresholds.\n\nThe ROC curve plots sensitivity, also called the true positive rate, against the false positive rate, which is $1-\\text{specificity}$.\n\nThe diagonal line represents a random classifier. A better classifier has an ROC curve that bows above this diagonal. The upper-left corner represents perfect classification, with sensitivity equal to 1 and specificity equal to 1.\n\n### Area Under the Curve (AUC)\n\nThe **area under the ROC curve (AUC)** provides a single-number summary of separation ability:\n\n- **AUC = 1**: perfect separation,\n- **AUC = 0.5**: random guessing,\n- **AUC < 0.5**: worse than random guessing, usually indicating a problem with the model or event coding.\n\n:::: {#exm-24_8 .example title=\"ROC curve and AUC for the disease model\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_predictions |>\n  roc_curve(truth = Y, .pred_1, event_level = \"second\") |>\n  autoplot()\n```\n\n::: {.cell-output-display}\n![](24_Logistic2_files/figure-html/unnamed-chunk-13-1.png){fig-alt='ROC curve for the disease outbreak logistic regression model.' width=576}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_predictions |>\n  roc_auc(truth = Y, .pred_1, event_level = \"second\") |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|.metric |.estimator | .estimate|\n|:-------|:----------|---------:|\n|roc_auc |binary     |     0.776|\n\n\n:::\n:::\n\n\nThe AUC estimates how well the fitted probabilities rank disease-present observations above disease-absent observations. Unlike accuracy, AUC does not depend on one specific classification threshold.\n\n::::\n\n## Train-Test Evaluation\n\nThe preceding metrics were calculated using the same data used to fit the model. That is useful for learning the mechanics, but it is not an honest estimate of future predictive performance. A train-test split gives a better validation example.\n\n:::: {#exm-24_9 .example title=\"Evaluating the disease model on a testing set\"}\n\nWe create a stratified split so that the training and testing sets preserve the disease-present and disease-absent proportions as much as possible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3386)\n\ndisease_split <- initial_split(\n  disease_data,\n  prop = 0.8,\n  strata = Y\n)\n\ndisease_train <- training(disease_split)\ndisease_test <- testing(disease_split)\n\nbind_rows(\n  disease_train |>\n    count(Y) |>\n    mutate(split = \"Training\"),\n  disease_test |>\n    count(Y) |>\n    mutate(split = \"Testing\")\n) |>\n  group_by(split) |>\n  mutate(proportion = n / sum(n)) |>\n  ungroup() |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Y  |  n|split    | proportion|\n|:--|--:|:--------|----------:|\n|0  | 53|Training |      0.688|\n|1  | 24|Training |      0.312|\n|0  | 14|Testing  |      0.667|\n|1  |  7|Testing  |      0.333|\n\n\n:::\n:::\n\n\nNow we fit the workflow on the training set and evaluate predictions on the testing set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndisease_train_fit <- disease_workflow |>\n  fit(data = disease_train)\n\ndisease_test_predictions <- disease_test |>\n  select(Y) |>\n  bind_cols(\n    predict(disease_train_fit, new_data = disease_test, type = \"prob\"),\n    predict(disease_train_fit, new_data = disease_test, type = \"class\")\n  )\n\ndisease_test_confusion <- conf_mat(\n  disease_test_predictions,\n  truth = Y,\n  estimate = .pred_class\n)\n\ndisease_test_confusion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction  0  1\n         0 13  4\n         1  1  3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  summary(disease_test_confusion, event_level = \"second\") |>\n    filter(.metric %in% c(\"accuracy\", \"sens\", \"spec\", \"ppv\", \"npv\")),\n  disease_test_predictions |>\n    roc_auc(truth = Y, .pred_1, event_level = \"second\")\n) |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|.metric  |.estimator | .estimate|\n|:--------|:----------|---------:|\n|accuracy |binary     |     0.762|\n|sens     |binary     |     0.429|\n|spec     |binary     |     0.929|\n|ppv      |binary     |     0.750|\n|npv      |binary     |     0.765|\n|roc_auc  |binary     |     0.806|\n\n\n:::\n:::\n\n\nThe testing-set metrics are based only on observations that were not used to estimate the model coefficients. Because this dataset is small, the testing-set estimates can be unstable, but they better represent the validation logic introduced in @sec-ridge and Chapter 22.\n\n::::\n\n## Recap\n\nIn this chapter, we fit and evaluated a multiple logistic regression model using `tidymodels`.\n\n| Idea | Meaning |\n|---|---|\n| **Multiple logistic regression** | Logistic regression with more than one predictor. |\n| **Linear predictor** | The logit-scale fitted value $\\eta_i=\\mathbf{x}_i^\\prime\\boldsymbol{\\beta}$. |\n| **Partial odds ratio** | The multiplicative change in odds for one predictor, holding the other predictors fixed. |\n| **Odds-ratio confidence interval** | A range of plausible values for a population odds ratio. |\n| **Reference group** | The group represented by all indicator variables equal to 0. |\n| **Targeted exploratory plot** | A focused plot that examines one predictor-response relationship more clearly than a broad matrix. |\n| **Predicted probability** | The fitted probability that an observation belongs to the event class. |\n| **Predicted class** | The class assigned after applying a classification threshold. |\n| **Confusion matrix** | A table comparing predicted classes to observed classes. |\n| **False positive** | An observation predicted as event-present when the event is truly absent. |\n| **False negative** | An observation predicted as event-absent when the event is truly present. |\n| **Sensitivity** | The proportion of true event cases correctly classified as event cases. |\n| **Specificity** | The proportion of true nonevent cases correctly classified as nonevent cases. |\n| **Threshold** | The probability cutoff used to convert predicted probabilities into predicted classes. |\n| **Cost-based threshold choice** | Choosing a threshold based on the consequences of false positives and false negatives. |\n| **ROC curve** | A curve showing sensitivity and false positive rate across many thresholds. |\n| **AUC** | A threshold-free summary of how well the model separates the two classes. |\n| **Event level** | The class treated as the event of interest when computing classification metrics. |\n| **In-sample evaluation** | Evaluating predictions on the same data used to fit the model. |\n| **Train-test evaluation** | Fitting the model on training data and evaluating it on held-out testing data. |\n\n## Check your understanding\n\n::: {.callout-note collapse=\"false\" title=\"Problems\"}\n\n1. How does multiple logistic regression extend simple logistic regression?\n\n2. What does it mean to interpret a coefficient while holding other predictors fixed?\n\n3. Why is an indicator variable needed for middle socioeconomic class but not for upper socioeconomic class in this example?\n\n4. What is the event class in the disease outbreak example?\n\n5. Why is it important to make the event class explicit when computing sensitivity and specificity?\n\n6. What does `type = \"prob\"` return in a tidymodels logistic regression workflow?\n\n7. What does `type = \"class\"` return?\n\n8. What does the fitted logit represent?\n\n9. How is a predicted probability converted into a predicted class when the threshold is 0.5?\n\n10. What is a false positive in the disease outbreak example?\n\n11. What is a false negative in the disease outbreak example?\n\n12. What does sensitivity measure?\n\n13. What does specificity measure?\n\n14. Why might we lower the classification threshold below 0.5?\n\n15. Why might we raise the classification threshold above 0.5?\n\n16. What does an ROC curve show?\n\n17. Why is AUC called threshold-free?\n\n18. Why should the odds-ratio interpretations in this chapter not automatically be interpreted causally?\n\n19. What does an odds-ratio confidence interval communicate?\n\n20. Why can a targeted exploratory plot be more useful than a large scatterplot matrix?\n\n21. Why are in-sample classification metrics not a clean estimate of future performance?\n\n22. How does a train-test split improve the validation logic?\n\n23. How can false-positive and false-negative costs change the preferred classification threshold?\n\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Solutions\"}\n\n1. **It includes several predictors in the linear predictor.** The model still uses a logit link, but $\\eta_i$ can include quantitative predictors, indicator variables, interactions, or transformations.\n\n2. **It isolates one predictor's association.** The odds ratio for one predictor describes its association with the odds of the event when the other predictors are kept at the same values.\n\n3. **Upper class is the reference group.** With three classes, two indicator variables are enough. When both indicators are 0, the observation belongs to the upper-class reference group.\n\n4. **The event class is disease present, $Y=1$.** This is the outcome whose probability is modeled and evaluated.\n\n5. **Metrics depend on which class is treated as the event.** Reversing the event class reverses the meanings of sensitivity and specificity.\n\n6. **It returns predicted probabilities.** For a binary response, the output includes one probability column for each class.\n\n7. **It returns predicted classes.** The probabilities are converted into class labels using a threshold or highest-probability rule.\n\n8. **It is the prediction on the log-odds scale.** The fitted logit is $\\hat{\\eta}_i=\\mathbf{x}_i^\\prime\\hat{\\boldsymbol{\\beta}}$.\n\n9. **Classify as 1 if the predicted probability of 1 is at least 0.5.** Otherwise, classify as 0.\n\n10. **A false positive is predicted disease when disease is actually absent.** In symbols, the model predicts 1 but the observed value is 0.\n\n11. **A false negative is predicted no disease when disease is actually present.** In symbols, the model predicts 0 but the observed value is 1.\n\n12. **Sensitivity measures detection of true events.** It is the proportion of disease-present observations correctly classified as disease present.\n\n13. **Specificity measures detection of true nonevents.** It is the proportion of disease-absent observations correctly classified as disease absent.\n\n14. **To catch more true disease cases.** Lowering the threshold usually increases sensitivity but may create more false positives.\n\n15. **To avoid false alarms.** Raising the threshold usually increases specificity but may create more false negatives.\n\n16. **It shows the tradeoff across thresholds.** The ROC curve plots sensitivity against the false positive rate for many possible cutoffs.\n\n17. **It summarizes performance across many thresholds.** AUC does not depend on choosing one cutoff such as 0.5.\n\n18. **The study may be observational.** Logistic regression estimates associations after adjusting for included predictors, but causal interpretation requires stronger design and assumptions.\n\n19. **It communicates uncertainty about the odds ratio.** If the interval is wide, the estimate is imprecise. If it contains 1, the data are compatible with no multiplicative change in the odds.\n\n20. **It focuses attention.** A large matrix can be useful for scanning, but a targeted plot can make one predictor-response relationship easier to interpret.\n\n21. **The model has already seen those data.** In-sample metrics can be too optimistic because the same observations were used for fitting and evaluation.\n\n22. **It separates fitting from evaluation.** The model is estimated on the training data and then judged on held-out testing data.\n\n23. **Different mistakes may have different consequences.** If false negatives are costly, a lower threshold may be preferred; if false positives are costly, a higher threshold may be preferred.\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<!--  \\subsection*{Multinomial Logistic Regression} -->\n\n\n<!-- ## Nominal Response} -->\n\n<!-- \\marginpar{} -->\n<!-- Logistic regression is most frequently used to model the relationship between a dichotomous -->\n<!--                             response variable and a set of predictor variables. -->\n\n\n\n\n\n<!--                             On occasion, however. the response -->\n<!--                             variable may have *more} than two levels. -->\n\n\n\n\n\n<!--                             Logistic regression can still be employed by -->\n<!--                             means of a *polytomous}-or\\\\ *multinomial}-logistic regression model. -->\n\n\n\n\n\n<!--                             Multinomial logistic -->\n<!--                             regression models are used in many fields. In business, for instance, a market researcher -->\n<!--                             may wish to relate a consumer's choice of product (product A, product B. product C) to -->\n<!--                             the consumer's age, gender, geographic location and several other potential explanatory -->\n<!--                             variables. -->\n\n\n\n\n\n<!--                             This is an example of nominal multinomial regression because the response -->\n<!--                             categories are purely qualitative and not *ordered} in any way. -->\n\n\n\n<!-- *Ordinal} response categories can -->\n<!--                             also be modeled using multinomial regression. -->\n\n\n\n\n\n<!--                             For example, the relation between severity -->\n<!--                             of disease measured on an ordinal scale (mild, moderate, severe) and age of patient, gender -->\n<!--                             of patient, and some other explanatory variables may be of interest. -->\n\n\n\n\n\n<!--                             The response variable $Y$ must be coded in the same way as indicator variables except we will need an indicator variable for each category of $Y$. -->\n\n\n\n\n\n<!--                             Instead of going through the details, we will illustrate with R. -->\n\n\n\n\n<!-- \\begin{example} -->\n\n\n\n<!-- A study was undertaken to determine the strength of association between several risk factors -->\n<!--                             and the duration of pregnancies. -->\n\n\n\n<!-- \\marginpar{} -->\n\n<!--                             The risk factors considered were mother's age, nutritional -->\n<!--                             status, history of tobacco use, and history of alcohol use. -->\n\n\n\n\n\n<!--                             The response of interest, pregnancy -->\n<!--                             duration, is a three-category variable that was coded as follows: -->\n<!--                             \\begin{align*} -->\n<!--                             y_{i} &\\quad \\textbf{Pregnancy Duration Category}\\\\ -->\n<!--                             1 &\\quad \\text{Preterm (less than 36 weeks)}\\\\ -->\n<!--                             2 &\\quad \\text{Intermediate term (36 to 37 weeks)}\\\\ -->\n<!--                             3 &\\quad \\text{Full term (38 weeks or greater)} -->\n<!--                             \\end{align*} -->\n\n<!--                             Relevant data for 102 women who had recently given birth at a large metropolitan hospital -->\n<!--                             were obtained. -->\n\n\n\n\n\n<!--                             X variables include: -->\n\n\n<!--                             - Nutritional status ($x_1$), is an index of nutritional status (higher score denotes better nutritional status). -->\n\n<!--                             - Age was categorized into three groups: less than 20 years of age (coded 1), from 21 -->\n<!--                             to 30 years of age (coded 2), and greater than 30 years of age (coded 3). It is represented by -->\n<!--                             two indicator variables (X2 and X3): -->\n<!--                             \\begin{align*} -->\n<!--                             x_{2} &\\quad x_{3} & \\textbf{Class}\\\\ -->\n<!--                             1 &\\quad 0 & \\text{Less than or equal to 20}\\\\ -->\n<!--                             0 &\\quad 0 & \\text{21 to 30}\\\\ -->\n<!--                             0 &\\quad 1 & \\text{Greater than 30} -->\n<!--                             \\end{align*} -->\n\n<!--                             - Alcohol ($x_4$) and smoking history ($x_5$) were also qualitative predictors; the categories were \"Yes\" (coded 1) and \"No\" (coded 0). -->\n<!-- \\begin{lstlisting} -->\n<!-- dat = read.table(\"http://users.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/ -->\n<!--       textdatasets/KutnerData/Chapter%2014%20Data%20Sets/CH14TA13.txt\") -->\n<!-- names(dat) = c(\"id\", \"Y\", \"Y1\", \"Y2\", \"Y3\", \"X1\", \"X2\", \"X3\", \"X4\", \"X5\") -->\n\n<!-- head(dat) -->\n\n<!--   id Y Y1 Y2 Y3  X1 X2 X3 X4 X5 -->\n<!-- 1  1 1  1  0  0 150  0  0  0  1 -->\n<!-- 2  2 1  1  0  0 124  1  0  0  0 -->\n<!-- 3  3 1  1  0  0 128  0  0  0  1 -->\n<!-- 4  4 1  1  0  0 128  1  0  0  1 -->\n<!-- 5  5 1  1  0  0 133  0  0  1  1 -->\n<!-- 6  6 1  1  0  0 130  0  0  1  1 -->\n<!-- \\end{lstlisting} -->\n\n\n\n\n\n<!--                             Note that the Y variable is already coded with the variables Y1, Y2, and Y3 in the dataset. -->\n\n<!-- \\marginpar{} -->\n<!--                             We do not have to do this ourselves, R will code the indicator variables for us if we tell R the variable is a factor. -->\n\n\n\n<!-- \\begin{lstlisting} -->\n<!-- library(nnet) -->\n\n<!-- reg = multinom(factor(Y)~X1+X2+X3+X4+X5, data=dat) -->\n<!-- summary(reg) -->\n\n<!-- Call: -->\n<!-- multinom(formula = factor(Y) ~ X1 + X2 + X3 + X4 + X5, data = dat) -->\n\n<!-- Coefficients: -->\n<!--   (Intercept)         X1          X2         X3         X4         X5 -->\n<!-- 2   -1.517009 0.01897219 -0.04355881 -0.1721573 -0.9758857 -0.2218629 -->\n<!-- 3   -5.475353 0.06542052 -2.95693397 -2.0596355 -2.0428964 -2.4522828 -->\n\n<!-- Std. Errors: -->\n<!--   (Intercept)         X1        X2        X3        X4        X5 -->\n<!-- 2    2.047984 0.01631570 0.7373261 0.6943946 0.5869073 0.5856117 -->\n<!-- 3    2.271691 0.01823932 0.9644844 0.8947673 0.7097457 0.7315046 -->\n\n<!-- Residual Deviance: 168.6754 -->\n<!-- AIC: 192.6754 -->\n<!-- \\end{lstlisting} -->\n\n\n\n\n\n\n<!--                             Note in the summary, we have two regression fits. What we actually have done is model the odds of the probability of being in category 2 to the probability of being in category 1. -->\n\n\n\n\n\n<!--                             We also modeled the odds of the probability of being in category 3 to the probability of being in category 1. -->\n\n\n\n\n\n<!--                             So we call category 1 the baseline category. -->\n\n\n\n\n\n<!--                             To get the effect on the odds ratio for each coefficient: -->\n\n\n\n<!-- \\begin{lstlisting}[firstnumber=last] -->\n<!-- exp(coef(reg)) -->\n\n<!--   (Intercept)       X1         X2        X3        X4         X5 -->\n<!-- 2 0.219366942 1.019153 0.95737625 0.8418467 0.3768584 0.80102519 -->\n<!-- 3 0.004188751 1.067608 0.05197804 0.1275004 0.1296526 0.08609682 -->\n<!-- \\end{lstlisting} -->\n\n\n\n\n<!-- \\marginpar{} -->\n\n<!--                             We can use a different baseline category such as full term: -->\n\n\n\n<!-- \\begin{lstlisting}[firstnumber=last] -->\n<!-- dat$Y = as.factor(dat$Y) -->\n<!-- dat$Y = relevel(dat$Y, ref = \"3\") -->\n\n<!-- reg.nom = multinom(factor(Y)~X1+X2+X3+X4+X5, data=dat) -->\n<!-- summary(reg.nom) -->\n\n<!-- Call: -->\n<!-- multinom(formula = factor(Y) ~ X1 + X2 + X3 + X4 + X5, data = dat) -->\n\n<!-- Coefficients: -->\n<!--   (Intercept)          X1       X2       X3       X4       X5 -->\n<!-- 1    5.475147 -0.06541919 2.957028 2.059662 2.042900 2.452362 -->\n<!-- 2    3.958370 -0.04644903 2.913475 1.887550 1.067001 2.230492 -->\n\n<!-- Std. Errors: -->\n<!--   (Intercept)         X1        X2        X3        X4        X5 -->\n<!-- 1    2.271677 0.01823916 0.9644921 0.8947727 0.7097461 0.7315106 -->\n<!-- 2    1.941063 0.01488581 0.8575544 0.8088255 0.6495262 0.6681955 -->\n\n<!-- Residual Deviance: 168.6754 -->\n<!-- AIC: 192.6754 -->\n\n\n<!-- #to get the predicted probability for each observation -->\n<!-- preds.nom = fitted(reg.nom) -->\n<!-- preds.nom[1:10,] -->\n\n<!--             3           1          2 -->\n<!-- 1  0.62078219 0.094217907 0.28499991 -->\n<!-- 2  0.18455857 0.254210377 0.56123105 -->\n<!-- 3  0.34297651 0.219535548 0.43748794 -->\n<!-- 4  0.02716468 0.334553819 0.63828151 -->\n<!-- 5  0.13335384 0.474690286 0.39195587 -->\n<!-- 6  0.11480795 0.497290719 0.38790133 -->\n<!-- 7  0.95144461 0.009569423 0.03898596 -->\n<!-- 8  0.09738287 0.335195611 0.56742152 -->\n<!-- 9  0.02775016 0.658559402 0.31369044 -->\n<!-- 10 0.40441329 0.186642234 0.40894447 -->\n\n\n<!-- # if we pedict the category with the highest probability: -->\n<!-- ind = apply(preds.nom, 1, which.max) -->\n<!-- preds.nom.cat = colnames(preds.nom)[ind] -->\n<!-- preds.nom.cat -->\n\n<!--   [1] \"3\" \"2\" \"2\" \"2\" \"1\" \"1\" \"3\" \"2\" \"1\" \"2\" \"3\" \"1\" \"2\" \"1\" \"1\" \"3\" \"2\" \"2\" \"1\" \"1\" \"1\" -->\n<!--  [22] \"1\" \"1\" \"2\" \"1\" \"2\" \"3\" \"3\" \"2\" \"2\" \"2\" \"2\" \"2\" \"2\" \"3\" \"2\" \"2\" \"2\" \"2\" \"3\" \"2\" \"2\" -->\n<!--  [43] \"2\" \"2\" \"2\" \"2\" \"3\" \"2\" \"1\" \"2\" \"2\" \"1\" \"2\" \"3\" \"2\" \"2\" \"2\" \"1\" \"3\" \"1\" \"3\" \"3\" \"3\" -->\n<!--  [64] \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" -->\n<!--  [85] \"2\" \"3\" \"3\" \"3\" \"1\" \"3\" \"3\" \"3\" \"3\" \"3\" \"2\" \"2\" \"2\" \"2\" \"1\" \"1\" \"3\" \"1\" -->\n\n\n\n<!-- #compare to observed categories: -->\n<!-- table(preds.nom.cat, dat$Y) -->\n\n<!-- preds.nom.cat  3  1  2 -->\n<!--             1  4 12  4 -->\n<!--             2  5 10 23 -->\n<!--             3 32  4  8 -->\n<!-- \\end{lstlisting} -->\n<!-- \\end{example} -->\n\n\n<!--  \\subsection*{Ordinal Regression} -->\n\n\n<!-- ## Ordinal Response} -->\n\n\n<!-- When the response variable $Y$ takes on categorical responses that can be put into order, then  the multinomial logistic regression discussed in Section 8.2 can still be used. -->\n<!-- \\marginpar{} -->\n\n\n\n\n<!--                             However, a more effective strategy, yielding a more parsimonious and more easily interpreted model, results if the *ordering} of the categories is taken into account explicitly. -->\n\n\n\n\n\n<!--                             The model that is usually employed is called the *proportional} *odds}  model -->\n\n\n\n\n\n<!--                             The proportional odds model for ordinal logistic regression models the cumulative probabilities -->\n<!--                             $$ -->\n<!--                             P(y_i\\le j) -->\n<!--                             $$ -->\n<!--                             rather than the specific category probabilities -->\n<!--                             $$ -->\n<!--                             P(y_i=j) -->\n<!--                             $$ -->\n<!--                             as was the case -->\n<!--                             for nominal logistic regression. -->\n\n\n\n\n\n<!--                             Again, we will skip the details and illustrate with R using the pregnancy data from the last section. -->\n<!-- \\marginpar{} -->\n<!-- \\begin{example} -->\n\n<!-- \\ -->\n\n\n<!-- \\begin{lstlisting} -->\n<!-- library(MASS) -->\n\n<!-- dat = read.table(\"http://users.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/ -->\n<!--                  textdatasets/KutnerData/Chapter%2014%20Data%20Sets/CH14TA13.txt\") -->\n<!-- names(dat) = c(\"id\", \"Y\", \"Y1\", \"Y2\", \"Y3\", \"X1\", \"X2\", \"X3\", \"X4\", \"X5\") -->\n\n\n<!-- #tell R the order of the factors -->\n<!-- dat$Y = factor(dat$Y,levels = c(\"1\", \"2\", \"3\"), ordered=T) -->\n\n<!-- reg.ord = polr(Y~X1+X2+X3+X4+X5,data=dat) -->\n<!-- summary(reg.ord) -->\n\n<!-- Call: -->\n<!-- polr(formula = Y ~ X1 + X2 + X3 + X4 + X5, data = dat) -->\n\n<!-- Coefficients: -->\n<!--       Value Std. Error t value -->\n<!-- X1  0.04887    0.01182   4.133 -->\n<!-- X2 -1.97601    0.57616  -3.430 -->\n<!-- X3 -1.36348    0.54648  -2.495 -->\n<!-- X4 -1.66987    0.47537  -3.513 -->\n<!-- X5 -1.59154    0.45165  -3.524 -->\n\n<!-- Intercepts: -->\n<!--     Value   Std. Error t value -->\n<!-- 1|2  2.9301  1.4929     1.9627 -->\n<!-- 2|3  5.0249  1.5445     3.2535 -->\n\n<!-- Residual Deviance: 173.5122 -->\n<!-- AIC: 187.5122 -->\n\n\n<!-- #to get the predicted probability for each observation -->\n<!-- preds.ord = fitted(reg.ord) -->\n<!-- preds.ord[1:10,] -->\n\n<!--              1          2          3 -->\n<!-- 1  0.056827016 0.27179270 0.67138028 -->\n<!-- 2  0.239742367 0.47950086 0.28075677 -->\n<!-- 3  0.150070798 0.43915298 0.41077622 -->\n<!-- 4  0.560196430 0.35167985 0.08812372 -->\n<!-- 5  0.423470637 0.43299765 0.14353172 -->\n<!-- 6  0.459606967 0.41396070 0.12643233 -->\n<!-- 7  0.009988634 0.06576689 0.92424447 -->\n<!-- 8  0.384644784 0.45082830 0.16452692 -->\n<!-- 9  0.751897195 0.20907082 0.03903198 -->\n<!-- 10 0.121488681 0.40757743 0.47093389 -->\n\n\n<!-- # if we pedict the category with the highest probability: -->\n<!-- ind = apply(preds.ord, 1, which.max) -->\n<!-- preds.ord.cat = colnames(preds.ord)[ind] -->\n<!-- preds.ord.cat -->\n\n<!--   [1] \"3\" \"2\" \"2\" \"1\" \"2\" \"1\" \"3\" \"2\" \"1\" \"3\" \"3\" \"1\" \"2\" \"1\" \"1\" \"3\" \"2\" \"2\" \"1\" \"1\" \"1\" -->\n<!--  [22] \"1\" \"1\" \"2\" \"1\" \"1\" \"3\" \"3\" \"1\" \"2\" \"2\" \"2\" \"2\" \"2\" \"3\" \"2\" \"2\" \"3\" \"2\" \"2\" \"2\" \"2\" -->\n<!--  [43] \"1\" \"2\" \"2\" \"2\" \"3\" \"2\" \"2\" \"1\" \"2\" \"2\" \"1\" \"3\" \"1\" \"2\" \"1\" \"1\" \"2\" \"2\" \"3\" \"3\" \"3\" -->\n<!--  [64] \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"2\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" \"3\" -->\n<!--  [85] \"3\" \"3\" \"3\" \"3\" \"2\" \"3\" \"2\" \"3\" \"3\" \"3\" \"3\" \"2\" \"2\" \"3\" \"2\" \"1\" \"3\" \"2\" -->\n\n\n<!-- #compare to observed categories: -->\n<!-- table(preds.ord.cat, dat$Y) -->\n\n<!-- preds.ord.cat  1  2  3 -->\n<!--             1 13  7  1 -->\n<!--             2  8 21  7 -->\n<!--             3  5  7 33 -->\n<!-- \\end{lstlisting} -->\n<!-- \\end{example} -->\n\n\n\n<!--  \\subsection*{Poisson Regression} -->\n\n\n<!-- ## Introduction} -->\n\n<!-- \\marginpar{} -->\n<!-- We consider now another nonlinear regression model where the response outcomes are -->\n<!--                             discrete. -->\n\n\n\n\n\n<!--                             Poisson regression is useful when the outcome is a count, with large-count outcomes -->\n<!--                             being rare events. -->\n\n\n\n\n\n<!--                             For instance, the number of times a household shops at a particular -->\n<!--                             supermarket in a week is a count, with a large number of shopping trips to the store during -->\n<!--                             the week being a rare event. A researcher may wish to study the relation between a family's -->\n<!--                             number of shopping trips to the store during a particular week and the family's income, -->\n<!--                             number of children, distance from the store, and some other explanatory variables. -->\n\n\n\n\n\n<!--                             As another -->\n<!--                             example, the relation between the number of hospitalizations of a member of a health -->\n<!--                             maintenance organization during the past year and the member's age, income, and previous -->\n<!--                             health status may be of interest. -->\n\n\n\n\n\n\n<!--                             The Poisson distribution can be utilized for outcomes that are counts ($y_i = 0, 1,2, ...$ ), -->\n<!--                             with a large count or frequency being a rare event. -->\n\n<!-- ## The Poisson Distribution} -->\n\n\n<!-- The Poisson probability distribution is -->\n<!--                             $$ -->\n<!--                             f(Y) = \\frac{\\mu^Y \\exp(-\\mu)}{Y!} -->\n<!--                             $$ -->\n\n<!--                             The mean and variance of a Poisson distribution are -->\n<!--                             \\begin{align*} -->\n<!--                             E\\{Y\\} &= \\mu\\\\ -->\n<!--                             \\sigma^2\\{Y\\} &=\\mu -->\n<!--                             \\end{align*} -->\n\n\n<!--                             Note that the variance is the same as the mean. -->\n\n\n<!-- \\marginpar{} -->\n\n\n<!--                             Hence, if the number of store trips follows -->\n<!--                             the Poisson distribution and the mean number of store trips for a family with three children -->\n<!--                             is larger than the mean number of trips for a family with no children, the variances of the -->\n<!--                             distributions of outcomes for the two families will also differ. -->\n\n<!-- ## Poisson Regression} -->\n\n\n<!-- We start with the regression model -->\n<!--                             \\begin{align*} -->\n<!--                             y_{i} & =E\\left[ y_{i}\\right] +\\varepsilon_{i}\\qquad i=1,2,\\ldots,n -->\n<!--                             \\end{align*} -->\n\n\n<!--                             The mean response for the $i$th case, to be denoted now my $\\mu_{i}$ -->\n<!--                             for simplicity, is assumed as always to be a function of the set of -->\n<!--                             predictor variables $x_{1},\\ldots,x_{p-1}$. -->\n\n\n\n\n\n<!--                             We use the notation $\\mu\\left(\\textbf{X}_{i},\\boldsymbol{\\beta}\\right)$ -->\n<!--                             to denote the function that relates the mean response $\\mu_{i}$ to -->\n<!--                             $\\textbf{X}_{i}$, the values of the predictor variables for case -->\n<!--                             $i$, and $\\boldsymbol{\\beta}$, the values of the regression coefficients. -->\n\n\n\n\n\n<!--                             Some commonly used functions for Poisson regression are -->\n<!--                             \\begin{align*} -->\n<!--                             \\mu_{i}= & \\mu\\left(\\textbf{X}_{i},\\boldsymbol{\\beta}\\right)=\\textbf{X}_{i}^{\\prime}\\boldsymbol{\\beta}\\\\ -->\n<!--                             \\mu_{i}= & \\mu\\left(\\textbf{X}_{i},\\boldsymbol{\\beta}\\right)=\\exp\\left(\\textbf{X}_{i}^{\\prime}\\boldsymbol{\\beta}\\right)\\\\ -->\n<!--                             \\mu_{i}= & \\mu\\left(\\textbf{X}_{i},\\boldsymbol{\\beta}\\right)=\\ln\\left(\\textbf{X}_{i}^{\\prime}\\boldsymbol{\\beta}\\right) -->\n<!--                             \\end{align*} -->\n\n<!--                             In all three cases, the mean response $\\mu_{i}$ must be nonnegative. -->\n\n\n\n\n\n<!--                             Since the distribution of the error terms $\\varepsilon_{i}$ for Poisson -->\n<!--                             regression is a function of the distribution of the response $y_{i}$, -->\n<!--                             which is Poisson, it is easiest to state the Poisson regression model -->\n<!--                             in the following form: -->\n\n<!--                             $y_{i}$ are independent Poisson random variables with expected values $\\mu_{i}$ where -->\n<!--                             \\begin{align*} -->\n<!--                             \\mu_{i} & =\\mu\\left(\\textbf{X}_{i},\\boldsymbol{\\beta}\\right) -->\n<!--                             \\end{align*} -->\n\n\n<!--                             The most commonly used response function is $\\mu_{i}=\\exp\\left(\\textbf{X}_{i}^{\\prime}\\boldsymbol{\\beta}\\right)$. -->\n\n<!-- \\begin{example} -->\n\n<!-- The Miller Lumber Company is a large retailer of lumber and paint, as well as of plumbing, -->\n<!--                             electrical, and other household supplies. -->\n\n\n\n<!-- \\marginpar{} -->\n\n<!--                             During a representative two-week period, in-store -->\n<!--                             surveys were conducted and addresses of customers were obtained. The addresses were -->\n<!--                             then used to identify the metropolitan area census tracts in which the customers reside. -->\n\n\n\n\n\n<!--                             At -->\n<!--                             the end of the survey period, the total number of customers who visited the store from each -->\n<!--                             census tract within a 10-mile radius was determined and relevant demographic information -->\n<!--                             for each tract (average income, number of housing units, etc.) was obtained. -->\n\n\n\n\n\n<!--                             Several other -->\n<!--                             variables expected to be related to customer counts were constructed from maps, including -->\n<!--                             distance from census tract to nearest competitor and distance to store. -->\n\n\n\n\n\n\n<!--                             Initial screening of the potential predictor variables was conducted which led to the -->\n<!--                             retention of five predictor variables: -->\n\n\n<!--                             - $x_1$: Number of housing units -->\n\n<!--                             - $x_2$: Average income, in dollars -->\n\n<!--                             - $x_3$: Average housing unit age, in years -->\n\n<!--                             - $x_4$ : Distance to nearest competitor, in miles -->\n\n<!--                             - $x_5$: Distance to store, in miles -->\n\n<!--                             - $y_i$ : Number of customers who visited store from census tract -->\n\n\n<!-- \\begin{lstlisting} -->\n<!-- dat = read.table(\"http://users.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/ -->\n<!--                textdatasets/KutnerData/Chapter%2014%20Data%20Sets/CH14TA14.txt\") -->\n<!-- names(dat) = c(\"Y\", \"X1\", \"X2\", \"X3\", \"X4\", \"X5\") -->\n\n<!-- reg = glm(Y~., family = \"poisson\", data=dat) -->\n<!-- summary(reg) -->\n\n<!-- Call: -->\n<!-- glm(formula = Y ~ ., family = \"poisson\", data = dat) -->\n\n<!-- Deviance Residuals: -->\n<!--      Min        1Q    Median        3Q       Max -->\n<!-- -2.93195  -0.58868  -0.00009   0.59269   2.23441 -->\n\n<!-- Coefficients: -->\n<!--               Estimate Std. Error z value Pr(>|z|) -->\n<!-- (Intercept)  2.942e+00  2.072e-01  14.198  < 2e-16 *** -->\n<!-- X1           6.058e-04  1.421e-04   4.262 2.02e-05 *** -->\n<!-- X2          -1.169e-05  2.112e-06  -5.534 3.13e-08 *** -->\n<!-- X3          -3.726e-03  1.782e-03  -2.091   0.0365 * -->\n<!-- X4           1.684e-01  2.577e-02   6.534 6.39e-11 *** -->\n<!-- X5          -1.288e-01  1.620e-02  -7.948 1.89e-15 *** -->\n<!-- --- -->\n<!-- Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 -->\n\n<!-- (Dispersion parameter for poisson family taken to be 1) -->\n\n<!--     Null deviance: 422.22  on 109  degrees of freedom -->\n<!-- Residual deviance: 114.99  on 104  degrees of freedom -->\n<!-- AIC: 571.02 -->\n\n<!-- Number of Fisher Scoring iterations: 4 -->\n\n<!-- predict(reg) -->\n\n<!--        1        2        3        4        5        6        7 -->\n<!-- 2.512666 2.171006 3.336689 2.129078 1.982460 2.184004 1.458190 -->\n<!--        8        9       10 -->\n<!-- 2.397791 2.670277 2.453965 -->\n<!-- \\end{lstlisting} -->\n\n<!-- \\end{example} -->\n<!-- \\marginpar{} -->\n",
    "supporting": [
      "24_Logistic2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}