<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>STA 3386 Regression Analysis - 4&nbsp; Sampling Distribution of the Least Squares Estimators and Testing the Slope</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_Correlation.html" rel="next">
<link href="./03_Properties.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_Sampling.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling Distribution of the Least Squares Estimators and Testing the Slope</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Regression Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fitting the Simple Linear Regression Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Properties of the Least Squares Estimators and Model Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Sampling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling Distribution of the Least Squares Estimators and Testing the Slope</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation Coefficient and the Coefficient of Determination</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Using.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Using the Simple Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Checking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Checking the Linearity and Constant Variance Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Checking2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Checking the Normality and Independence Assumptions and Outliers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_Tidymodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression with Tidymodels</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_Intro_Multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">An Intro to Multiple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_Regression_Matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">The Regression Model in Matrix Terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Model Assumptions and the ANOVA F-test</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#properties-of-the-constants-k_i-and-c_i" id="toc-properties-of-the-constants-k_i-and-c_i" class="nav-link active" data-scroll-target="#properties-of-the-constants-k_i-and-c_i"><span class="header-section-number">4.1</span> Properties of the constants <span class="math inline">\(k_i\)</span> and <span class="math inline">\(c_i\)</span></a></li>
  <li><a href="#expected-values-of-b_0-and-b_1" id="toc-expected-values-of-b_0-and-b_1" class="nav-link" data-scroll-target="#expected-values-of-b_0-and-b_1"><span class="header-section-number">4.2</span> Expected Values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span></a>
  <ul class="collapse">
  <li><a href="#expected-value-of-b_1" id="toc-expected-value-of-b_1" class="nav-link" data-scroll-target="#expected-value-of-b_1"><span class="header-section-number">4.2.1</span> Expected Value of <span class="math inline">\(b_1\)</span></a></li>
  <li><a href="#expected-value-of-b_0" id="toc-expected-value-of-b_0" class="nav-link" data-scroll-target="#expected-value-of-b_0"><span class="header-section-number">4.2.2</span> Expected Value of <span class="math inline">\(b_0\)</span></a></li>
  </ul></li>
  <li><a href="#variances-of-b_0-and-b_1" id="toc-variances-of-b_0-and-b_1" class="nav-link" data-scroll-target="#variances-of-b_0-and-b_1"><span class="header-section-number">4.3</span> Variances of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span></a>
  <ul class="collapse">
  <li><a href="#variance-of-b_1" id="toc-variance-of-b_1" class="nav-link" data-scroll-target="#variance-of-b_1"><span class="header-section-number">4.3.1</span> Variance of <span class="math inline">\(b_1\)</span></a></li>
  <li><a href="#variance-of-b_0" id="toc-variance-of-b_0" class="nav-link" data-scroll-target="#variance-of-b_0"><span class="header-section-number">4.3.2</span> Variance of <span class="math inline">\(b_0\)</span></a></li>
  </ul></li>
  <li><a href="#best-linear-unbiased-estimators-blues" id="toc-best-linear-unbiased-estimators-blues" class="nav-link" data-scroll-target="#best-linear-unbiased-estimators-blues"><span class="header-section-number">4.4</span> Best Linear Unbiased Estimators (BLUEs)</a></li>
  <li><a href="#sampling-distribution-for-b_1" id="toc-sampling-distribution-for-b_1" class="nav-link" data-scroll-target="#sampling-distribution-for-b_1"><span class="header-section-number">4.5</span> Sampling Distribution for <span class="math inline">\(b_1\)</span></a>
  <ul class="collapse">
  <li><a href="#standardized-score" id="toc-standardized-score" class="nav-link" data-scroll-target="#standardized-score"><span class="header-section-number">4.5.1</span> Standardized Score</a></li>
  <li><a href="#studentized-score" id="toc-studentized-score" class="nav-link" data-scroll-target="#studentized-score"><span class="header-section-number">4.5.2</span> Studentized Score</a></li>
  </ul></li>
  <li><a href="#sec-modelutility" id="toc-sec-modelutility" class="nav-link" data-scroll-target="#sec-modelutility"><span class="header-section-number">4.6</span> Assessing the Utility of the Model: Making Inferences About the Slope</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling Distribution of the Least Squares Estimators and Testing the Slope</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>“If you do not know how to ask the right question, you discover nothing.” - W. E. Demining</p>
</blockquote>
<section id="properties-of-the-constants-k_i-and-c_i" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="properties-of-the-constants-k_i-and-c_i"><span class="header-section-number">4.1</span> Properties of the constants <span class="math inline">\(k_i\)</span> and <span class="math inline">\(c_i\)</span></h2>
<p>In the previous section, we examined how the least squares estimators are linear combinations of the response variable <span class="math inline">\(y\)</span>. Let’s know look at the properties of the coefficients in <a href="03_Properties.html#eq-w1_5">Equation&nbsp;<span>3.1</span></a> and <a href="03_Properties.html#eq-w1_6">Equation&nbsp;<span>3.2</span></a>. We will not present the proofs in this course but they are not complicated.</p>
<p>The coefficients <span class="math inline">\(k_{i}\)</span> have the following properties: <span id="eq-w1_7"><span class="math display">\[
\begin{align}
\sum k_{i} &amp; =0
\end{align}
\tag{4.1}\]</span></span></p>
<p><span id="eq-w1_8"><span class="math display">\[
\begin{align}
\sum k_{i}x_i &amp; =1
\end{align}
\tag{4.2}\]</span></span></p>
<p><span id="eq-w1_9"><span class="math display">\[
\begin{align}
\sum k_{i}^{2} &amp; =\frac{1}{\sum \left(x_i-\bar{x}\right)^{2}}
\end{align}
\tag{4.3}\]</span></span></p>
<p>Likewise, the coefficients <span class="math inline">\(c_{i}\)</span> have the following properties: <span id="eq-w1_10"><span class="math display">\[
\begin{align}
\sum c_{i} &amp; =1
\end{align}
\tag{4.4}\]</span></span></p>
<p><span id="eq-w1_11"><span class="math display">\[
\begin{align}
\sum c_{i}x_i &amp; =0
\end{align}
\tag{4.5}\]</span></span></p>
<p><span id="eq-w1_12"><span class="math display">\[
\begin{align}
\sum c_{i}^{2} &amp; =\frac{1}{n}+\frac{\left(\bar{x}\right)^{2}}{\sum \left(x_i-\bar{x}\right)^{2}}
\end{align}
\tag{4.6}\]</span></span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Review: The Expected Value of a Linear Combination
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recall that the expected value of a linear combination of the random variable <span class="math inline">\(Y\)</span> is <span class="math display">\[
E(aY+b)=aE(Y)+b
\]</span> where <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are constants.</p>
</div>
</div>
</section>
<section id="expected-values-of-b_0-and-b_1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="expected-values-of-b_0-and-b_1"><span class="header-section-number">4.2</span> Expected Values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span></h2>
<p>Before finding the expectations, recall <span class="math inline">\(E\left(y_i\right)=\beta_{0}+\beta_{1}x_i\)</span>.</p>
<section id="expected-value-of-b_1" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="expected-value-of-b_1"><span class="header-section-number">4.2.1</span> Expected Value of <span class="math inline">\(b_1\)</span></h3>
<p>The expected value of <span class="math inline">\(b_1\)</span> is <span class="math display">\[
\begin{align*}
E\left[b_1\right] &amp; =E\left[\underbrace{\sum k_{i}y_i}_{(3.1)}\right]\\
&amp; =\sum k_{i}\left(\beta_{0}+\beta_{1}x_i\right)\\
&amp; =\beta_{0}\underbrace{\sum k_{i}}_{(4.1)}+\beta_{1}\underbrace{\sum k_{i}x_i}_{(4.2)}\\
&amp; =\beta_{1}
\end{align*}
\]</span></p>
</section>
<section id="expected-value-of-b_0" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="expected-value-of-b_0"><span class="header-section-number">4.2.2</span> Expected Value of <span class="math inline">\(b_0\)</span></h3>
<p>The expected value of <span class="math inline">\(b_0\)</span> is <span class="math display">\[
\begin{align*}
E\left[b_0\right] &amp; =E\left[\underbrace{\sum c_{i}y_i}_{(3.2)}\right]\\
&amp; =\sum c_{i}\left(\beta_{0}+\beta_{1}x_i\right)\\
&amp; =\beta_{0}\underbrace{\sum c_{i}}_{(4.4)}+\beta_{1}\underbrace{\sum c_{i}x_i}_{(4.5)}\\
&amp; =\beta_{0}
\end{align*}
\]</span></p>
<p>Therefore, <span class="math inline">\(b_0\)</span> is an <em>unbiased</em> estimator of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(b_1\)</span> is an <em>unbiased</em> estimator of <span class="math inline">\(\beta_1\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Review: Unbiased Estimator
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recall that an unbiased estimator for some parameter is an estimator that has an expected value equal to that parameter.</p>
</div>
</div>
</section>
</section>
<section id="variances-of-b_0-and-b_1" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="variances-of-b_0-and-b_1"><span class="header-section-number">4.3</span> Variances of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span></h2>
<p>To find the variances, we will use a result from mathematical statistics: Let <span class="math inline">\(Y_{1},\ldots,Y_{n}\)</span> be uncorrelated random variables and let <span class="math inline">\(a_{1},\ldots,a_{n}\)</span> be constants. Then <span id="eq-w1_13"><span class="math display">\[
\begin{align}
Var\left[\sum a_{i}Y_i\right] &amp; =\sum a_{i}^{2}Var\left[Y_i\right]
\end{align}
\tag{4.7}\]</span></span></p>
<p>Recall that we assume the response variables <span class="math inline">\(y_i\)</span>’s are <em>independent</em>.</p>
<p>Technically, we assume the <span class="math inline">\(y_i\)</span>’s are <em>uncorrelated</em>. In general, uncorrelated does not imply independent. However, if the random variables are jointly normally distributed (recall our third assumption of the model), then uncorrelated does imply independent.</p>
<p>Also, note that <span class="math display">\[
\begin{align*}
    Var\left[Y\right]&amp; = Var\left[\beta_0 + \beta_1 x + \varepsilon\right]\\
    &amp; = Var\left[\varepsilon\right]\\
    &amp; = \sigma^2
\end{align*}
\]</span></p>
<section id="variance-of-b_1" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="variance-of-b_1"><span class="header-section-number">4.3.1</span> Variance of <span class="math inline">\(b_1\)</span></h3>
<p>The variance of <span class="math inline">\(b_1\)</span> is <span id="eq-w1_14"><span class="math display">\[
\begin{align}
Var\left[b_1\right] &amp; =Var\left[\underbrace{\sum k_{i}y_i}_{(3.1)}\right]\\
&amp; =\underbrace{\sum k_{i}^{2}}_{(4.3)}Var\left[y_i\right]\\
&amp; =\frac{\sigma^{2}}{\sum \left(x_i-\bar{x}\right)^{2}}
\end{align}
\tag{4.8}\]</span></span></p>
</section>
<section id="variance-of-b_0" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="variance-of-b_0"><span class="header-section-number">4.3.2</span> Variance of <span class="math inline">\(b_0\)</span></h3>
<p>The variance of <span class="math inline">\(b_0\)</span> is <span id="eq-w1_15"><span class="math display">\[
\begin{align}
Var\left[b_0\right] &amp; =Var\left[\underbrace{\sum c_{i}y_i}_{(3.2)}\right]\nonumber\\
&amp; =\underbrace{\sum c_{i}^{2}}_{(4.6)}Var\left[y_i\right]\\
&amp; =\sigma^{2}\left[\frac{1}{n}+\frac{\left(\bar{x}\right)^{2}}{\sum \left(x_i-\bar{x}\right)^{2}}\right]
\end{align}
\tag{4.9}\]</span></span></p>
</section>
</section>
<section id="best-linear-unbiased-estimators-blues" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="best-linear-unbiased-estimators-blues"><span class="header-section-number">4.4</span> Best Linear Unbiased Estimators (BLUEs)</h2>
<p>We see from <a href="03_Properties.html#eq-w1_5">Equation&nbsp;<span>3.1</span></a> and <a href="03_Properties.html#eq-w1_6">Equation&nbsp;<span>3.2</span></a> that <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are <em>linear</em> estimators.</p>
<p>Any estimator for <span class="math inline">\(\beta_{1}\)</span>, which we will denote as <span class="math inline">\(\hat{\beta}_{0}\)</span>, that takes the form <span class="math display">\[
\begin{align*}
\hat{\beta}_{1} &amp; =\sum a_{i}y_i
\end{align*}
\]</span> where <span class="math inline">\(a_{i}\)</span> is some constant, is called a <em>linear estimator</em>.</p>
<p>Of all linear estimators for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that are <em>unbiased</em>, the least squares estimators, <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, have the smallest variance.</p>
<p>This is summarized in the following well known theorem:</p>
<div id="thm-gauss" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.1 (Gauss Markov Theorem) </strong></span>For the simple linear regression model, the least squares estimators <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are unbiased and have minimum variance among all unbiased linear estimators.</p>
</div>
<p>An estimator that is linear, unbiased, and has the smallest variance of all unbiased linear estimators is called the <em>best linear unbiased estimator</em> (BLUE).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
For those who want to see the math:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Proof of the Gauss Markov Theorem:</p>
<p>For all linear estimators that are unbiased, we must have <span class="math display">\[
\begin{align*}
E\left[\hat{\beta}_{1}\right] &amp; =E\left[\sum a_{i}y_i\right]\\
&amp; =\sum a_{i}E\left[y_i\right]\\
&amp; =\beta_{1}
\end{align*}
\]</span> Since <span class="math inline">\(E\left[y_i\right]=\beta_{0}+\beta_{1}x_i\)</span>, then we must have <span class="math display">\[
\begin{align*}
E\left[\hat{\beta}_{1}\right] &amp; =\sum a_{i}\left(\beta_{0}+\beta_{1}x_i\right)\\
&amp; =\beta_{0}\sum a_{i}+\beta_{1}\sum a_{i}x_i\\
&amp; =\beta_{1}
\end{align*}
\]</span> Therefore, <span class="math display">\[
\begin{align*}
\sum a_{i} &amp; =0\\
\sum a_{i}x_i &amp; =1
\end{align*}
\]</span> We now examine the variance of <span class="math inline">\(\hat{\beta}_{1}\)</span>: <span class="math display">\[
\begin{align*}
Var\left[\hat{\beta}_{1}\right] &amp; =\sum a_{i}^{2}Var\left[y_i\right]\\
&amp; =\sigma^{2}\sum a_{i}^{2}
\end{align*}
\]</span> Let’s now define <span class="math inline">\(a_{i}=k_{i}+d_{i}\)</span> where <span class="math inline">\(k_{i}\)</span> is defined in <a href="03_Properties.html#eq-w1_5">Equation&nbsp;<span>3.1</span></a>. and <span class="math inline">\(d_{i}\)</span> is some arbitrary constant.</p>
<p>We will show that adding a constant (whether negative or positive) to <span class="math inline">\(k_i\)</span> cannot make the variance smaller. Thus, the smallest variance of the linear estimator <span class="math inline">\(\hat{\beta}_1\)</span> is when <span class="math inline">\(a_i=k_i\)</span>.</p>
<p>The variance of <span class="math inline">\(\hat{\beta}_{1}\)</span> can now be written as <span class="math display">\[
\begin{align*}
Var\left[\hat{\beta}_{1}\right] &amp; =\sigma^{2}\sum a_{i}^{2}\\
&amp; =\sigma^{2}\sum\left(k_{i}+d_{i}\right)^{2}\\
&amp; =\sigma^{2}\sum\left(k_{i}^{2}+2k_{i}d_{i}+d_{i}^{2}\right)\\
&amp; =Var\left[b_1\right]+2\sigma^{2}\sum k_{i}d_{i}+\sigma^{2}\sum d_{i}^{2}
\end{align*}
\]</span> Examining the second term and using the expression of <span class="math inline">\(k_{i}\)</span> in <a href="03_Properties.html#eq-w1_5">Equation&nbsp;<span>3.1</span></a>, we see that <span class="math display">\[
\begin{align*}
\sum k_{i}d_{i} &amp; =\sum k_{i}\left(a_{i}-k_{i}\right)\\
&amp; =\sum a_{i}k_{i}-\underbrace{\sum k_{i}^{2}}_{(4.3)}\\
&amp; =\sum a_{i}\frac{x_i-\bar{x}}{\sum\left(x_i-\bar{x}\right)^{2}}-\frac{1}{\sum\left(x_i-\bar{x}\right)^{2}}\\
&amp; =\frac{\sum a_{i}x_i-\bar{x}\sum a_{i}}{\sum\left(x_i-\bar{x}\right)^{2}}-\frac{1}{\sum\left(x_i-\bar{x}\right)^{2}}\\
&amp; =\frac{1-\bar{x}\left(0\right)}{\sum\left(x_i-\bar{x}\right)^{2}}-\frac{1}{\sum\left(x_i-\bar{x}\right)^{2}}\\
&amp; =0
\end{align*}
\]</span></p>
<p>We now have the variance of <span class="math inline">\(\hat{\beta}_{1}\)</span> as <span class="math display">\[
\begin{align*}
Var\left[\hat{\beta}_{1}\right] &amp; =Var\left[b_1\right]+\sigma^{2}\sum d_{i}^{2}
\end{align*}
\]</span> This variance is minimized when <span class="math inline">\(\sum d_{i}^{2}=0\)</span> which only happens when <span class="math inline">\(d_{i}=0\)</span>.</p>
<p>Thus, the unbiased linear estimator with the smallest variance is when <span class="math inline">\(a_{i}=k_{i}\)</span>. That is, the least squares estimator <span class="math inline">\(b_1\)</span> in <a href="03_Properties.html#eq-w1_5">Equation&nbsp;<span>3.1</span></a> has the smallest variance of all unbiased linear estimators of <span class="math inline">\(\beta_{1}\)</span>.</p>
<p>A similar argument can be used to show that <span class="math inline">\(b_0\)</span> has the smallest variance of all unbiased linear estimators of <span class="math inline">\(\beta_{0}\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sampling-distribution-for-b_1" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sampling-distribution-for-b_1"><span class="header-section-number">4.5</span> Sampling Distribution for <span class="math inline">\(b_1\)</span></h2>
<p>Now that we see that the least squares estimator <span class="math inline">\(b_1\)</span> is the BLUE for <span class="math inline">\(\beta_{1}\)</span>, we will now examine the sampling distribution for <span class="math inline">\(b_1\)</span>.</p>
<p>We previously discussed that the mean of the sampling distribution of <span class="math inline">\(b_1\)</span> is <span class="math display">\[
E[b_1]=\beta_1
\]</span> with a variance of <span id="eq-w1_14"><span class="math display">\[
\begin{align}
Var\left[b_1\right]
&amp; =\frac{\sigma^{2}}{\sum \left(x_i-\bar{x}\right)^{2}}
\end{align}
\tag{4.10}\]</span></span></p>
<p>Note that in our model with our four assumptions, <span class="math inline">\(y\)</span> is normally distributed. That is, <span id="eq-4_10"><span class="math display">\[
\begin{align}
    y\sim N\left(\beta_0+\beta_1 x, \sigma^2\right)
\end{align}
\tag{4.11}\]</span></span></p>
<p>To learn about the sampling distributions of the least squares estimators, we will use the following theorems from mathematical statistics:</p>
<div id="thm-4_1" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.2 (Sum of Independent Normal Random Variables) </strong></span>If <span class="math display">\[
Y_i\sim N\left(\mu_i,\sigma_i^2\right)
\]</span> are independent, then the linear combination <span class="math inline">\(\sum_i a_iY_i\)</span> is also normally distributed where <span class="math inline">\(a_i\)</span> are constants. In particular <span class="math display">\[
\sum_i a_iY_i \sim N\left(\sum_i a_i\mu_i, \sum_i a_i^2\sigma_i^2\right)
\]</span></p>
</div>
<div id="thm-4_2" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.3 (Adding a Constant to a Normal Random Variable) </strong></span>If <span class="math display">\[
Y\sim N\left(\mu,\sigma^2\right)
\]</span> then for any real constant <span class="math inline">\(c\)</span>, <span class="math display">\[
Y+c\sim N\left(\mu+c,\sigma^2\right)
\]</span></p>
</div>
<p>Since <span class="math inline">\(Y\)</span> is normally distributed by <a href="#eq-4_10">Equation&nbsp;<span>4.11</span></a>, then we can apply <a href="#thm-4_1">Theorem&nbsp;<span>4.2</span></a> which implies that <span class="math inline">\(b_1\)</span> is normally distributed. That is, <span id="eq-w2_3"><span class="math display">\[
\begin{align}
b_1 &amp; \sim N\left(\beta_{1},\frac{\sigma^{2}}{\sum\left(x_i-\bar{x}\right)^{2}}\right)
\end{align}
\tag{4.12}\]</span></span></p>
<section id="standardized-score" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="standardized-score"><span class="header-section-number">4.5.1</span> Standardized Score</h3>
<p>Since <span class="math inline">\(b_1\)</span> is normally distributed, we can <em>standardize</em> it so that the resulting statistic will have a standard normal distribution.</p>
<p>Therefore, we have <span id="eq-w2_4"><span class="math display">\[
\begin{align}
z=\frac{b_1-\beta_{1}}{\sqrt{\frac{\sigma^{2}}{\sum\left(x_i-\bar{x}\right)^{2}}}} &amp; \sim N\left(0,1\right)
\end{align}
\tag{4.13}\]</span></span></p>
</section>
<section id="studentized-score" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="studentized-score"><span class="header-section-number">4.5.2</span> Studentized Score</h3>
<p>In practice, the standardized score <span class="math inline">\(z\)</span> is not useful since we do not know the value of <span class="math inline">\(\sigma^{2}\)</span>. We can estimate <span class="math inline">\(\sigma^{2}\)</span> with the statistic <span class="math display">\[
s^2 = \frac{SSE}{n-2}
\]</span></p>
<p>Using this estimate for <span class="math inline">\(\sigma^2\)</span> leads us to a <span class="math inline">\(t\)</span>-score: <span id="eq-w2_4b"><span class="math display">\[
\begin{align}
t=\frac{b_1-\beta_{1}}{\sqrt{\frac{s^{2}}{\sum\left(x_i-\bar{x}\right)^{2}}}} &amp; \sim t\left(n-2\right)
\end{align}
\tag{4.14}\]</span></span></p>
<p>We call this <span class="math inline">\(t\)</span> statistic, the <em>studentized</em> score.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
For those who want to see the math:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is important to note the following theorem from math stats presented here without proof:</p>
<div id="thm-04_3" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.4 (Distribution of the sample variance of the residuals) </strong></span>For the sample variance of the residuals <span class="math inline">\(s^{2}\)</span>, the quantity <span class="math display">\[\begin{align*}
\frac{\left(n-2\right)s^{2}}{\sigma^{2}} &amp; =\frac{SSE}{\sigma^{2}}
\end{align*}\]</span> is distributed as a chi-square distribution with <span class="math inline">\(n-2\)</span> degrees of freedom. That is, <span class="math display">\[\begin{align*}
\frac{SSE}{\sigma^{2}} &amp; \sim\chi^{2}\left(n-2\right)
\end{align*}\]</span></p>
</div>
<p>We will use another important theorem form math stats (again presented without proof):</p>
<div id="thm-04_4" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.5 (Ratio of independent standard normal and chi-square statistics) </strong></span>If <span class="math inline">\(Z\sim N\left(0,1\right)\)</span> and <span class="math inline">\(W\sim\chi^{2}\left(\nu\right)\)</span>, and <span class="math inline">\(Z\)</span> and <span class="math inline">\(W\)</span> are independent, then the statistic <span class="math display">\[\begin{align*}
\frac{Z}{\sqrt{\frac{W}{\nu}}}
\end{align*}\]</span> is distributed as a Student’s <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(\nu\)</span> degrees of freedom.</p>
</div>
<p>We will take the standardized score in <a href="#eq-w2_4">Equation&nbsp;<span>4.13</span></a> and divide by <span class="math display">\[\begin{align*}
\sqrt{\frac{\frac{\left(n-2\right)s^{2}}{\sigma^{2}}}{\left(n-2\right)}} &amp; =\sqrt{\frac{s^{2}}{\sigma^{2}}}
\end{align*}\]</span> to give us <span class="math display">\[\begin{align*}
t &amp; =\frac{\frac{b_1-\beta_{1}}{\sqrt{\frac{\sigma^{2}}{\sum\left(x_i-\overline{X}\right)^{2}}}}}{\sqrt{\frac{s^{2}}{\sigma^{2}}}}\\
&amp; =\frac{b_1-\beta_{1}}{\sqrt{\frac{\sigma^{2}}{\sum\left(x_i-\overline{X}\right)^{2}}}\sqrt{\frac{s^{2}}{\sigma^{2}}}}\\
&amp; =\frac{b_1-\beta_{1}}{\sqrt{\frac{s^{2}}{\sum\left(x_i-\overline{X}\right)^{2}}}}
\end{align*}\]</span> which will have a Student’s <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
</div>
</div>
</div>
</section>
</section>
<section id="sec-modelutility" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="sec-modelutility"><span class="header-section-number">4.6</span> Assessing the Utility of the Model: Making Inferences About the Slope</h2>
<p>Suppose that the independent variable <span class="math inline">\(x\)</span> is completely unrelated to the dependent variable <span class="math inline">\(y\)</span>.</p>
<p>What could be said about the values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in the hypothesized probabilistic model <span class="math display">\[\begin{align*}
    y = \beta_0 +\beta_1 x + \varepsilon
\end{align*}\]</span> if <span class="math inline">\(x\)</span> contributes no information for the prediction of <span class="math inline">\(y\)</span>?</p>
<p>The implication is that the mean of <span class="math inline">\(y\)</span>, does not change as <span class="math inline">\(x\)</span> changes. In other words, the line would just be a <em>horizontal</em> line.</p>
<p>If <span class="math inline">\(E(y)\)</span> does not change as <span class="math inline">\(x\)</span> increases, then using <span class="math inline">\(x\)</span> to predict <span class="math inline">\(y\)</span> in the linear model is not <em>useful</em>.</p>
<p>Regardless of the value of <span class="math inline">\(x\)</span>, you always predict the same value of <span class="math inline">\(y\)</span>. In the straight-line model, this means that the true slope, <span class="math inline">\(\beta_1\)</span>, is equal to 0.</p>
<p>Therefore, to test the null hypothesis that <span class="math inline">\(x\)</span> contributes no information for the prediction of <span class="math inline">\(y\)</span> against the alternative hypothesis that these variables are <em>linearly</em> related with a slope differing from 0, we test <span class="math display">\[\begin{align*}
    H_0:\beta_1 = 0\\
    H_a:\beta_1\ne 0
\end{align*}\]</span></p>
<p>If the data support the alternative hypothesis, we conclude that <span class="math inline">\(x\)</span> does contribute information for the prediction of <span class="math inline">\(y\)</span> using the straight-line model (although the true relationship between <span class="math inline">\(E(y)\)</span> and <span class="math inline">\(x\)</span> could be more complex than a straight line). Thus, to some extent, this is a test of the <em>utility</em> of the hypothesized model.</p>
<p>The appropriate test statistic is the studentized score given above: <span id="eq-4_14"><span class="math display">\[
\begin{align}
    t &amp;= \frac{b_1-\beta_{1}}{\sqrt{\frac{s^{2}}{\sum\left(x_i-\overline{X}\right)^{2}}}}\\
    &amp;=\frac{b_1}{\sqrt{\frac{s^{2}}{SS_{xx}}}}
\end{align}
\tag{4.15}\]</span></span></p>
<p>Another way to make inferences about the slope <span class="math inline">\(\beta_1\)</span> is to estimate it using a <em>confidence</em> <em>interval</em> <span id="eq-4_15"><span class="math display">\[
\begin{align}
    b_1 \pm \left(t_{\alpha/2}\right)s_{b_1}
\end{align}
\tag{4.16}\]</span></span> where <span class="math display">\[\begin{align*}
    s_{b_1} = \frac{s}{\sqrt{SS_{xx}}}
\end{align*}\]</span></p>
<p>We can obtain the p-value for the hypothesis test by using the <code>summary</code> function with an <code>lm</code> object. For the previous example consisting of the <code>mtcars</code> data.</p>
<div id="exm-4_1" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.1 (<a href="03_Properties.html#exm-3_1">Example&nbsp;<span>3.1</span></a> - revisited) </strong></span>&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(mpg<span class="sc">~</span>wt, <span class="at">data =</span> mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We find the least squares estimates as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5432 -2.3647 -0.1252  1.4096  6.8727 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
wt           -5.3445     0.5591  -9.559 1.29e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.046 on 30 degrees of freedom
Multiple R-squared:  0.7528,    Adjusted R-squared:  0.7446 
F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
</div>
</div>
<p>From the output, we see the p-value is <span class="math inline">\(1.29\times 10^{-10}\)</span>. So we have sufficient evidence to conclude that the true population slope is different than zero.</p>
<p>To find the confidence interval, we can use the <code>confint</code> function with the <code>lm</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(fit, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 33.450500 41.119753
wt          -6.486308 -4.202635</code></pre>
</div>
</div>
<p>We 95% confident that the true population slope is in the interval <span class="math inline">\((-6.486, -4.203)\)</span></p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_Properties.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Properties of the Least Squares Estimators and Model Assumptions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_Correlation.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation Coefficient and the Coefficient of Determination</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">STA 3386</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Fall 2024</div>
  </div>
</footer>



</body></html>