<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>STA 3386 Regression Analysis - 9&nbsp; Simple Linear Regression with Tidymodels</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08_Checking2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09_Tidymodels.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression with Tidymodels</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Regression Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fitting the Simple Linear Regression Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Properties of the Least Squares Estimators and Model Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling Distribution of the Least Squares Estimators and Testing the Slope</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation Coefficient and the Coefficient of Determination</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Using.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Using the Simple Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Checking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Checking the Linearity and Constant Variance Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Checking2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Checking the Normality and Independence Assumptions and Outliers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_Tidymodels.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression with Tidymodels</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#specifying-the-model" id="toc-specifying-the-model" class="nav-link active" data-scroll-target="#specifying-the-model"><span class="header-section-number">9.1</span> Specifying the Model</a>
  <ul class="collapse">
  <li><a href="#model-specification-with-parsnip" id="toc-model-specification-with-parsnip" class="nav-link" data-scroll-target="#model-specification-with-parsnip"><span class="header-section-number">9.1.1</span> Model Specification with <code>parsnip</code></a></li>
  <li><a href="#hyperparameters-and-engine-customization" id="toc-hyperparameters-and-engine-customization" class="nav-link" data-scroll-target="#hyperparameters-and-engine-customization"><span class="header-section-number">9.1.2</span> Hyperparameters and Engine Customization</a></li>
  <li><a href="#choosing-the-right-model-and-engine" id="toc-choosing-the-right-model-and-engine" class="nav-link" data-scroll-target="#choosing-the-right-model-and-engine"><span class="header-section-number">9.1.3</span> Choosing the Right Model and Engine</a></li>
  <li><a href="#benefits-of-model-specification-with-parsnip" id="toc-benefits-of-model-specification-with-parsnip" class="nav-link" data-scroll-target="#benefits-of-model-specification-with-parsnip"><span class="header-section-number">9.1.4</span> Benefits of Model Specification with <code>parsnip</code></a></li>
  </ul></li>
  <li><a href="#defining-the-workflow" id="toc-defining-the-workflow" class="nav-link" data-scroll-target="#defining-the-workflow"><span class="header-section-number">9.2</span> Defining the Workflow</a>
  <ul class="collapse">
  <li><a href="#what-is-a-workflow" id="toc-what-is-a-workflow" class="nav-link" data-scroll-target="#what-is-a-workflow"><span class="header-section-number">9.2.1</span> What is a Workflow?</a></li>
  <li><a href="#creating-a-workflow-for-simple-linear-regression" id="toc-creating-a-workflow-for-simple-linear-regression" class="nav-link" data-scroll-target="#creating-a-workflow-for-simple-linear-regression"><span class="header-section-number">9.2.2</span> Creating a Workflow for Simple Linear Regression</a></li>
  <li><a href="#the-formula-interface" id="toc-the-formula-interface" class="nav-link" data-scroll-target="#the-formula-interface"><span class="header-section-number">9.2.3</span> The Formula Interface</a></li>
  <li><a href="#preprocessing-in-workflows" id="toc-preprocessing-in-workflows" class="nav-link" data-scroll-target="#preprocessing-in-workflows"><span class="header-section-number">9.2.4</span> Preprocessing in Workflows</a></li>
  <li><a href="#why-use-workflows" id="toc-why-use-workflows" class="nav-link" data-scroll-target="#why-use-workflows"><span class="header-section-number">9.2.5</span> Why Use Workflows?</a></li>
  </ul></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model"><span class="header-section-number">9.3</span> Fitting the Model</a>
  <ul class="collapse">
  <li><a href="#the-fit-function" id="toc-the-fit-function" class="nav-link" data-scroll-target="#the-fit-function"><span class="header-section-number">9.3.1</span> The <code>fit()</code> Function</a></li>
  <li><a href="#model-output" id="toc-model-output" class="nav-link" data-scroll-target="#model-output"><span class="header-section-number">9.3.2</span> Model Output</a></li>
  <li><a href="#extracting-model-coefficients" id="toc-extracting-model-coefficients" class="nav-link" data-scroll-target="#extracting-model-coefficients"><span class="header-section-number">9.3.3</span> Extracting Model Coefficients</a></li>
  <li><a href="#model-predictions" id="toc-model-predictions" class="nav-link" data-scroll-target="#model-predictions"><span class="header-section-number">9.3.4</span> Model Predictions</a></li>
  <li><a href="#performance-metrics" id="toc-performance-metrics" class="nav-link" data-scroll-target="#performance-metrics"><span class="header-section-number">9.3.5</span> Performance Metrics</a></li>
  </ul></li>
  <li><a href="#model-diagnostics" id="toc-model-diagnostics" class="nav-link" data-scroll-target="#model-diagnostics"><span class="header-section-number">9.4</span> Model Diagnostics</a>
  <ul class="collapse">
  <li><a href="#residuals-and-fitted-values" id="toc-residuals-and-fitted-values" class="nav-link" data-scroll-target="#residuals-and-fitted-values"><span class="header-section-number">9.4.1</span> Residuals and Fitted Values</a></li>
  <li><a href="#plotting-residuals-vs.-fitted-values" id="toc-plotting-residuals-vs.-fitted-values" class="nav-link" data-scroll-target="#plotting-residuals-vs.-fitted-values"><span class="header-section-number">9.4.2</span> Plotting Residuals vs.&nbsp;Fitted Values</a></li>
  <li><a href="#checking-homoscedasticity-constant-variance" id="toc-checking-homoscedasticity-constant-variance" class="nav-link" data-scroll-target="#checking-homoscedasticity-constant-variance"><span class="header-section-number">9.4.3</span> Checking Homoscedasticity (Constant Variance)</a></li>
  <li><a href="#normality-of-residuals" id="toc-normality-of-residuals" class="nav-link" data-scroll-target="#normality-of-residuals"><span class="header-section-number">9.4.4</span> Normality of Residuals</a></li>
  <li><a href="#checking-for-independence-of-errors" id="toc-checking-for-independence-of-errors" class="nav-link" data-scroll-target="#checking-for-independence-of-errors"><span class="header-section-number">9.4.5</span> Checking for Independence of Errors</a></li>
  <li><a href="#detecting-outliers" id="toc-detecting-outliers" class="nav-link" data-scroll-target="#detecting-outliers"><span class="header-section-number">9.4.6</span> Detecting Outliers</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">9.5</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression with Tidymodels</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<blockquote class="blockquote">
<p>“Knowledge is a process of piling up facts; wisdom lies in their simplification.” - Martin Luther King Jr.&nbsp;</p>
</blockquote>
<p>In this chapter, we will introduce the <code>tidymodels</code> framework for fitting a simple linear regression model. <code>tidymodels</code> is a collection of R packages that work together to streamline the modeling process, from data preparation to model tuning and evaluation. The main packages involved in fitting models are <code>parsnip</code> for specifying models and <code>recipes</code> for preprocessing data. Most necessary packages used in this framework can be loaded with the <code>tidymodels</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will illustrate with the <code>mtcars</code> data first used in <a href="03_Properties.html#exm-3_1">Example&nbsp;<span>3.1</span></a>.</p>
<section id="specifying-the-model" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="specifying-the-model"><span class="header-section-number">9.1</span> Specifying the Model</h2>
<p>In <code>tidymodels</code>, the first step in model building is to define the type of model you want to fit. The <code>parsnip</code> package is the tool within <code>tidymodels</code> that handles model specification. Unlike the traditional approach where you directly use a modeling function like <code>lm()</code>, <code>parsnip</code> separates the model definition from the model fitting, making the process more modular and adaptable to different engines (i.e., different computational backends).</p>
<section id="model-specification-with-parsnip" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="model-specification-with-parsnip"><span class="header-section-number">9.1.1</span> Model Specification with <code>parsnip</code></h3>
<p>The primary function to specify a model in <code>parsnip</code> is <code>linear_reg()</code>, which indicates that you are building a linear regression model. However, <code>linear_reg()</code> does not fit the model by itself. Instead, it allows you to define the general structure of the model, which is then paired with a computational engine. An engine is the specific function or package that will perform the calculations. For linear regression, the default engine is <code>"lm"</code>, which corresponds to R’s base <code>lm()</code> function.</p>
<p>Let’s break down how the model specification works:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify a linear regression model</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">=</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>linear_reg()</code>: This specifies that we are interested in a linear regression model. The model type is abstracted, allowing us to focus on the statistical method (linear regression) rather than the computational details.</li>
<li><code>set_engine("lm")</code>: This command specifies that we will use the <code>"lm"</code> engine to estimate the linear regression parameters. <code>parsnip</code> supports other engines, such as <code>glmnet</code> for penalized regression models and <code>stan</code> for Bayesian regression models, which allows for great flexibility in model building.</li>
</ul>
</section>
<section id="hyperparameters-and-engine-customization" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="hyperparameters-and-engine-customization"><span class="header-section-number">9.1.2</span> Hyperparameters and Engine Customization</h3>
<p>You can also specify hyperparameters, which are settings that influence the model fitting process. For simple linear regression with the <code>"lm"</code> engine, there are no specific hyperparameters to set, but with more complex models (such as regularized regression), you might need to tune parameters like the penalty term or the mixture parameter for Lasso or Ridge regression (discussed in a later chapter).</p>
<p>An example of specifying a model with hyperparameters (for demonstration purposes):</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example for models that require hyperparameters</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ridge_model <span class="ot">=</span> <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="fl">0.1</span>, <span class="at">mixture =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Although these hyperparameters are not necessary for simple linear regression, <code>parsnip</code> enables seamless transition to more complex models, and this flexibility is a key feature of the <code>tidymodels</code> framework.</p>
</section>
<section id="choosing-the-right-model-and-engine" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="choosing-the-right-model-and-engine"><span class="header-section-number">9.1.3</span> Choosing the Right Model and Engine</h3>
<p>One of the strengths of the <code>parsnip</code> package is that it decouples the conceptual model (linear regression) from the computational engine (e.g., <code>"lm"</code>, <code>"glmnet"</code>, <code>"stan"</code>). This allows the user to switch engines without changing the model structure.</p>
<p>For example, suppose you wanted to fit the same linear regression model using a Bayesian approach via the <code>stan</code> engine:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify a Bayesian linear regression model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>bayesian_lm_model <span class="ot">=</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"stan"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>In this case, the model structure remains the same, but the estimation procedure differs (frequentist vs.&nbsp;Bayesian). This level of abstraction enhances the flexibility of your workflow, especially as you explore different modeling approaches.</p>
</section>
<section id="benefits-of-model-specification-with-parsnip" class="level3" data-number="9.1.4">
<h3 data-number="9.1.4" class="anchored" data-anchor-id="benefits-of-model-specification-with-parsnip"><span class="header-section-number">9.1.4</span> Benefits of Model Specification with <code>parsnip</code></h3>
<p>The model specification process in <code>parsnip</code> offers several key benefits. Its modularity allows for the separation of model specification from model fitting, enabling you to reuse the same model definition across different datasets or engines. This framework provides flexibility, making it easy to switch between various engines, such as <code>lm()</code>, <code>glmnet()</code>, or <code>stan</code>, without altering the core model structure.</p>
<p>Additionally, <code>parsnip</code> enhances scalability by simplifying the process of extending models. For example, moving from simple linear regression to more complex models like Ridge or Lasso regression only requires adjusting the engine and hyperparameters, without the need to rewrite your code.</p>
<p>In this section, we have seen how to specify a linear regression model using <code>parsnip</code> and set the engine to <code>"lm"</code>. Next, we will define the relationship between the predictor and response variables and organize our workflow before fitting the model.</p>
</section>
</section>
<section id="defining-the-workflow" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="defining-the-workflow"><span class="header-section-number">9.2</span> Defining the Workflow</h2>
<p>In the <code>tidymodels</code> ecosystem, workflows serve as a central organizing structure that ties together the components of a model-building process. A workflow in <code>tidymodels</code> allows you to combine different elements, such as the model specification, preprocessing steps, and the formula that defines the relationship between the predictor(s) and response. This section will explain the importance of workflows and demonstrate how to create one for simple linear regression.</p>
<section id="what-is-a-workflow" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="what-is-a-workflow"><span class="header-section-number">9.2.1</span> What is a Workflow?</h3>
<p>A workflow can be thought of as a blueprint that organizes how data flows through different steps of the modeling process. It encapsulates model specification and data preprocessing tasks, which can include transformations such as scaling, normalization, or encoding categorical variables. In traditional modeling approaches, these steps are often written separately, which can lead to code that is harder to manage and prone to errors, especially as the complexity of the model increases.</p>
<p>With workflows, the entire process becomes more organized and reproducible. The key benefit is that you don’t need to repeatedly specify how the data should be prepared or how the model should be fit. Once a workflow is defined, it can be reused or modified easily to fit different models or datasets.</p>
</section>
<section id="creating-a-workflow-for-simple-linear-regression" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="creating-a-workflow-for-simple-linear-regression"><span class="header-section-number">9.2.2</span> Creating a Workflow for Simple Linear Regression</h3>
<p>For a simple linear regression model, our workflow consists of two main components: the formula that defines the relationship between the response and predictor variables, and the model specification itself. Since simple linear regression does not require extensive preprocessing (like handling categorical variables or missing data), the workflow is relatively straightforward.</p>
<p>Let’s begin by constructing the workflow for predicting miles per gallon (<code>mpg</code>) using horsepower (<code>hp</code>) from the <code>mtcars</code> dataset. Recall that the model specification (<code>lm_model</code>) was defined in the previous section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a workflow</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>lm_workflow <span class="ot">=</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_model) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_formula</span>(mpg <span class="sc">~</span> hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this code:</p>
<ul>
<li><code>workflow()</code> initializes an empty workflow.</li>
<li><code>add_model()</code> adds the linear regression model (<code>lm_model</code>) that was specified earlier using the <code>parsnip</code> package.</li>
<li><code>add_formula()</code> defines the model’s formula, which indicates that the response variable <code>mpg</code> is modeled as a function of the predictor <code>hp</code>.</li>
</ul>
<p>The formula-based approach used in this workflow is intuitive for most users familiar with R’s base modeling functions, such as <code>lm()</code> and <code>glm()</code>. However, workflows also support more advanced techniques, such as specifying custom preprocessing steps with the <code>recipes</code> package, which we will explore later.</p>
</section>
<section id="the-formula-interface" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="the-formula-interface"><span class="header-section-number">9.2.3</span> The Formula Interface</h3>
<p>The formula interface in <code>tidymodels</code> is a key aspect of defining relationships between variables. The tilde (<code>~</code>) symbol is used to separate the response variable (on the left-hand side) from the predictor(s) (on the right-hand side). In the example <code>mpg ~ hp</code>, the model will predict <code>mpg</code> using <code>hp</code> as the predictor. This is a simple linear regression model, where the model assumes a linear relationship between these two variables.</p>
<p>If there were multiple predictors, the formula would include them on the right-hand side, separated by a plus sign (<code>+</code>), such as <code>mpg ~ hp + wt + qsec</code>, indicating a multiple linear regression model. The formula syntax allows for flexible model building, including interaction terms (<code>*</code> or <code>:</code>) and transformations (e.g., <code>log()</code> or polynomial terms).</p>
</section>
<section id="preprocessing-in-workflows" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="preprocessing-in-workflows"><span class="header-section-number">9.2.4</span> Preprocessing in Workflows</h3>
<p>One of the primary advantages of using workflows is the ability to integrate preprocessing steps seamlessly into the model-building process. While simple linear regression may not require extensive preprocessing, workflows can easily handle more complex tasks, such as:</p>
<ul>
<li><strong>Standardizing predictors</strong>: Scaling variables to have mean 0 and standard deviation 1.</li>
<li><strong>Handling missing data</strong>: Imputing missing values.</li>
<li><strong>Encoding categorical variables</strong>: Converting factors into dummy or one-hot encoded variables.</li>
</ul>
<p>For example, suppose that instead of horsepower (<code>hp</code>), we had a categorical variable representing car transmission type (<code>am</code>), and we wanted to include it as a predictor. In this case, we could use the <code>recipes</code> package to preprocess the data by encoding the categorical variable. The workflow can be extended as follows:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example of adding preprocessing using recipes</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>recipe <span class="ot">=</span> <span class="fu">recipe</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> am, <span class="at">data =</span> mtcars) <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>())</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>lm_workflow <span class="ot">=</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lm_model) <span class="sc">|&gt;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(recipe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>In this example, <code>recipe()</code> initializes a preprocessing recipe that converts the categorical predictor <code>am</code> into a set of dummy variables. <code>step_dummy()</code> is one of many preprocessing steps available in the <code>recipes</code> package.</p>
</section>
<section id="why-use-workflows" class="level3" data-number="9.2.5">
<h3 data-number="9.2.5" class="anchored" data-anchor-id="why-use-workflows"><span class="header-section-number">9.2.5</span> Why Use Workflows?</h3>
<p>Workflows provide several key benefits when building models with <code>tidymodels</code>:</p>
<ul>
<li><strong>Reproducibility</strong>: By encapsulating the entire modeling process into a workflow, the model can be easily reproduced, reducing the chances of human error. Each step is clearly defined and can be executed in a consistent manner.</li>
<li><strong>Modularity</strong>: You can modify or swap out different components of the workflow—such as changing the model from linear regression to a different type of regression—without rewriting significant portions of your code.</li>
<li><strong>Separation of Concerns</strong>: Workflows help you organize your code by clearly separating data preprocessing, model specification, and model fitting. This makes it easier to debug, extend, or modify your models later on.</li>
<li><strong>Preprocessing Integration</strong>: Workflows enable the integration of complex preprocessing pipelines, ensuring that data transformations and model fitting occur seamlessly within a single structure. This is especially useful for more advanced models, where data preprocessing steps are often critical to model performance.</li>
</ul>
<p>In this section, we introduced the concept of workflows in <code>tidymodels</code>, which serves as a crucial tool for organizing and managing the different components of the modeling process. For simple linear regression, the workflow was relatively simple, involving a formula and a model specification. However, workflows can be extended to handle more complex models and preprocessing tasks as we will see in later chapters. By using workflows, you ensure that your model-building process is organized, reproducible, and adaptable to future changes.</p>
</section>
</section>
<section id="fitting-the-model" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="fitting-the-model"><span class="header-section-number">9.3</span> Fitting the Model</h2>
<p>Once the model and workflow have been defined, the next step is to fit the model to the data. In <code>tidymodels</code>, this is done using the <code>fit()</code> function, which estimates the model parameters (such as the intercept and slope in simple linear regression) based on the data provided. The fitting process involves using the workflow to apply the model specification and formula to the dataset.</p>
<section id="the-fit-function" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="the-fit-function"><span class="header-section-number">9.3.1</span> The <code>fit()</code> Function</h3>
<p>The <code>fit()</code> function is a central function in the modeling process that takes the workflow and the data as inputs. It applies the formula and estimates the model’s parameters by minimizing the SSE (for linear regression models) or another appropriate criterion depending on the model type.</p>
<p>For our simple linear regression model, we fit the model using the <code>mtcars</code> dataset, where the response variable is <code>mpg</code> (miles per gallon) and the predictor is <code>hp</code> (horsepower).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">=</span> lm_workflow <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this command:</p>
<ul>
<li><code>lm_workflow</code>: The workflow containing the model and the formula for simple linear regression.</li>
<li><code>data = mtcars</code>: The dataset used to fit the model. The model will use this data to estimate the parameters <span class="math inline">\(\beta_0\)</span> (the intercept) and <span class="math inline">\(\beta_1\)</span> (the slope).</li>
</ul>
<p>The <code>fit()</code> function then processes the data, applies the specified formula (<code>mpg ~ hp</code>), and estimates the model parameters using the specified engine (<code>lm</code> in this case). In the background, <code>tidymodels</code> calls the R base <code>lm()</code> function to fit the model, but the workflow structure abstracts these technical details, making it easier to switch between engines without altering the core syntax.</p>
</section>
<section id="model-output" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="model-output"><span class="header-section-number">9.3.2</span> Model Output</h3>
<p>After fitting the model, it’s essential to inspect the model’s output to understand the estimated relationship between the predictor and response variables. The fitted workflow object (<code>lm_fit</code>) contains a number of important details, including the estimated coefficients for the linear model, the residuals, and performance metrics.</p>
<p>Let’s start by examining the output of the fitted model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the model fit summary</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>lm_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Formula
Model: linear_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
mpg ~ hp

── Model ───────────────────────────────────────────────────────────────────────

Call:
stats::lm(formula = ..y ~ ., data = data)

Coefficients:
(Intercept)           hp  
   30.09886     -0.06823  </code></pre>
</div>
</div>
<p>The output of <code>lm_fit</code> provides an overview of the fitted model, including the coefficients for the intercept and slope. This information is crucial for interpreting the relationship between the predictor and the response variable. Specifically, the estimated intercept (<span class="math inline">\(b_0\)</span>) represents the expected value of <code>mpg</code> when <code>hp</code> is zero, and the slope (<span class="math inline">\(b_1\)</span>) represents the expected change in <code>mpg</code> for each one-unit increase in <code>hp</code>.</p>
</section>
<section id="extracting-model-coefficients" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="extracting-model-coefficients"><span class="header-section-number">9.3.3</span> Extracting Model Coefficients</h3>
<p>To better understand the results, you can extract the estimated coefficients from the model using the <code>tidy()</code> function from the <code>broom</code> package, which is part of the <code>tidymodels</code> ecosystem. This function provides a clean, easy-to-read summary of the model’s coefficients, along with other important statistics such as standard errors, t-values, and p-values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficients</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)  30.1       1.63       18.4  6.64e-18
2 hp           -0.0682    0.0101     -6.74 1.79e- 7</code></pre>
</div>
</div>
<p>This table shows the estimated coefficients for the intercept and slope:</p>
<ul>
<li><strong>Intercept</strong>: The estimated intercept (<span class="math inline">\(b_0\)</span>) is 30.10, meaning that when <code>hp</code> is zero, the predicted <code>mpg</code> is approximately 30.10. In this example, the interpretation is not practical.</li>
<li><strong>Slope</strong>: The estimated slope (<span class="math inline">\(b_1\)</span>) is -0.068, indicating that for each additional unit of horsepower, the <code>mpg</code> decreases by about 0.068 miles per gallon, on average. The negative sign confirms an inverse relationship between <code>mpg</code> and <code>hp</code>.</li>
</ul>
<p>Additionally, the table provides the standard errors, t-statistics, and p-values, which are useful for assessing the statistical significance of the estimated coefficients. In this case, both the intercept and the slope have very small p-values (less than 0.001), suggesting that they are statistically significant at conventional significance levels (e.g., 0.05).</p>
</section>
<section id="model-predictions" class="level3" data-number="9.3.4">
<h3 data-number="9.3.4" class="anchored" data-anchor-id="model-predictions"><span class="header-section-number">9.3.4</span> Model Predictions</h3>
<p>After fitting the model, it’s often useful to make predictions based on new or existing data. The <code>predict()</code> function allows you to generate predictions from the fitted model. In this case, we’ll generate predictions using the original dataset (<code>mtcars</code>), though in practice, you would typically use the model to predict on new, unseen data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the original data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> lm_fit <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">new_data =</span> mtcars)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Add predictions to the original data</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>mtcars_with_preds <span class="ot">=</span> mtcars <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mpg, hp) <span class="sc">|&gt;</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">predicted_mpg =</span> predictions<span class="sc">$</span>.pred)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># View the predictions</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars_with_preds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg  hp predicted_mpg
Mazda RX4         21.0 110      22.59375
Mazda RX4 Wag     21.0 110      22.59375
Datsun 710        22.8  93      23.75363
Hornet 4 Drive    21.4 110      22.59375
Hornet Sportabout 18.7 175      18.15891
Valiant           18.1 105      22.93489</code></pre>
</div>
</div>
<p>In this example, we use the <code>predict()</code> function to generate predicted values of <code>mpg</code> for each observation in the <code>mtcars</code> dataset. These predictions are stored in a new column called <code>predicted_mpg</code>. Comparing the predicted values to the actual values allows us to assess how well the model fits the data.</p>
</section>
<section id="performance-metrics" class="level3" data-number="9.3.5">
<h3 data-number="9.3.5" class="anchored" data-anchor-id="performance-metrics"><span class="header-section-number">9.3.5</span> Performance Metrics</h3>
<p>Once predictions have been made, it’s important to evaluate the model’s performance. One common metric for regression models is the Root Mean Squared Error (RMSE), which measures the average difference between the predicted and actual values. Lower RMSE values indicate better model performance.</p>
<p>You can calculate the RMSE and other performance metrics using the <code>yardstick</code> package, another component of the <code>tidymodels</code> framework.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate RMSE</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">=</span> lm_fit <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="at">new_data =</span> mtcars) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(mtcars) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> mpg, <span class="at">estimate =</span> .pred)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View performance metrics</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>metrics</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard       3.74 
2 rsq     standard       0.602
3 mae     standard       2.91 </code></pre>
</div>
</div>
<p>This will output the RMSE, along with other useful metrics like the Mean Absolute Error (MAE) and R-squared.</p>
<ul>
<li><code>rmse</code>: The Root Mean Squared Error (RMSE) is approximately 3.74, meaning that, on average, the model’s predictions are off by about 3.74 miles per gallon.</li>
<li><code>rsq</code>: The R-squared value is 0.60, indicating that the model explains about 60% of the variation in <code>mpg</code>.</li>
</ul>
<p>In this section, we demonstrated how to fit a simple linear regression model using the <code>fit()</code> function in <code>tidymodels</code>. We also explored how to extract and interpret the model coefficients, make predictions, and evaluate model performance using metrics like RMSE and R-squared. By abstracting the fitting process into a workflow, <code>tidymodels</code> makes it easy to manage and evaluate models in a structured and reproducible way. In the next section, we will delve into model diagnostics to assess how well the assumptions of linear regression are met in this fitted model.</p>
</section>
</section>
<section id="model-diagnostics" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="model-diagnostics"><span class="header-section-number">9.4</span> Model Diagnostics</h2>
<p>After fitting a linear regression model, it’s essential to check the underlying assumptions to ensure that the model is appropriate for the data and that the results can be trusted. These assumptions include linearity, constant variance (homoscedasticity) of the residuals, independence of errors, and normally distributed errors. Violations of these assumptions can lead to biased estimates or misleading inference. In this section, we will focus on diagnosing these assumptions using residual plots and other techniques, leveraging the <code>tidymodels</code> framework.</p>
<section id="residuals-and-fitted-values" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="residuals-and-fitted-values"><span class="header-section-number">9.4.1</span> Residuals and Fitted Values</h3>
<p>To start our diagnostics, we will generate the residuals and fitted values using the <code>augment()</code> function from the <code>broom</code> package, which adds additional information such as residuals and fitted values to the original dataset. To use <code>augment</code> we must first extract the fitted model from the overall fitted workflow with the <code>extract_fit_engine</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Augment the model with residuals and fitted values</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">extract_fit_engine</span>(lm_fit) <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>()</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of augmented data</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
    ..y    hp .fitted .resid   .hat .sigma  .cooksd .std.resid
  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
1  21     110    22.6 -1.59  0.0405   3.92 0.00374      -0.421
2  21     110    22.6 -1.59  0.0405   3.92 0.00374      -0.421
3  22.8    93    23.8 -0.954 0.0510   3.92 0.00173      -0.253
4  21.4   110    22.6 -1.19  0.0405   3.92 0.00210      -0.315
5  18.7   175    18.2  0.541 0.0368   3.93 0.000389      0.143
6  18.1   105    22.9 -4.83  0.0432   3.82 0.0369       -1.28 </code></pre>
</div>
</div>
</section>
<section id="plotting-residuals-vs.-fitted-values" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="plotting-residuals-vs.-fitted-values"><span class="header-section-number">9.4.2</span> Plotting Residuals vs.&nbsp;Fitted Values</h3>
<p>A key diagnostic plot for linear regression is the residuals versus fitted values plot. This plot helps assess the assumption of linearity and constant variance (homoscedasticity). In a well-behaved model, the residuals should exhibit no clear pattern and should have constant spread across all levels of the fitted values.</p>
<p>Let’s create the residuals vs.&nbsp;fitted values plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot residuals vs. fitted values</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predictions, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted Values"</span>, <span class="at">y =</span> <span class="st">"Residuals"</span>, <span class="at">title =</span> <span class="st">"Residuals vs. Fitted Values"</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09_Tidymodels_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>In this plot:</p>
<ul>
<li>The x-axis represents the fitted values (predicted <code>mpg</code> from the model).</li>
<li>The y-axis represents the residuals (differences between observed and predicted <code>mpg</code>).</li>
<li>The dashed red line at zero represents where the residuals would lie if the model were perfect.</li>
</ul>
</section>
<section id="checking-homoscedasticity-constant-variance" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="checking-homoscedasticity-constant-variance"><span class="header-section-number">9.4.3</span> Checking Homoscedasticity (Constant Variance)</h3>
<p>Another assumption of linear regression is that the residuals should have constant variance, also known as homoscedasticity. If the spread of residuals increases or decreases with the fitted values, the assumption of constant variance is violated, which can lead to inefficient estimates and biased standard errors.</p>
<p>In the residuals vs.&nbsp;fitted values plot, this would manifest as a “funnel” shape, where the residuals get larger (or smaller) as the fitted values increase. If you observe this pattern, it suggests heteroscedasticity, and you may need to consider a transformation of the response variable or use robust standard errors to account for the non-constant variance.</p>
</section>
<section id="normality-of-residuals" class="level3" data-number="9.4.4">
<h3 data-number="9.4.4" class="anchored" data-anchor-id="normality-of-residuals"><span class="header-section-number">9.4.4</span> Normality of Residuals</h3>
<p>Linear regression assumes that the residuals are normally distributed. A common way to check this assumption is to create a Q-Q (quantile-quantile) plot, which compares the quantiles of the residuals to the quantiles of a normal distribution. If the residuals are normally distributed, the points should fall roughly along a 45-degree line.</p>
<p>Let’s create a Q-Q plot using <code>ggplot2</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q-Q plot of residuals</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predictions, <span class="fu">aes</span>(<span class="at">sample =</span> .resid)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Q-Q Plot of Residuals"</span>) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09_Tidymodels_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>In the Q-Q plot:</p>
<ul>
<li>If the residuals are normally distributed, the points will fall along the 45-degree reference line.</li>
<li>Deviations from this line, especially at the tails, suggest that the residuals may not follow a normal distribution.</li>
</ul>
<p>If the normality assumption is violated (e.g., heavy tails or skewness), it may be necessary to apply a transformation to the response variable or explore alternative models that do not assume normality, such as generalized linear models.</p>
</section>
<section id="checking-for-independence-of-errors" class="level3" data-number="9.4.5">
<h3 data-number="9.4.5" class="anchored" data-anchor-id="checking-for-independence-of-errors"><span class="header-section-number">9.4.5</span> Checking for Independence of Errors</h3>
<p>Another important assumption is that the errors (or residuals) should be independent of one another. This is especially relevant in time series data, where errors may be autocorrelated (i.e., residuals at one time point may be related to residuals at nearby time points). We can used the residuals in an ACF plot to determine if there is significant autocorrelation at a lag.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggAcf</span>(predictions<span class="sc">$</span>.resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09_Tidymodels_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="576"></p>
</div>
</div>
</section>
<section id="detecting-outliers" class="level3" data-number="9.4.6">
<h3 data-number="9.4.6" class="anchored" data-anchor-id="detecting-outliers"><span class="header-section-number">9.4.6</span> Detecting Outliers</h3>
<p>To identify potential outliers, you can plot the standardized residuals, which are residuals divided by their estimated standard deviation. Residuals with an absolute value greater than 2 or 3 are often considered potential outliers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot standardized residuals</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(predictions, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted Values"</span>, <span class="at">y =</span> <span class="st">"Standardized Residuals"</span>, <span class="at">title =</span> <span class="st">"Standardized Residuals vs. Fitted Values"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09_Tidymodels_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="576"></p>
</div>
</div>
<p>In this plot:</p>
<ul>
<li>Points outside the dashed lines (at standardized residuals of -2 and 2) are potential outliers. These points should be investigated further to understand why they deviate from the model’s predictions.</li>
</ul>
</section>
</section>
<section id="summary" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="summary"><span class="header-section-number">9.5</span> Summary</h2>
<p>In this chapter, we demonstrated how to use the <code>tidymodels</code> framework to fit a simple linear regression model. We covered the key steps, including specifying the model with <code>parsnip</code>, building a workflow, and fitting the model. Additionally, we explored how to extract model results and perform basic diagnostics.</p>
<p>The <code>tidymodels</code> ecosystem offers a flexible and organized approach to model building, and in future chapters, we will expand this framework to handle more complex regression models and advanced techniques such as cross-validation and model tuning.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08_Checking2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Checking the Normality and Independence Assumptions and Outliers</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">STA 3386</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Fall 2024</div>
  </div>
</footer>



</body></html>