{
  "hash": "4561544a656193bd197336ea600a0b2f",
  "result": {
    "engine": "knitr",
    "markdown": "---\neditor: \n  markdown: \n    wrap: 72\n---\n\n# Model Assumptions and the ANOVA F-test\n\n> \"Regression analysis is the hydrogen bomb of the statistics\n> arsenal.\" - Charles Wheelan\n\nThe steps we followed in developing a simple linear model are applicable\nto the multiple regression model.\n\n**Analyzing a Multiple Regression Model**\n\n1.  Collect the *sample data* (i.e., the value of $y$, $x_1$, $x_2$,\n    ..., $x_k$) for each unit in the sample.\n2.  Hypothesize the *form* of the model (i.e., the deterministic\n    component), $E(y)$. This involves choosing which independent\n    variables to include in the model.\n3.  Use the method of least squares to *estimate* the unknown\n    *parameters*.\n4.  Specify the probability distribution of the random error component\n    $\\varepsilon$ and estimate its *variance* $\\sigma^2$.\n5.  Statistically evaluate the *utility* of the model.\n6.  Check that the *assumptions* on $\\varepsilon$ are satisfied and make\n    model modifications, if necessary.\n7.  Finally, if the model is deemed adequate, use the fitted model to\n    estimate the *mean* value of $y$ or to *predict* a particular value\n    of $y$ for given values of the independent variables, and to make\n    other inferences.\n\nWe will first assume the model is known and the assumptions hold. We\nwill then come back to step 2 and step 6 later. Let's first discuss what\nthe assumptions are.\n\n## Model Assumptions\n\nThe assumptions for the multiple regression model are the same as the\nsimple linear model. That is,\n\n-   *Linearity* - We assume the model is linear in the *parameters* but\n    not necessarily linear in the *predictor* variables. Thus, some of\n    the predictor variables may need to be transformed.\n-   *constant* *variance*\n-   *normality*\n-   *independence*\n\nThe inferences on the multiple regression model will depend on these\nassumptions holding. We will discuss how to check these later.\n\n::: {.callout-note collapse=\"false\" title=\"Assumptions and the F-test\"}\n\nThe ANOVA $F$-test is a model-utility test, but it still relies on the regression assumptions.\n\n- Linearity affects whether the fitted model is describing the right mean structure.\n- Constant variance affects the reliability of the standard error estimate.\n- Normality is especially important for small-sample inference.\n- Independence affects whether the information in the data is being counted correctly.\n\nA small p-value from the global $F$-test does not prove that the model assumptions are satisfied. It only says that, under the model assumptions, the predictors collectively explain more variation than we would expect by chance if all slope coefficients were 0.\n\n:::\n\n## A First-Order Model with Quantitative Predictors\n\nRecall that a *first-order* model means that none of the predictor\nvariables are functions of any other predictor variables.\n\nWhen the independent variables are quantitative, the $\\beta$ parameters\nin the first-order model have similar interpretations as the simple\nregression model. The difference is that when we interpret the $\\beta$\nthat multiplies one of the variables (e.g., $x_1$), we must be certain\nto hold the values of the remaining independent variables (e.g., $x_2$,\n$x_3$) *fixed*.\n\n::: {.callout-warning collapse=\"false\" title=\"Partial slopes are still conditional\"}\n\nThe ANOVA $F$-test asks whether the predictors are collectively useful. It does not change how individual slopes are interpreted.\n\nIn a first-order model with quantitative predictors, each slope is interpreted as the expected change in the response for a one-unit increase in that predictor, *holding the other predictors fixed*.\n\n:::\n\n## Testing the Utility of a Model: The Analysis of Variance $F$-Test\n\nThe objective of step 5 in a multiple regression analysis is to conduct\na test of the *utility* of the model—that is, a test to determine\nwhether the model is adequate for predicting $y$.\n\nLater, we will examine how to conduct $t$-tests on each $\\beta$\nparameter in a model, where $$\n\\begin{align*}\n    H_0: \\beta_j = 0, \\qquad j=1, 2, \\ldots, p-1\n\\end{align*}\n$$\n\nHowever, this approach is generally not a good way to determine whether\nthe *overall* model is contributing information for the prediction of\n$y$. If we were to conduct a series of $t$-tests to determine whether\nthe independent variables are contributing to the predictive\nrelationship, we would be very likely to make one or more errors in\ndeciding which terms to retain in the model and which to exclude.\n\nSuppose you fit a first-order model with 10 quantitative independent\nvariables, $x_1, x_2,..., x_{10}$, and decide to conduct $t$-tests on\nall 10 individual $\\beta$’s in the model, each at $\\alpha = .05$.\n\nFor any one test, the probability of making a type I error is 0.05: $$\n\\begin{align*}\n    P(\\text{Reject } H_0|\\beta_j=0) &= {0.05}\\\\\n    & {= 1 - 0.95}\n\\end{align*}\n$$ If we were to do ten of these tests (one for each predictor\nvariable), then the probability that at least one is a type I error is\n$$\n\\begin{align*}\n    P(\\text{Reject at least one } H_0|\\beta_1=\\beta_2=\\cdots=\\beta_{p-1}=0)\n    & = 1-[(1-\\alpha)^{10}]\\\\\n    & {= 1-(0.95)^{10}}\\\\\n    &{ = 0.401}\n\\end{align*}\n$$\n\nEven if all the $\\beta$ parameters (except $\\beta_0$) in the model are\nequal to 0, approximately 40% of the time you will incorrectly reject\nthe null hypothesis at least once and conclude that some $\\beta$\nparameter is nonzero. In other words, the overall Type I error is about\n.40, not .05.\n\nTo illustrate this inflated Type I error, let's look at the following\nexample.\n\n::: {#exm-12_1 .example title=\"Inflated Type I error from many individual tests\"}\nWe will simulate a sample of size 200 with a response variable $y$ and\nten predictor variables $x_1, x_2, \\ldots, x_{10}$. The random error\nterm $\\varepsilon$ will be a standard normal random variable.\n\nThe true model will have each coefficient $\\beta$ set to 0, with the\nexception of $\\beta_0$ which will be 20. We will conduct a $t$-test for\neach coefficient (except $\\beta_0$). Since the true coefficient is 0, we\nexpect to see p-values greater than 0.05 for each coefficient.\n\nWe will fit the model and test the coefficients 1000 times. We will\ncount the number of times at least one of the coefficients was less than\n0.05 (which would lead to a Type I error).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nset.seed(3430)\n\nn = 200\n\ntype1error = numeric(1000)\n\nfor(i in 1:1000){\n  \n  x = runif(n*10) |> matrix(ncol = 10)\n  \n  eps = rnorm(n)\n  \n  y = 20 + 0*x[,1] + 0*x[,2] + 0*x[,3] + 0*x[,4] +\n    0*x[,5] + 0*x[,6] + 0*x[,7] + 0*x[,8] + 0*x[,9] +\n    0*x[,10] + eps\n  \n  dat = tibble(y, x1 = x[,1], x2 = x[,2], x3 = x[,3],\n               x4 = x[,4], x5 = x[,5], x6 = x[,6], x7 = x[,7],\n               x8 = x[,8], x9 = x[,9], x10 = x[,10],)\n  \n  fit = lm(y~., data = dat)\n  \n  type1error[i] = any(summary(fit)$coefficients[-1,4] < 0.05)\n}\n\nmean(type1error)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.414\n```\n\n\n:::\n:::\n\n\nWe see that 41.4% of the time, we had at least one coefficient have a\np-value smaller than 0.05. This corresponds to the probability of at\nleast one Type I error of around 0.401.\n:::\n\n::: {.example title=\"Worked example: Comparing many t-tests to the global F-test\"}\n\nThe previous simulation counted how often at least one individual $t$-test was significant when all slope coefficients were truly 0. Now compare that behavior with the global $F$-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3386)\n\nnsim <- 1000\nn <- 200\nalpha <- 0.05\n\nsimulation_results <- tibble(\n  many_t_tests = logical(nsim),\n  global_f_test = logical(nsim)\n)\n\nfor (i in 1:nsim) {\n  x <- matrix(runif(n * 10), ncol = 10)\n  eps <- rnorm(n)\n  y <- 20 + eps\n\n  dat <- tibble(\n    y,\n    x1 = x[, 1],\n    x2 = x[, 2],\n    x3 = x[, 3],\n    x4 = x[, 4],\n    x5 = x[, 5],\n    x6 = x[, 6],\n    x7 = x[, 7],\n    x8 = x[, 8],\n    x9 = x[, 9],\n    x10 = x[, 10]\n  )\n\n  fit <- lm(y ~ ., data = dat)\n\n  coefficient_p_values <- summary(fit)$coefficients[-1, 4]\n  f_statistic <- summary(fit)$fstatistic\n  global_p_value <- pf(\n    f_statistic[\"value\"],\n    f_statistic[\"numdf\"],\n    f_statistic[\"dendf\"],\n    lower.tail = FALSE\n  )\n\n  simulation_results$many_t_tests[i] <- any(coefficient_p_values < alpha)\n  simulation_results$global_f_test[i] <- global_p_value < alpha\n}\n\ntype1_comparison <- simulation_results |>\n  summarize(\n    `At least one individual t-test is significant` = mean(many_t_tests),\n    `Global F-test is significant` = mean(global_f_test)\n  ) |>\n  pivot_longer(\n    cols = everything(),\n    names_to = \"method\",\n    values_to = \"type_i_error_rate\"\n  )\n\nknitr::kable(type1_comparison, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|method                                        | type_i_error_rate|\n|:---------------------------------------------|-----------------:|\n|At least one individual t-test is significant |             0.384|\n|Global F-test is significant                  |             0.050|\n\n\n:::\n:::\n\n\nWhen all slope coefficients are truly 0, the global $F$-test keeps the Type I error rate close to $\\alpha = 0.05$. The \"many separate $t$-tests\" approach has a much larger chance of producing at least one false positive.\n\n:::\n\nIn multiple regression models for which a large number of independent\nvariables are being considered, conducting a series of $t$-tests may\ncause the experimenter to include a large number of insignificant\nvariables and exclude some useful ones. If we want to test the utility\nof a multiple regression model, we will need a *global* *test* (one that\nencompasses all the $\\beta$ parameters).\n\n::: {.callout-note collapse=\"false\" title=\"What the global F-test asks\"}\n\nFor a model with predictors $x_1,\\ldots,x_{p-1}$, the global $F$-test asks:\n\n$$\nH_0:\\beta_1=\\beta_2=\\cdots=\\beta_{p-1}=0\n$$\n\nagainst\n\n$$\nH_a:\\text{at least one slope coefficient is not 0.}\n$$\n\nThe test is global because it evaluates the model's predictors as a group. If the test is significant, it does not tell us which predictor is responsible. It only tells us that the model with predictors improves on the intercept-only model.\n\n:::\n\n### Partitioning the Sum of Squares\n\nRecall when we discussed the coefficient of determination that we used\n$SS_{yy}$ to denote the variability of the response variable $y$ from\nits mean $\\bar y$ (without regard to the model involving $x$).\n\nAnother name for $SS_{yy}$ is the *sum of squares total* (SSTO). We call\nit this since it gives us a measure of total variability in $y$.\n\nIn multiple regression, SSTO is still the same as $SS_{yy}$. In matrix\nnotation this can be expressed as $$\n\\begin{align}\nSSTO & ={\\bf Y}^{\\prime}{\\bf Y}-\\left(\\frac{1}{n}\\right){\\bf Y}^{\\prime}{\\bf J}{\\bf Y}\n\\end{align}\n$$ {#eq-w4-34}\n\n#### Sum of Squares Error (SSE)\n\nAlso recall the variability of $y$ about the regression line (in simple\nlinear regression) was expressed by SSE. We can think of this as the\nvariability of $y$ remaining after explaining some of the variability\nwith the regression model.\n\nIn multiple regression, SSE is still the sum of the squared distances\nbetween the response $y$ and the fitted model $\\hat{y}$. Now, the fitted\nmodel is the fitted *hyperplane* instead of a line.\n\nThe SSE can be expressed in matrix terms as $$\n\\begin{align}\nSSE & =\\left({\\bf Y}-{\\bf X}{\\bf b}\\right)^{\\prime}\\left({\\bf Y}-{\\bf X}{\\bf b}\\right)\\\\\n& ={\\bf Y}^{\\prime}{\\bf Y}-{\\bf b}^{\\prime}{\\bf X}^{\\prime}{\\bf Y}\n\\end{align}\n$$ {#eq-w3_35}\n\n#### Sum of Squares Regression (SSR)\n\nIf SSTO is the total variability of $y$ (without regard to the\npredictor variables), and SSE is the variability of $y$ left over after\nexplaining the variability of $y$ with the model (including the\npredictor variables), we might want to know the variability of $y$\nexplained by the model.\n\nWe call the variability explained by the regression model the *sum of\nsquares regression* (SSR).\n\nWe will show below that SSR can be expressed as $$\n\\begin{align}\nSSR & =\\sum\\left(\\hat{y}_{i}-\\bar{y}\\right)^{2}\n\\end{align}\n$$ {#eq-w4_36} which can be expressed in matrix terms as $$\n\\begin{align}\nSSR & ={\\bf b}^{\\prime}{\\bf X}^{\\prime}{\\bf Y}-\\left(\\frac{1}{n}\\right){\\bf Y}^{\\prime}{\\bf J}{\\bf Y}\n\\end{align}\n$$ {#eq-w4_37}\n\n#### Components of SSTO\n\nTo see how SSTO, SSR, and SSE relate to each other, consider how SSTO is\na sum of squares of $y$ from its mean $\\bar{y}$: $$\n\\begin{align*}\ny_{i}-\\bar{y}\n\\end{align*}\n$$\n\nWe can add and subtract the fitted value $\\hat{y}_{i}$ to get $$\n\\begin{align*}\ny_{i}-\\bar{y} & =y_{i}-\\hat{y}_{i}+\\hat{y}_{i}-\\bar{y}\\\\\n& =\\left(y_{i}-\\hat{y}_{i}\\right)+\\left(\\hat{y}_{i}-\\bar{y}\\right)\n\\end{align*}\n$$\n\nSquaring both sides gives us $$\n\\begin{align*}\n\\left(y_{i}-\\bar{y}\\right)^{2} & =\\left[\\left(y_{i}-\\hat{y}_{i}\\right)+\\left(\\hat{y}_{i}-\\bar{y}\\right)\\right]^{2}\\\\\n& =\\left(y_{i}-\\hat{y}_{i}\\right)^{2}+\\left(\\hat{y}_{i}-\\bar{y}\\right)^{2}+2\\left(y_{i}-\\hat{y}_{i}\\right)\\left(\\hat{y}_{i}-\\bar{y}\\right)\n\\end{align*}\n$$\n\nSumming both sides gives us $$\n\\begin{align*}\n\\sum\\left(y_{i}-\\bar{y}\\right)^{2} & =\\sum\\left(y_{i}-\\hat{y}_{i}\\right)^{2}+\\sum\\left(\\hat{y}_{i}-\\bar{y}\\right)^{2}+2\\sum\\left(y_{i}-\\hat{y}_{i}\\right)\\left(\\hat{y}_{i}-\\bar{y}\\right)\\\\\n& =\\sum\\left(y_{i}-\\hat{y}_{i}\\right)^{2}+\\sum\\left(\\hat{y}_{i}-\\bar{y}\\right)^{2}+2\\sum\\hat{y}_{i}e_{i}-2\\bar{y}\\sum e_{i}\n\\end{align*}\n$$\n\nNote that $\\sum\\hat{y}_{i}e_{i}=0$ \n<!-- from @eq-w1_22  -->\nand $\\sum e_{i}=0$.\n<!-- from @eq-w1_20. -->\n\nTherefore, we have $$\n\\begin{align*}\n\\sum\\left(y_{i}-\\bar{y}\\right)^{2} & =\\sum\\left(\\hat{y}_{i}-\\bar{y}\\right)^{2}+\\sum\\left(y_{i}-\\hat{y}_{i}\\right)^{2}\\\\\nSSTO & =SSR+SSE \n\\end{align*}\n$$ {#eq-4_38}\n\nWe call this the *decomposition* of SSTO.\n\n::: {.example title=\"Worked example: Decomposing SSTO for the `trees` model\"}\n\nFor the `trees` model with `Volume` predicted by `Girth` and `Height`, the total variation in `Volume` can be split into variation explained by the model and variation left in the residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrees_anova_fit <- lm(Volume ~ Girth + Height, data = trees)\n\ntrees_y <- trees$Volume\ntrees_yhat <- fitted(trees_anova_fit)\ntrees_resid <- resid(trees_anova_fit)\n\nssto_trees <- sum((trees_y - mean(trees_y))^2)\nssr_trees <- sum((trees_yhat - mean(trees_y))^2)\nsse_trees <- sum(trees_resid^2)\n\nss_decomposition <- tibble(\n  source = c(\"Total variation\", \"Explained by regression\", \"Unexplained error\"),\n  symbol = c(\"SSTO\", \"SSR\", \"SSE\"),\n  value = c(ssto_trees, ssr_trees, sse_trees)\n)\n\nknitr::kable(ss_decomposition, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|source                  |symbol |     value|\n|:-----------------------|:------|---------:|\n|Total variation         |SSTO   | 8106.0839|\n|Explained by regression |SSR    | 7684.1625|\n|Unexplained error       |SSE    |  421.9214|\n\n\n:::\n:::\n\n\nThe decomposition says\n\n$$\nSSTO = SSR + SSE.\n$$\n\nFor this model, 8106.0839 is approximately equal to 7684.1625 + 421.9214.\n\n:::\n\n::: {.example title=\"Worked example: Visualizing `SSTO = SSR + SSE`\"}\n\nThe decomposition can also be shown visually. The total bar shows SSTO. The second bar breaks that same total into SSR and SSE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nss_visual <- tibble(\n  bar = c(\"SSTO\", \"SSR + SSE\", \"SSR + SSE\"),\n  component = c(\"SSTO\", \"SSR\", \"SSE\"),\n  value = c(ssto_trees, ssr_trees, sse_trees)\n)\n\nggplot(ss_visual, aes(x = bar, y = value, fill = component)) +\n  geom_col(width = 0.6, color = \"white\") +\n  scale_fill_manual(\n    values = c(\n      \"SSTO\" = \"gray70\",\n      \"SSR\" = \"steelblue\",\n      \"SSE\" = \"orange\"\n    )\n  ) +\n  labs(\n    x = NULL,\n    y = \"Sum of squares\",\n    fill = \"Component\",\n    title = \"Total variation decomposes into explained and unexplained variation\",\n    subtitle = \"For least squares regression with an intercept: SSTO = SSR + SSE\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12_ANOVA_files/figure-html/unnamed-chunk-4-1.png){width=576}\n:::\n:::\n\n\nThe visual point is simple: the total variation in the response can be split into the part explained by the fitted model and the part left in the residuals.\n\n:::\n\n#### Degrees of Freedom\n\nThe degrees of freedom can be decomposed as well. Note that the degrees\nof freedom for SSTO is $$\n\\begin{align*}\ndf_{SSTO} & =n-1\n\\end{align*}\n$$ since the mean of $y$ is needed to be estimated with $\\bar{y}$.\n\nThe degrees of freedom for SSE is $$\n\\begin{align*}\ndf_{SSE} & =n-p\n\\end{align*}\n$$ since the $p$ coefficients $\\beta_{0},\\ldots,\\beta_{p-1}$ need to be\nestimated with $\\hat{\\beta}_{0},\\ldots,\\hat{\\beta}_{p-1}.$\n\nFor SSR, the degrees of freedom is $$\n\\begin{align*}\ndf_{SSR} & =p-1\n\\end{align*}\n$$ since there are $p$ estimated coefficients\n$\\hat{\\beta}_{0},\\ldots,\\hat{\\beta}_{p-1}$ but need to estimate the mean\nof $y$ with $\\bar{y}$.\n\nDecomposing the degrees of freedom give us $$\n\\begin{align}\nn-1 & =p-1+n-p\\\\\ndf_{SSTO} & =df_{SSR}+df_{SSE}\n\\end{align}\n$$ {#eq-w4_29}\n\n### The Analysis of Variance (ANOVA) Table\n\nThe sums of squares and degrees of freedom are commonly displayed in an\nanalysis of variance (ANOVA) table:\n\n|   Source   |     df      |   SS   | MS  |  F  | p-value |\n|:----------:|:-----------:|:------:|:---:|:---:|:-------:|\n| Regression | $df_{SSR}$  | $SSR$  |     |     |         |\n|   Error    | $df_{SSE}$  | $SSE$  |     |     |         |\n|   Total    | $df_{SSTO}$ | $SSTO$ |     |     |         |\n\n\n\n#### Mean Squares\n\nRecall that if we divide SSE by its degrees of freedom, we obtain the\nmean square error: \n$$\n\\begin{align}\nMSE & =\\frac{SSE}{n-p}\n\\end{align}\n$${#eq-w4_40}\n\n\nLikewise, if we divide SSR by its degrees of freedom, we obtain the\n*mean square regression*: \n$$\n\\begin{align}\nMSR & =\\frac{SSR}{p-1}\n\\end{align} \n$${#eq-w4_41}\n\nThese values are also included in the ANOVA table:\n\n|   Source   |     df      |   SS   | MS  |  F  | p-value |\n|:----------:|:-----------:|:------:|:---:|:---:|:-------:|\n| Regression | $df_{SSR}$  | $SSR$  |  $MSR$   |     |         |\n|   Error    | $df_{SSE}$  | $SSE$  | $MSE$    |     |         |\n|   Total    | $df_{SSTO}$ | $SSTO$ |     |     |         |\n\n\nNote that although the sum of squares and degrees of freedom decompose,\nthe mean squares do not. That is \n$$\n\\begin{align*}\n\\frac{SSTO}{n-1} & \\ne MSR+MSE\n\\end{align*}\n$$\n\nIn fact, the mean square for the total ($SSTO/n-1$) does\nnot usually show up on the ANOVA table.\n\n### The ANOVA F-test\n\nWe tested the slope in simple regression to see if there is a\nsignificant linear relationship between $X$ and $Y$.\n\nIn multiple regression, we will want to see if there is any significant\nlinear relationship between any of the $x$s and $y$. Thus, we want to\ntest the hypotheses \n$$\n\\begin{align*}\nH_{0}: & \\beta_{1}=\\beta_{2}=\\cdots=\\beta_{p-1}=0\\\\\nH_{a}: & \\text{at least one } \\beta \\text{ is not equal to zero}\n\\end{align*}\n$$\n\nTo construct a test statistic, we first note that \n$$\n\\begin{align*}\n\\frac{SSE}{\\sigma^{2}} & \\sim\\chi^{2}\\left(n-p\\right)\n\\end{align*}\n$$\nAlso, if $H_{0}$ is true, then \n$$\n\\begin{align*}\n\\frac{SSR}{\\sigma^{2}} & \\sim\\chi^{2}\\left(p-1\\right)\n\\end{align*}\n$$\n\nThe ratio of two independent chi-square random variables divided by\ntheir degrees of freedom gives a statistic that follows an F-distribution.\n\nSince $SSE/\\sigma^{2}$ and $SSR/\\sigma^{2}$ are independent (proof not\ngiven here), then under $H_{0}$, we can construct a test statistic as\n$$\n\\begin{align}\nF^{*} & =\\left(\\frac{\\frac{SSR}{\\sigma^{2}}}{p-1}\\right)\\div\\left(\\frac{\\frac{SSE}{\\sigma^{2}}}{n-p}\\right)\\\\\n& =\\left(\\frac{SSR}{p-1}\\right)\\div\\left(\\frac{SSE}{n-p}\\right)\\\\\n& =\\frac{MSR}{MSE}\n\\end{align}\n$${#eq-w4_42}\n\n\nLarge values of $F^{*}$ indicate evidence for $H_{a}$.\n\n\n\n\nThe test statistic and p-value are the last two components of the ANOVA\ntable:\n\n|   Source   |     df      |   SS   | MS  |  F  | p-value |\n|:----------:|:-----------:|:------:|:---:|:---:|:-------:|\n| Regression | $df_{SSR}$  | $SSR$  |  $MSR$   | $F^{*}$    |  $P\\left(F\\ge F^{*}\\right)$       |\n|   Error    | $df_{SSE}$  | $SSE$  | $MSE$    |     |         |\n|   Total    | $df_{SSTO}$ | $SSTO$ |     |     |         |\n\n::: {.example title=\"Worked example: Building the ANOVA table by hand\"}\n\nUsing the sums of squares from the `trees` model, we can construct the ANOVA table directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_trees_anova <- nobs(trees_anova_fit)\np_trees_anova <- length(coef(trees_anova_fit))\n\ndf_regression <- p_trees_anova - 1\ndf_error <- n_trees_anova - p_trees_anova\ndf_total <- n_trees_anova - 1\n\nmsr_trees <- ssr_trees / df_regression\nmse_trees <- sse_trees / df_error\nf_trees <- msr_trees / mse_trees\np_value_trees <- pf(f_trees, df_regression, df_error, lower.tail = FALSE)\n\nmanual_anova_table <- tibble(\n  source = c(\"Regression\", \"Error\", \"Total\"),\n  df = c(df_regression, df_error, df_total),\n  SS = c(ssr_trees, sse_trees, ssto_trees),\n  MS = c(msr_trees, mse_trees, NA_real_),\n  F = c(f_trees, NA_real_, NA_real_),\n  p_value = c(p_value_trees, NA_real_, NA_real_)\n)\n\nknitr::kable(manual_anova_table, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|source     | df|        SS|        MS|        F| p_value|\n|:----------|--:|---------:|---------:|--------:|-------:|\n|Regression |  2| 7684.1625| 3842.0813| 254.9723|       0|\n|Error      | 28|  421.9214|   15.0686|       NA|      NA|\n|Total      | 30| 8106.0839|        NA|       NA|      NA|\n\n\n:::\n:::\n\n\nThe global $F$ statistic compares explained variation per regression degree of freedom to unexplained variation per error degree of freedom.\n\n$$\nF^*=\\frac{MSR}{MSE}.\n$$\n\nLarge values of $F^*$ occur when the regression model explains a lot of variation relative to the residual noise.\n\n:::\n\n::: {.callout-warning collapse=\"false\" title=\"What a significant F-test does not tell you\"}\n\nA significant global $F$-test tells us that at least one slope coefficient is not 0. It does not tell us:\n\n- which predictor or predictors are useful,\n- whether the model assumptions are satisfied,\n- whether the relationship is causal,\n- whether the model predicts well on new data.\n\nThose questions require follow-up coefficient tests, diagnostic plots, subject-area reasoning, and validation.\n\n:::\n\n\n\n\n\n::: {#exm-12_2 .example title=\"The global F-test for the `trees` model\"}\nWe will fit a multiple regression model to the `trees` dataset. The Tidymodels framework will be used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n\ndata(trees)\n\n# Prepare data\ndat_recipe <- recipe(Volume ~ Girth + Height, data = trees)\n\n# Set up model\nlm_model <- linear_reg() |>\n  set_engine(\"lm\")\n\n# Set up the workflow\nlm_workflow <- workflow() |>\n  add_recipe(dat_recipe) |> \n  add_model(lm_model)\n\n# Fit the model\nlm_fit <- lm_workflow |>\n  fit(data = trees)\n\n# Get the coefficients\ntrees_tidymodels_coefficients <- lm_fit |>\n  tidy()\n\nknitr::kable(trees_tidymodels_coefficients, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) | -57.9877|    8.6382|   -6.7129|  0.0000|\n|Girth       |   4.7082|    0.2643|   17.8161|  0.0000|\n|Height      |   0.3393|    0.1302|    2.6066|  0.0145|\n\n\n:::\n:::\n\n\nThe fitted model is\n$$\n\\hat{y} = -57.988 + 4.708x_1 + 0.339x_2\n$$\n\nwhere $x_1$ is `Girth` and $x_2$ is `Height`.\n\nFor every one-inch increase in Girth, the average Volume increases by 4.708 cubic feet, keeping Height fixed.\n\nFor every one-foot increase in Height, the average Volume increases by 0.339 cubic feet, keeping Girth fixed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the global F-test p-value\ntrees_global_test <- lm_fit |>\n  glance()\n\ntrees_global_test |>\n  select(r.squared, statistic, p.value, df, df.residual) |>\n  knitr::kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n| r.squared| statistic| p.value| df| df.residual|\n|---------:|---------:|-------:|--:|-----------:|\n|     0.948|  254.9723|       0|  2|          28|\n\n\n:::\n\n```{.r .cell-code}\n# Get the ANOVA table\n# Note that SSR is split into individual predictors\ntrees_sequential_anova <- lm_fit |>\n  extract_fit_engine() |>\n  anova()\n\nknitr::kable(trees_sequential_anova, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|          | Df|    Sum Sq|   Mean Sq|  F value| Pr(>F)|\n|:---------|--:|---------:|---------:|--------:|------:|\n|Girth     |  1| 7581.7813| 7581.7813| 503.1503| 0.0000|\n|Height    |  1|  102.3812|  102.3812|   6.7943| 0.0145|\n|Residuals | 28|  421.9214|   15.0686|       NA|     NA|\n\n\n:::\n:::\n\n\n\nSince the global F-test p-value is very small, there is sufficient evidence to conclude that at least one slope coefficient is not 0.\n\nThe `anova()` table shown by R splits the regression sum of squares across predictors in the order they enter the model. The global F-test reported by `glance()` tests the predictors collectively.\n\n:::\n\n::: {.callout-note collapse=\"false\" title=\"Global F-test versus sequential ANOVA table\"}\n\nThe global $F$-test and the `anova()` table from `anova(lm_object)` answer related but different questions.\n\n| Output | Main question | Important detail |\n|---|---|---|\n| `glance()` global F-test | Does the full model improve on the intercept-only model? | Tests all slopes together. |\n| `anova(lm_object)` sequential ANOVA table | How much sum of squares is added by each predictor as it enters the model? | The order of predictors matters. |\n\nFor example, compare these two model formulas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_girth_first <- anova(lm(Volume ~ Girth + Height, data = trees))\nanova_height_first <- anova(lm(Volume ~ Height + Girth, data = trees))\n\nsequential_anova_compare <- bind_rows(\n  as_tibble(anova_girth_first, rownames = \"term\") |>\n    mutate(order = \"Girth entered first\"),\n  as_tibble(anova_height_first, rownames = \"term\") |>\n    mutate(order = \"Height entered first\")\n) |>\n  select(order, term, Df, `Sum Sq`, `Mean Sq`, `F value`, `Pr(>F)`)\n\nknitr::kable(sequential_anova_compare, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|order                |term      | Df|    Sum Sq|   Mean Sq|  F value| Pr(>F)|\n|:--------------------|:---------|--:|---------:|---------:|--------:|------:|\n|Girth entered first  |Girth     |  1| 7581.7813| 7581.7813| 503.1503| 0.0000|\n|Girth entered first  |Height    |  1|  102.3812|  102.3812|   6.7943| 0.0145|\n|Girth entered first  |Residuals | 28|  421.9214|   15.0686|       NA|     NA|\n|Height entered first |Height    |  1| 2901.1889| 2901.1889| 192.5318| 0.0000|\n|Height entered first |Girth     |  1| 4782.9736| 4782.9736| 317.4129| 0.0000|\n|Height entered first |Residuals | 28|  421.9214|   15.0686|       NA|     NA|\n\n\n:::\n:::\n\n\nThe total model fit is the same either way, but the sequential ANOVA table allocates explained variation according to the order in which predictors enter the formula. This is why the global F-test is the cleaner answer to the question, \"Is the predictor set useful as a group?\"\n\n:::\n\n### A Bridge to Adjusted $R^2$\n\nThe ANOVA decomposition also connects directly to $R^2$.\n\nRecall that\n\n$$\nR^2=\\frac{SSR}{SSTO}=1-\\frac{SSE}{SSTO}.\n$$\n\nThis measures the proportion of sample variation in the response explained by the fitted model. However, ordinary $R^2$ never decreases when predictors are added, even if the new predictors are not useful. Adjusted $R^2$ adds a degrees-of-freedom penalty:\n\n$$\nR^2_{adj}=1-\\frac{SSE/(n-p)}{SSTO/(n-1)}.\n$$\n\nNotice that this formula uses the same ingredients as the ANOVA table: $SSE$, $SSTO$, $n-p$, and $n-1$.\n\n::: {.example title=\"Worked example: Connecting ANOVA to adjusted `R^2`\"}\n\nFor the `trees` model, we can calculate $R^2$ and adjusted $R^2$ directly from the sums of squares.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_squared_trees <- ssr_trees / ssto_trees\nadjusted_r_squared_trees <- 1 - (sse_trees / df_error) / (ssto_trees / df_total)\n\nrsq_compare <- tibble(\n  quantity = c(\"R-squared from sums of squares\", \"Adjusted R-squared from ANOVA pieces\", \"R-squared from lm summary\", \"Adjusted R-squared from lm summary\"),\n  value = c(\n    r_squared_trees,\n    adjusted_r_squared_trees,\n    summary(trees_anova_fit)$r.squared,\n    summary(trees_anova_fit)$adj.r.squared\n  )\n)\n\nknitr::kable(rsq_compare, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|quantity                             |  value|\n|:------------------------------------|------:|\n|R-squared from sums of squares       | 0.9480|\n|Adjusted R-squared from ANOVA pieces | 0.9442|\n|R-squared from lm summary            | 0.9480|\n|Adjusted R-squared from lm summary   | 0.9442|\n\n\n:::\n:::\n\n\nAdjusted $R^2$ is useful because it rewards explained variation but penalizes the model for using more predictors. It is not a hypothesis test, but it is closely connected to the same variation-decomposition ideas behind ANOVA.\n\n:::\n\n## Recap\n\nThis chapter introduced the ANOVA approach to testing the overall utility of a multiple regression model.\n\n| Idea | Meaning |\n|---|---|\n| **Global F-test** | Tests whether the predictors are collectively useful for explaining variation in the response. |\n| **Null hypothesis** | $H_0:\\beta_1=\\beta_2=\\cdots=\\beta_{p-1}=0$. |\n| **Alternative hypothesis** | At least one slope coefficient is not 0. |\n| **SSTO** | Total variation in the response: variation around $\\bar y$. |\n| **SSR** | Regression variation: variation explained by the fitted model. |\n| **SSE** | Error variation: variation left in the residuals. |\n| **Sum-of-squares decomposition** | $SSTO=SSR+SSE$. |\n| **Degrees-of-freedom decomposition** | $n-1=(p-1)+(n-p)$. |\n| **MSR** | $MSR=SSR/(p-1)$, explained variation per regression degree of freedom. |\n| **MSE** | $MSE=SSE/(n-p)$, unexplained variation per error degree of freedom. |\n| **F statistic** | $F^*=MSR/MSE$. |\n| **Large F statistic** | Evidence against $H_0$ and in favor of at least one useful predictor. |\n| **Sequential ANOVA** | Splits SSR across predictors in formula order; useful, but order-dependent. |\n| **$R^2$** | $R^2=SSR/SSTO=1-SSE/SSTO$, the proportion of sample response variation explained by the model. |\n| **Adjusted $R^2$** | $R^2_{adj}=1-\\dfrac{SSE/(n-p)}{SSTO/(n-1)}$, an $R^2$-like measure with a degrees-of-freedom penalty. |\n| **Important limitation** | A significant global F-test does not identify which predictor is useful or prove that assumptions hold. |\n\n## Check your understanding\n\n::: {.callout-note collapse=\"false\" title=\"Problems\"}\n\n1. What is the purpose of the global ANOVA $F$-test in multiple regression?\n\n2. What null hypothesis is tested by the global $F$-test?\n\n3. Why is conducting many individual $t$-tests not the same as conducting one global model test?\n\n4. What does SSTO measure?\n\n5. What does SSR measure?\n\n6. What does SSE measure?\n\n7. How are SSTO, SSR, and SSE related?\n\n8. What are the degrees of freedom for regression, error, and total in a model with $p$ parameters and $n$ observations?\n\n9. Why do we divide sums of squares by degrees of freedom to form mean squares?\n\n10. What does the statistic $F^*=MSR/MSE$ compare?\n\n11. What does a large value of $F^*$ suggest?\n\n12. If the global $F$-test is significant, does that tell us which predictor is useful? Explain.\n\n13. Does a significant global $F$-test prove that the regression assumptions are satisfied?\n\n14. Why is the global $F$-test best viewed as a test of collective usefulness?\n\n15. Why can the sequential ANOVA table from `anova(lm_object)` change when the order of predictors changes?\n\n16. How is $R^2$ related to the ANOVA sums of squares?\n\n17. Why does adjusted $R^2$ include a degrees-of-freedom penalty?\n\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Solutions\"}\n\n1. **To test overall model utility.** The global $F$-test asks whether the predictors, as a group, explain a meaningful amount of variation in the response.\n\n2. **All slopes are 0.** The null hypothesis is $H_0:\\beta_1=\\beta_2=\\cdots=\\beta_{p-1}=0$.\n\n3. **Multiple tests inflate error risk.** Many individual $t$-tests create many chances for a Type I error. The global $F$-test evaluates the predictors together in one test.\n\n4. **Total response variation.** SSTO measures the total variation of the observed responses around their mean.\n\n5. **Explained variation.** SSR measures the part of the response variation explained by the fitted regression model.\n\n6. **Unexplained variation.** SSE measures the residual variation left after fitting the model.\n\n7. **They decompose total variation.** In least squares regression with an intercept, $SSTO=SSR+SSE$.\n\n8. **Regression, error, total.** The regression degrees of freedom are $p-1$, the error degrees of freedom are $n-p$, and the total degrees of freedom are $n-1$.\n\n9. **To put variation on a per-degree-of-freedom scale.** Mean squares compare sums of squares after accounting for their degrees of freedom.\n\n10. **Explained variation relative to residual variation.** The $F$ statistic compares MSR to MSE.\n\n11. **Evidence against the null.** A large $F^*$ suggests that the model explains more variation than expected if all slope coefficients were 0.\n\n12. **No.** A significant global $F$-test says at least one slope is not 0, but it does not identify which one.\n\n13. **No.** The test assumes the regression assumptions are reasonable; it does not verify them.\n\n14. **It evaluates the predictor set.** The test compares a model with all predictors to an intercept-only model, so it addresses whether the predictors are collectively useful.\n\n15. **Sequential means order-dependent.** The table gives each predictor credit for the extra sum of squares it explains after earlier predictors have already entered the model. If the order changes, that allocation can change.\n\n16. **It is explained variation divided by total variation.** $R^2=SSR/SSTO=1-SSE/SSTO$.\n\n17. **To discourage adding useless predictors.** Ordinary $R^2$ cannot decrease when predictors are added. Adjusted $R^2$ compares MSE to the total mean square, so it accounts for both unexplained variation and the number of parameters estimated.\n\n:::\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "12_ANOVA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}