{
  "hash": "4e3e9af080231355b7e487e1370c3916",
  "result": {
    "engine": "knitr",
    "markdown": "# An Intro to Multiple Regression {#sec-multiple}\n\n> \"Statisticians, like artists, have the bad habit of falling in love with their models.\" - George Box \n\n\n\n## Types of Models\n\nWhen we discuss the simple linear regression model\n$$\n\\begin{align*}\n    y = \\beta_0 + \\beta_1 x +\\varepsilon\n\\end{align*}\n$$\nwe stated previously that it is \"simple\" because there is only one predictor variable.\n\n\nThe model is \"*linear in the parameters*\" because every parameter is only to the first power and is not multiplied or divided by another parameter.\n\nThe model is also \"*linear in the predictor variable*\" because $x$ appears only with an exponent of one (instead of $x^2$, $x^{1/2}$, etc.). \n\nA \"linear model\" means it is linear in the parameters (not necessarily linear in the predictor variables). A model that is linear in both the parameters and the predictor variables is called a *first-order model*.\n\n::: {.example title=\"Example 10.1: Linear in parameters versus linear in predictors\"}\n\nThe word \"linear\" can be sneaky because it can refer to two different ideas.\n\n| Model | Linear in the parameters? | Linear in the predictor variables? | First-order model? |\n|---|---|---|---|\n| $y=\\beta_0+\\beta_1x+\\varepsilon$ | Yes | Yes | Yes |\n| $y=\\beta_0+\\beta_1x+\\beta_2x^2+\\varepsilon$ | Yes | No | No |\n| $y=\\beta_0+\\beta_1\\log(x)+\\varepsilon$ | Yes | No | No |\n| $y=\\beta_0+\\beta_1x_1+\\beta_2x_2+\\beta_3x_1x_2+\\varepsilon$ | Yes | No, because of the product term | No |\n| $y=\\beta_0+\\beta_1^2x+\\varepsilon$ | No | Yes | No |\n\nRegression courses usually use the phrase \"linear regression\" to mean linear in the parameters. That means transformations of predictors, polynomial terms, and interaction terms can still be part of a linear regression model.\n\n:::\n\n\n## Multiple Predictor Variables\n\nOften when modeling some response variable $y$, one predictor variable may not be adequate. Thus, multiple predictor variables can be used to model $y$.\n\n\n\nAs in simple linear regression, we will assume models that are *linear* in the parameters. \n\n\n\n\nWe will present the multiple linear regression model that is linear in the parameters but not necessarily linear in the predictor variables. This type of model is called the *general* linear regression model. \n\n\n### The Multiple Regression Model\n\n\nThe general model is\n$$\n\\begin{align}\ny_{i}= & \\beta_{0}+\\beta_{1}x_{i1}+\\beta_{2}x_{i2}+\\cdots+\\beta_{p-1}x_{i,p-1}+\\varepsilon_{i}\\\\\n= & \\beta_{0}+\\sum_{k=1}^{p-1}\\beta_{k}x_{ik}+\\varepsilon_{i}\\\\\n& \\varepsilon\\overset{iid}{\\sim}N\\left(0,\\sigma^{2}\\right)\n\\end{align}\n$${#eq-w4_1}\nwhere\n$$\n\\begin{align*}\n& \\beta_{0},\\beta_{1},\\ldots,\\beta_{p-1}\\text{ are parameters}\\\\\n& x_{i1},\\ldots,x_{i,p-1}\\text{ are known constants}\\\\\n& i=1,\\ldots,n\n\\end{align*}\n$$\n\n::: {.example title=\"Example 10.2: Interpreting a partial slope\"}\n\nSuppose we model a student's exam score using hours studied and number of missed classes:\n\n$$\nscore_i=\\beta_0+\\beta_1hours_i+\\beta_2missed_i+\\varepsilon_i.\n$$\n\nThe coefficient $\\beta_1$ is the expected change in exam score for a one-unit increase in hours studied, *holding the number of missed classes constant*.\n\nThe phrase \"holding the other predictor constant\" is the key new interpretation in multiple regression. A multiple-regression slope is a *partial* effect, not just the raw relationship between one predictor and the response.\n\n:::\n\n\nThe predictor variable $x_{k}$ can be raised to some power or transformed\nin some other way. Also, the predictor variable can be the product\nof two variables. When this is the case, we say the term is an *interaction*\nterm. We will discuss these more later.\n\n\n\n\n### Assumptions About the Predictor Variables\n\nIn multiple regression, we are interested in how the predictor variables relate to the response variable. In particular, we want to know:\n\n1. How *important* are the different predictor variables in modeling $y$?\n2. What is the *effect* of a given predictor variable on predicting $y$? \n3. Are any of the predictor variables *unnecessary* in modeling $y$ and therefore be dropped from the model?\n4. Are there any predictor variables not *included* in the model that should be included? \n\n\n\nThese questions are relatively simple to answer if the predictor variables are *uncorrelated* among themselves.\n\n\n\n\nUnfortunately, in real-world applications, especially for observational studies, the predictor variables tend to be correlated among themselves. When this is the case, we say that *multicollinearity* exists.\n\n::: {.example title=\"Example 10.3: Why correlated predictors complicate interpretation\"}\n\nSuppose we model house price using square footage and number of bedrooms.\n\nLarger houses often have more bedrooms, so these two predictors are usually correlated. If both predictors are in the model, the slope for square footage describes the relationship between square footage and price *among houses with the same number of bedrooms*. The slope for bedrooms describes the relationship between bedrooms and price *among houses with the same square footage*.\n\nThose are useful questions, but they are more subtle than the simple-regression question \"How does price change as square footage changes?\" Multicollinearity makes it harder to separate the unique contribution of each predictor.\n\n:::\n\n\n\n\nJust due to chance, there will always be some correlation among the predictor variables. In general, we will assume the correlation among the predictor variables is low. If the correlation is high, then this may present problems in the analyses. As we discuss the inferences and assumptions going further, we will discuss the problem of multicollinearity in more detail.  \n\n\n## Estimating the Multiple Regression Model\n\n\n\n### Minimizing the SSE\n\nAs we did in the simple linear regression case, we want to fit model @eq-w4_1 to the observed data.\n\n\n\nThe fitted line in the multiple regression case is \n$$\n\\begin{align}\n\\hat{y}_i = b_0 + b_1 x_{i1} + b_2 x_{i2}+\\cdots +b_{p-1}x_{i,p-1}\n\\end{align}\n$${#eq-w4_2}\nThe estimates $b_0,b_1,\\ldots,b_{p-1}$ are found by minimizing the *squared* *distances* between the observed values $y_i$ and the fitted values $\\hat{y}_i$. The sum of the squared distances is now\n$$\n\\begin{align}\nQ=\\sum \\left(y_i-\\left(b_0 + b_1 x_{i1} + b_2 x_{i2}+\\cdots +b_{p-1}x_{i,p-1}\\right)\\right)^2\n\\end{align}\n$${#eq-w4_3}\nin the multiple regression case. \n\n\n\n\n\nNote that model @eq-w4_1 is no longer a line. It is a *plane* when $p=3$ and a *hyperplane* when $p>3$. \n\n\n\n\n### Case with Two Predictor Variables\n\nWhen there are two predictor variables ($p=3$), we will take three partial derivatives of @eq-w4_3 with respect to $b_0$, $b_1$, and $b_2$. This leads us to \n$$\n\\begin{align}\n\\frac{\\partial Q}{\\partial b_{0}} & =-2\\sum\\left(y_{i}-b_{0}-b_{1}x_{i1}-b_{2}x_{i2}\\right)\\\\\n\\frac{\\partial Q}{\\partial b_{1}} & =-2\\sum x_{i1}\\left(y_{i}-b_{0}-b_{1}x_{i1}-b_{2}x_{i2}\\right)\\\\\n\\frac{\\partial Q}{\\partial b_{2}} & =-2\\sum x_{i2}\\left(y_{i}-b_{0}-b_{1}x_{i1}-b_{2}x_{i2}\\right)\n\\end{align}\n$${#eq-w4_4}\n\n\n\n\n### The Normal Equations\n\nSetting the partial derivative equal to zero and rearranging the terms lead us to the *normal* equations\n$$\n\\begin{align}\n\\sum y_{i} & =nb_{0}+b_{1}\\sum x_{i1}+b_{2}\\sum x_{i2}\\\\\n\\sum x_{i1}y_{i} & =b_{0}\\sum x_{i1}+b_{1}\\sum x_{i1}^{2}+b_{2}\\sum x_{i1}x_{i2}\\\\\n\\sum x_{i2}y_{i} & =b_{0}\\sum x_{i2}+b_{1}\\sum x_{i1}x_{i2}+b_{2}\\sum x_{i2}^{2}\n\\end{align}\n$${#eq-w4_5}\n\n\n\n### The Least Squares Estimators\n\nSolving the normal equations for $b_0$, $b_1$, and $b_2$ gives us the *least* *squares* estimators\n$$\n\\begin{align}\nb_{1} & =\\frac{\\left(\\sum x_{i2}^{2}\\right)\\left(\\sum x_{i1}y_{i}\\right)-\\left(\\sum x_{i1}x_{i2}\\right)\\left(\\sum x_{i2}y_{i}\\right)}{\\left(\\sum x_{i1}^{2}\\right)\\left(\\sum x_{i2}^{2}\\right)-\\left(\\sum x_{i1}x_{i2}\\right)^{2}}\\\\\nb_{2} & =\\frac{\\left(\\sum x_{i1}^{2}\\right)\\left(\\sum x_{i2}y_{i}\\right)-\\left(\\sum x_{i1}x_{i2}\\right)\\left(\\sum x_{i1}y_{i}\\right)}{\\left(\\sum x_{i1}^{2}\\right)\\left(\\sum x_{i2}^{2}\\right)-\\left(\\sum x_{i1}x_{i2}\\right)^{2}}\\\\\nb_{0} & =\\bar{Y}-b_{1}\\bar{X}_{1}-b_{2}\\bar{X}_{2}\n\\end{align}\n$${#eq-w4_6}\n\nWe see that the expression for the least squares estimators become cumbersome even for $p=3$. As more variables are added to the model, the equations become even more cumbersome.\n\n::: {.example title=\"Example 10.4: Fitting a multiple regression model in R\"}\n\nThe `trees` dataset contains measurements on the girth, height, and volume of 31 black cherry trees. A natural multiple regression model is\n\n$$\nVolume_i=\\beta_0+\\beta_1Girth_i+\\beta_2Height_i+\\varepsilon_i.\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrees_fit <- lm(Volume ~ Girth + Height, data = trees)\n\ntrees_coefs <- broom::tidy(trees_fit)\n\nknitr::kable(trees_coefs, digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) | -57.9877|    8.6382|   -6.7129|  0.0000|\n|Girth       |   4.7082|    0.2643|   17.8161|  0.0000|\n|Height      |   0.3393|    0.1302|    2.6066|  0.0145|\n\n\n:::\n:::\n\n\nThe estimated slope for `Girth` is 4.7082. Interpreted in the multiple-regression model, this means that for trees with the same height, a one-unit increase in girth is associated with an average increase of about 4.7082 cubic feet in predicted volume.\n\nThe estimated slope for `Height` is 0.3393. This means that for trees with the same girth, a one-unit increase in height is associated with an average increase of about 0.3393 cubic feet in predicted volume.\n\nThe important phrase in both interpretations is \"with the other predictor held constant.\"\n\n:::\n\n::: {.callout-warning collapse=\"false\" title=\"Common interpretation mistake: partial slopes are conditional\"}\n\nIn simple linear regression, it is natural to describe the slope as the relationship between $x$ and $y$.\n\nIn multiple regression, that wording is incomplete. A slope describes the relationship between one predictor and the response *after accounting for the other predictors in the model*.\n\nFor the `trees` model, the `Girth` slope should not be interpreted as the overall relationship between girth and volume. It is the expected change in volume for a one-unit increase in girth *among trees with the same height*.\n\nThat \"holding the other predictors constant\" phrase is not decorative. It is doing the heavy interpretive lifting.\n\n:::\n\n::: {.example title=\"Example 10.5: Visualizing a regression plane\"}\n\nWith one predictor, the fitted values form a line. With two predictors, the fitted values form a plane.\n\nThe model\n\n$$\n\\widehat{Volume}=b_0+b_1Girth+b_2Height\n$$\n\nproduces one predicted volume for each combination of girth and height.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngirth_grid <- seq(min(trees$Girth), max(trees$Girth), length.out = 25)\nheight_grid <- seq(min(trees$Height), max(trees$Height), length.out = 25)\n\nplane_grid <- expand.grid(\n  Girth = girth_grid,\n  Height = height_grid\n)\n\nplane_grid$predicted_volume <- predict(trees_fit, newdata = plane_grid)\n\nvolume_surface <- matrix(\n  plane_grid$predicted_volume,\n  nrow = length(girth_grid),\n  ncol = length(height_grid)\n)\n\nregression_plane <- persp(\n  x = girth_grid,\n  y = height_grid,\n  z = volume_surface,\n  theta = 35,\n  phi = 25,\n  expand = 0.6,\n  col = \"lightblue\",\n  border = \"gray80\",\n  ticktype = \"detailed\",\n  xlab = \"Girth\",\n  ylab = \"Height\",\n  zlab = \"Predicted volume\"\n)\n\npoints(\n  trans3d(\n    x = trees$Girth,\n    y = trees$Height,\n    z = trees$Volume,\n    pmat = regression_plane\n  ),\n  pch = 19,\n  col = \"darkgreen\"\n)\n```\n\n::: {.cell-output-display}\n![](10_Intro_Multiple_files/figure-html/unnamed-chunk-2-1.png){width=576}\n:::\n:::\n\n\nThe blue surface represents the fitted regression plane. The green points represent the observed trees. Each residual is the vertical distance between an observed point and the fitted plane.\n\n:::\n\n::: {.callout-note collapse=\"false\" title=\"From line to plane to hyperplane\"}\n\nThe geometry changes as predictors are added:\n\n- one predictor gives a fitted line,\n- two predictors give a fitted plane,\n- three or more predictors give a fitted hyperplane.\n\nThe word \"hyperplane\" sounds fancy, but the idea is the same: the model is still producing fitted values by combining predictors linearly in the parameters.\n\n:::\n\n\n\n\nWe can simplify notation by utilizing *matrices* to represent the model. We will present some basic notation and operations for matrices  and then present the model using matrices. \n\n\n\n\n## A Primer on Matrices\n\n\n\n### Matrices\n\nA *matrix* is a rectangular array of elements arranged in rows and columns. \n\nAn example of\na matrix is:\n\\begin{align*}\n\\left[\\begin{array}{ccc}\n8.3 & 70 & 10.3\\\\\n8.6 & 65 & 10.3\\\\\n8.8 & 63 & 10.2\\\\\n10.5 & 72 & 16.4\\\\\n\\end{array}\\right]\n\\end{align*}\n\nThis matrix represents some of the data from the \\texttt{trees} dataset. The values in the first column represent Girth, the second column represents Height, and the third column represents Volume.\n\n\nEach row corresponds to a tree. The first row represents the values for the first tree. It has 8.3 for Girth, 70 for Height, and 10.3 for Volume.\n\n\n\nSo this matrix gives the values of three variables for four trees.\n\n::: {.example title=\"Example 10.6: The data matrix behind the `trees` example\"}\n\nThe first four rows of the `trees` data can be viewed as a matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrees_matrix <- as.matrix(head(trees, 4))\n\ntrees_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Girth Height Volume\n1   8.3     70   10.3\n2   8.6     65   10.3\n3   8.8     63   10.2\n4  10.5     72   16.4\n```\n\n\n:::\n:::\n\n\nThis matrix has 4 rows and 3 columns. The rows represent observational units, the individual trees. The columns represent variables measured on each tree.\n\nIn regression, it is useful to keep this distinction straight:\n\n- rows usually correspond to observations,\n- columns usually correspond to variables or model terms.\n\n:::\n\n\n\n\n### Notation\n\nEach value of the matrix is called an *element* of that matrix. We denote the elements as $a_{ij}$ for the element in the $i$th row and the $j$th column. Note that the first subscript identifies the row number and the second the column number.\n\n\n\n\nSo for the matrix above, the elements can be denoted as\n$$\n\\begin{align*}\n\\left[\\begin{array}{ccc}\na_{11} & a_{12} & a_{13}\\\\\na_{21} & a_{22} & a_{23}\\\\\na_{31} & a_{32} & a_{33}\\\\\na_{41} & a_{42} & a_{43}\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\nA matrix may be denoted by a symbol such as $\\bf{A}$, $\\bf{X}$, or $\\bf{Z}$. The matrix could also be a greek symbol such as $\\bf{\\Omega}$. The symbol is in boldface to\nidentify that it refers to a matrix.\n\n\n\n\nThus, we might define for the above matrix;\n$$\n\\begin{align*}\n\\bf{A} =\\left[\\begin{array}{ccc}\na_{11} & a_{12} & a_{13}\\\\\na_{21} & a_{22} & a_{23}\\\\\na_{31} & a_{32} & a_{33}\\\\\na_{41} & a_{42} & a_{43}\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\nAnother notation we could use is:\n$$\n\\textbf{A}=\\left[a_{ij}\\right]\\qquad i=1,\\ldots,4; j=1,2,3\n$$\n\nThis notation avoids the need for writing out all elements of the matrix by stating only the\ngeneral element. \n\nSometimes we will specify the matrix with the dimension below the matrix symbol. For example, a $r$ x $c$ matrix can be expressed as \n\n\n\n### Matrix Dimensions\n\nThe *dimension* of the matrix above is 4 x 3, since there are four rows and three columns.\n\n\nRecall that the `trees` dataset has 31 observations. So a matrix representing the full dataset would be 31 x 3. \n\n\n\n\nNote that in giving the\ndimension of a matrix, we always specify the number of *rows* first and then the number of *columns*.\n\n::: {.callout-note collapse=\"false\" title=\"Rows first, columns second\"}\n\nMatrix dimensions are always written as\n\n$$\n\\text{number of rows} \\times \\text{number of columns}.\n$$\n\nFor regression data, rows usually represent observations and columns usually represent variables or model terms. If a data matrix has 31 trees and 3 measured variables, its dimension is $31\\times3$, not $3\\times31$.\n\n:::\n\n\n\n\nSo a $r$ x $c$ matrix can be expressed as \n$$\n\\begin{align*}\n\\underset{r\\times c}{{\\bf A}} & =\\left[\\begin{array}{cccc}\na_{11} & a_{12} & \\cdots & a_{1c}\\\\\na_{21} & a_{22} & \\cdots & a_{2c}\\\\\n\\vdots & \\vdots & \\ddots & \\vdots\\\\\na_{r1} & a_{r2} & \\cdots & a_{rc}\n\\end{array}\\right]\n\\end{align*}\n$$\nor in the compact form\n$$\n\\begin{align*}\n\\underset{r\\times c}{{\\bf A}} & =\\left[a_{ij}\\right]\\qquad i=1,\\ldots,r;j=1,\\ldots,c\n\\end{align*}\n$$\nAgain, the dimensions may or may not be given under the matrix symbol. \n\n\n### Square Matrices\n\nA matrix is said to be *square* if the number of rows equals the number of columns. For example, the matrices\n$$\n\\begin{align*}\n\\left[\\begin{array}{cc}\na_{11} & a_{12}\\\\\na_{21} & a_{22}\n\\end{array}\\right]\n\\end{align*}\n$$\nand  \n$$\n\\begin{align*}\n\\left[\\begin{array}{ccc}\na_{11} & a_{12} & a_{13}\\\\\na_{21} & a_{22} & a_{23}\\\\\na_{31} & a_{32} & a_{33}\\\\\n\\end{array}\\right]\n\\end{align*}\n$$\nare both square matrices. \n\n\n\n\n\n\n\n\n### Vectors\n\nA matrix containing only one column is called a *column* *vector* or simply a *vector*. \n\nTwo\nexamples are:\n$$\n\\begin{align*}\n\\textbf{A}=\\left[\\begin{array}{c}\n1\\\\\n20\\\\\n7\n\\end{array}\\right] & \\qquad\\textbf{B}=\\left[\\begin{array}{c}\nb_{1}\\\\\nb_{2}\\\\\nb_{3}\\\\\nb_{4}\\\\\nb_{5}\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\nNote that the elements only have one subscript in $\\bf{B}$ since there is only one column. The subscript indicates only the row. \n\n\n\n\n\n\n\nA matrix containing only one row is called a *row vector*.\n\n\n\n\nTwo examples are:\n$$\n\\begin{align*}\n\\textbf{B}^{\\prime}=\\left[\\begin{array}{ccc}\n15 & 25 & 50\\end{array}\\right] & \\qquad\\boldsymbol{\\delta}^{\\prime}=\\left[\\begin{array}{cc}\n\\delta_{1} & \\delta_{2}\\end{array}\\right]\n\\end{align*}\n$$\n\nWe use the prime (${}^\\prime$) symbol for row vectors for reasons to be seen next. \n\n\n\n\n\n### Transpose\n\nThe transpose of a matrix $\\bf{A}$ is another matrix, denoted by $\\textbf{A}^{\\prime}$, that is obtained by interchanging\ncorresponding columns and rows of the matrix $\\bf{A}$.\n\n\n\n\nFor example, if:\n$$\n\\begin{align*}\n\\underset{3\\times2}{\\textbf{A}}=\\left[\\begin{array}{cc}\n1 & 7\\\\\n12 & 4\\\\\n5 & 9\n\\end{array}\\right]\n\\end{align*}\n$$\nthen the transpose $\\bf{A}^\\prime$ is:\n$$\n\\begin{align*}\n\\underset{2\\times3}{\\textbf{A}^{\\prime}}=\\left[\\begin{array}{ccc}\n1 & 12 & 5\\\\\n7 & 4 & 9\n\\end{array}\\right]\n\\end{align*}\n$$\n\nNote that the first column of $\\bf{A}$ is the first row of $\\bf{A}^\\prime$, and similarly the second column of $\\bf{A}$\nis the second row of $\\bf{A}^\\prime$. \n\n\n\n\n\n\nNote that the dimension of $\\bf{A}$ becomes\nreversed for the dimension of $\\bf{A}^\\prime$.\n\n\nNote that the transpose of a column vector is a *row vector*, and vice versa. \n\n\n\nThis is the reason\nwhy we used the symbol $\\bf{B}^\\prime$ earlier to identify a row vector, since it may be thought of as\nthe transpose of a column vector $\\bf{B}$.\n\n\n\n\n### Symmetric Matrices\n\nA matrix is said to be *symmetric* if $\\bf{A}=\\bf{A}^\\prime$.\n\nA symmetric matrix $\\bf{A}$ has elements $a_{ij}=a_{ji}$. Clearly, a symmetric matrix must be a square matrix. \n\n\n\n\n### Diagonal Matrices\n\nA square matrix is said to be *diagonal* if all of the off-diagonal elements are zero. \n\n\n\n\nFor example\n$$\n\\begin{align*}\n{\\bf A} & =\\left[\\begin{array}{cccc}\na_{11} & 0 & 0 & 0\\\\\n0 & a_{22} & 0 & 0\\\\\n0 & 0 & a_{33} & 0\\\\\n0 & 0 & 0 & a_{44}\n\\end{array}\\right]\n\\end{align*}\n$$\nis a diagonal matrix.\n\n\n\n\n### Identity Matrix\n\nThe *identity* matrix is a diagonal matrix with ones for all the diagonal elements. The identity matrix is denoted with $\\bf{I}$.\n\n\n\n\nFor Example\n$$\n\\begin{align*}\n{\\bf I} & =\\left[\\begin{array}{cccc}\n1 & 0 & 0 & 0\\\\\n0 & 1 & 0 & 0\\\\\n0 & 0 & 1 & 0\\\\\n0 & 0 & 0 & 1\n\\end{array}\\right]\n\\end{align*}\n$$\nis a 4 x 4 identity matrix.\n\n\n\n\n\n### Matrices and Vectors of Ones and Zeros\n\n\nA matrix with ones for all the elements is denoted as\n$$\n\\begin{align*}\n{\\bf J} & =\\left[\\begin{array}{cccc}\n1 & 1 & \\cdots & 1\\\\\n1 & 1 & \\cdots & 1\\\\\n\\vdots & \\vdots & \\ddots & \\vdots\\\\\n1 & 1 & \\cdots & 1\n\\end{array}\\right]\n\\end{align*}\n$$\n\nA vector with ones for all the elements is denoted as\n$$\n\\begin{align*}\n{\\bf 1} & =\\left[\\begin{array}{c}\n1\\\\\n1\\\\\n\\vdots\\\\\n1\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\nLikewise a vector of zeros is denoted as\n$$\n\\begin{align*}\n{\\bf 0} & =\\left[\\begin{array}{c}\n0\\\\\n0\\\\\n\\vdots\\\\\n0\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n\n\n\n\n\n###  Matrix Addition and Subtraction\n\nAdding or subtracting two matrices requires that they have the same *dimension*. \n\n\n\n\nThe sum,\nor difference, of two matrices is another matrix whose elements each consist of the sum, or\ndifference, of the corresponding elements of the two matrices.\n\n\n\n\nSuppose:\n$$\n\\begin{align*}\n\\underset{3\\times2}{\\textbf{A}}=\\left[\\begin{array}{cc}\n1 & 4\\\\\n2 & 5\\\\\n3 & 6\n\\end{array}\\right] & \\qquad\\underset{3\\times2}{\\textbf{B}}=\\left[\\begin{array}{cc}\n1 & 2\\\\\n2 & 3\\\\\n3 & 4\n\\end{array}\\right]\n\\end{align*}\n$$\nthen\n$$\n\\begin{align*}\n\\underset{3\\times2}{\\textbf{A}+\\textbf{B}=} & \\left[\\begin{array}{cc}\n1+1 & 4+2\\\\\n2+2 & 5+3\\\\\n3+3 & 6+4\n\\end{array}\\right]=\\left[\\begin{array}{cc}\n2 & 6\\\\\n4 & 8\\\\\n6 & 10\n\\end{array}\\right]\n\\end{align*}\n$$\n\nSimilarly:\n$$\n\\begin{align*}\n\\underset{3\\times2}{\\textbf{A}-\\textbf{B}=} & \\left[\\begin{array}{cc}\n1-1 & 4-2\\\\\n2-2 & 5-3\\\\\n3-3 & 6-4\n\\end{array}\\right]=\\left[\\begin{array}{cc}\n0 & 2\\\\\n0 & 2\\\\\n0 & 2\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n\n### Matrix Multiplication\n\nThe addition and subtraction rules discussed above are fairly straightforward and similar to addition and subtraction of (non-matrix) numbers.\n\n\n\n\nMultiplication of matrices is not as straightforward as multiplication of (non-matrix) numbers.\n\n\n\n#### Multiplication of a Matrix by a Scalar\n\nA *scalar* is an ordinary number or a symbol representing a number. \n\n\n\n\nIn multiplication of a\nmatrix by a scalar, every element of the matrix is multiplied by the scalar. \n\n\n\n\nFor example,\nsuppose the matrix $\\textbf{A}$ is given by\n$$\n\\begin{align*}\n\\textbf{A}=\\left[\\begin{array}{cc}\n1 & 3\\\\\n5 & 7\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\nThen $2\\textbf{A}$, where 2 is the scalar, equals\n$$\n\\begin{align*}\n2\\textbf{A}=2\\left[\\begin{array}{cc}\n1 & 3\\\\\n5 & 7\n\\end{array}\\right] & =\\left[\\begin{array}{cc}\n2 & 6\\\\\n10 & 14\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n\n\n#### Multiplication of a Matrix by a Matrix\n\nConsider the two matrices:\n$$\n\\begin{align*}\n\\underset{2\\times2}{\\textbf{A}}=\\left[\\begin{array}{cc}\n1 & 2\\\\\n3 & 4\n\\end{array}\\right] & \\qquad\\underset{2\\times2}{\\textbf{B}}=\\left[\\begin{array}{cc}\n5 & 6\\\\\n7 & 8\n\\end{array}\\right]\n\\end{align*}\n$$\n\nMultiplying $\\bf{A}$ by $\\bf{B}$ is found by a multiplying the elements of each *row* vector by the elements of each each *column* vector and then summing the products. \n\n\n\nFor example, to find the element in the first row and the first column\nof the product $\\textbf{AB}$, we work with the first row of $\\textbf{A}$\nand the first column of $\\textbf{B}$:\n$$\n\\begin{align*}\n\\begin{array}{cc}\n& \\textbf{A}\\\\\n& \\left[\\begin{array}{cc}\n{\\color{red}1} & {\\color{red}2}\\\\\n3 & 4\n\\end{array}\\right]\\\\\n\\\\\n\\end{array}\\begin{array}{c}\n\\textbf{B}\\\\\n\\left[\\begin{array}{cc}\n{\\color{red}5} & 6\\\\\n{\\color{red}7} & 8\n\\end{array}\\right]\\\\\n\\begin{array}{cc}\n& \\end{array}\n\\end{array} & =\\begin{array}{cc}\n& \\textbf{AB}\\\\\n&  \\left[\\begin{array}{cc}\n\\color{red}{\\left(1\\right)\\left(5\\right)+\\left(2\\right)\\left(7\\right)} &\\\\\n\\\\\n\\end{array}\\right]\\\\\n\\\\\n\\end{array}\\\\\n& = \\begin{array}{cc}\n& \\textbf{AB}\\\\\n&  \\left[\\begin{array}{cc}\n\\color{red}{19} &\\\\\n\\\\\n\\end{array}\\right]\\\\\n\\\\\n\\end{array}\n\\end{align*}\n$$\n\nTo find the element in the first row and second column of $\\textbf{AB}$:\n$$\n\\begin{align*}\n\\begin{array}{cc}\n& \\textbf{A}\\\\\n& \\left[\\begin{array}{cc}\n{\\color{red}1} & {\\color{red}2}\\\\\n3 & 4\n\\end{array}\\right]\\\\\n\\\\\n\\end{array}\\begin{array}{c}\n\\textbf{B}\\\\\n\\left[\\begin{array}{cc}\n5 & \\color{red}{6}\\\\\n7 & \\color{red}{8}\n\\end{array}\\right]\\\\\n\\begin{array}{cc}\n& \\end{array}\n\\end{array} & =\\begin{array}{cc}\n& \\textbf{AB}\\\\\n&  \\left[\\begin{array}{cc}\n33&\n\\color{red}{\\left(1\\right)\\left(6\\right)+\\left(2\\right)\\left(8\\right)} \\\\\n\\\\\n\\end{array}\\right]\\\\\n\\\\\n\\end{array}\\\\\n& = \\begin{array}{cc}\n& \\textbf{AB}\\\\\n&  \\left[\\begin{array}{cc}\n33 & \\color{red}{22}\\\\\n\\\\\n\\end{array}\\right]\\\\\n\\\\\n\\end{array}\n\\end{align*}\n$$\n\nContinuing this process we get\n$$\n\\begin{align*}\n\\underset{2\\times2}{\\textbf{AB}} & =\\left[\\begin{array}{cc}\n\\left(1\\right)\\left(5\\right)+\\left(2\\right)\\left(7\\right) & \\left(1\\right)\\left(6\\right)+\\left(2\\right)\\left(8\\right)\\\\\n\\left(3\\right)\\left(5\\right)+\\left(4\\right)\\left(7\\right) & \\left(3\\right)\\left(6\\right)+\\left(4\\right)\\left(8\\right)\n\\end{array}\\right]=\\left[\\begin{array}{cc}\n19 & 22\\\\\n43 & 50\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\nNote that the order in matrix multiplication is important. In general, $\\textbf{AB} \\ne \\textbf{BA}$. In fact, even though the product $\\textbf{AB}$ may be defined, the product $\\textbf{BA}$ may not be defined at all.\n\n\n\n\nIn general, the product $\\textbf{AB}$  is defined only when the number of columns in $\\textbf{A}$  equals the\nnumber of rows in $\\textbf{B}$. \n\n::: {.example title=\"Example 10.7: Checking whether matrix multiplication is defined\"}\n\nIn regression matrix notation, the fitted values can be written as\n\n$$\n\\hat{\\bf Y}={\\bf X}{\\bf b}.\n$$\n\nIf there are $n$ observations and $p$ regression parameters, then\n\n$$\n\\underset{n\\times p}{\\bf X}\\quad\n\\underset{p\\times 1}{\\bf b}\n=\n\\underset{n\\times 1}{\\hat{\\bf Y}}.\n$$\n\nThe multiplication is defined because the number of columns in $\\bf X$ equals the number of rows in $\\bf b$. The result is an $n\\times1$ vector, one fitted value for each observation.\n\nThis is a useful way to check whether a matrix formula makes sense: the inner dimensions must match, and the outer dimensions tell you the size of the result.\n\n:::\n\n\n\n\nFor example:\n$$\n\\begin{align*}\n\\underset{{\\color{red}2}\\times{\\color{blue}3}}{\\textbf{A}} & \\quad\\underset{{\\color{blue}3}\\times{\\color{red}1}}{\\textbf{B}}=\\underset{{\\color{red}2}\\times{\\color{red}1}}{\\textbf{AB}}\n\\end{align*}\n$$\nis defined since the number of columns of $\\textbf{A}$ (3) is equal\nto the number of rows of $\\textbf{B}$ (3). \n\n\n\n\nHowever, note that \n$$\n\\begin{align*}\n\\underset{{\\color{blue}3}\\times{\\color{red}1}}{\\textbf{B}}\\quad\\underset{{\\color{red}2}\\times{\\color{blue}3}}{\\textbf{A}}\n\\end{align*}\n$$\nis not defined since the number of columns of $\\textbf{B}$ (1) is\nnot equal to the number of rows of $\\textbf{A}$ (2).\n\n\n\n\nWhen obtaining the product $\\textbf{AB}$, we say that $\\textbf{A}$ is *postmultiplied* by $\\textbf{B}$ or $\\textbf{B}$ is *premultiplied*\nby $\\textbf{A}$. \n\n\n\n\n\n#### Inverse of a Matrix\n\nFor ordinary (non-matrix) numbers, the inverse of a number is its reciprocal. Thus, the inverse of 2 is $\\frac{1}{2}$ \n\n\n\n\nA\nnumber multiplied by its inverse always equals 1:\n$$\n\\begin{align*}\n&2\\cdot\\frac{1}{2}=\\frac{1}{2}\\cdot2=1\n\\end{align*}\n$$\n\n\n\n\n\nIn matrix algebra, the inverse of a matrix $\\textbf{A}$ is another matrix, denoted by $\\textbf{A}^{-1}$, such that:\n$$\n\\textbf{A}^{-1}\\textbf{A}=\\textbf{A}\\textbf{A}^{-1}=\\textbf{I}\n$$\nwhere $\\textbf{I}$ is the identity matrix.\n\n\n\n\nThus,  the identity matrix $\\textbf{I}$ plays the same role as the\nnumber 1 in ordinary algebra. \n\n\n\n\nAn inverse of a matrix is defined only for *square matrices*.\n\n\n\nEven so, many square matrices do not have inverses. \n\n\n\nIf a square matrix does have an inverse,\nthe inverse is unique.\n\n\n\n\nIf the inverse of a matrix does not exist, then we say the matrix is *singular*. If the inverse does exist, then we say the matrix is *nonsingular*.\n\n::: {.callout-warning collapse=\"false\" title=\"Why singular matrices matter in regression\"}\n\nIn multiple regression, the least-squares estimates can be written using a matrix inverse. In the next chapter, this will appear as\n\n$$\n{\\bf b}=({\\bf X}'{\\bf X})^{-1}{\\bf X}'{\\bf Y}.\n$$\n\nThis formula only works if ${\\bf X}'{\\bf X}$ has an inverse. If predictors are perfectly redundant, such as including the same variable twice or including one predictor that is an exact linear combination of others, then ${\\bf X}'{\\bf X}$ becomes singular and the usual least-squares estimates are not uniquely defined.\n\nThis is the matrix-algebra version of a regression idea: the model cannot separately estimate effects that the data cannot separate.\n\n:::\n\n::: {.example title=\"Example 10.8: Verifying the matrix formula for least squares\"}\n\nThe usual matrix formula for the least-squares coefficient estimates is\n\n$$\n{\\bf b}=({\\bf X}'{\\bf X})^{-1}{\\bf X}'{\\bf Y}.\n$$\n\nFor the `trees` model, R's `model.matrix()` creates the design matrix ${\\bf X}$. The first column is the intercept column of ones, and the remaining columns are the predictors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- model.matrix(trees_fit)\nY <- trees$Volume\n\nmatrix_estimates <- solve(t(X) %*% X) %*% t(X) %*% Y\n\ncomparison <- tibble::tibble(\n  term = names(coef(trees_fit)),\n  matrix_formula = as.numeric(matrix_estimates),\n  lm_estimate = as.numeric(coef(trees_fit)),\n  difference = as.numeric(matrix_estimates) - as.numeric(coef(trees_fit))\n)\n\nknitr::kable(comparison, digits = 10)\n```\n\n::: {.cell-output-display}\n\n\n|term        | matrix_formula| lm_estimate| difference|\n|:-----------|--------------:|-----------:|----------:|\n|(Intercept) |    -57.9876589| -57.9876589|          0|\n|Girth       |      4.7081605|   4.7081605|          0|\n|Height      |      0.3392512|   0.3392512|          0|\n\n\n:::\n:::\n\n\nThe matrix formula and `lm()` give the same coefficient estimates. In practice, we usually rely on software such as `lm()` because it uses numerically stable methods, but this calculation shows where the familiar regression estimates come from.\n\n:::\n\n\n\n\n\n### Basic Matrix Results\n\nBelow are some basic results for matrices presented without proof. They will be useful as we use matrices in regression.\n$$\n\\begin{align}\n\\textbf{A}+\\textbf{B} & =\\textbf{B}+\\textbf{A} &\\\\\n\\left(\\textbf{A}+\\textbf{B}\\right)+\\textbf{C} & =\\textbf{A}+\\left(\\textbf{B}+\\textbf{C}\\right) &\\\\\n\\left(\\textbf{A}\\textbf{B}\\right)\\textbf{C} & =\\textbf{A}\\left(\\textbf{B}\\textbf{C}\\right)&\\\\\n\\textbf{C}\\left(\\textbf{A}+\\textbf{B}\\right) & =\\textbf{C}\\textbf{A}+\\textbf{C}\\textbf{B}&\\\\\nk\\left(\\textbf{A}+\\textbf{B}\\right) & =k\\textbf{A}+k\\textbf{B}&\\\\\n\\left(\\textbf{A}^{\\prime}\\right)^{\\prime} & =\\textbf{A}&\\\\\n\\left(\\textbf{A}+\\textbf{B}\\right)^{\\prime} & =\\textbf{A}^{\\prime}+\\textbf{B}^{\\prime}&\\\\\n\\left(\\textbf{A}\\textbf{B}\\right)^{\\prime} & =\\textbf{B}^{\\prime}\\textbf{A}^{\\prime}&\\\\\n\\left(\\textbf{A}\\textbf{B}\\textbf{C}\\right)^{\\prime} & =\\textbf{C}^{\\prime}\\textbf{B}^{\\prime}\\textbf{A}^{\\prime}&\\\\\n\\left(\\textbf{A}^{-1}\\right)^{-1} & =\\textbf{A}&\\\\\n\\left(\\textbf{A}^{\\prime}\\right)^{-1} & =\\left(\\textbf{A}^{-1}\\right)^{\\prime}&\n\\end{align}\n$$\n\n\n\n\n### Matrix Differentiation\n\nThere are a number of results when using matrix calculus which are beyond the scope of this course. We will present a few results for matrix differentiation that will be useful in multiple regression.\n\n\n\n\nIt is important to note that matrix calculus can be confusing due to notational conventions that are used in various fields. There are two main conventions (although the two are sometimes mixed by some authors) that are based how to take a derivative with respect to a vector. One convention is the *numerator* layout and the other is the *denominator* layout. Below, we will present the results using numerator layout. \n\n\n\n\nIn all the results that follow, let $d$ be a scalar, ${\\bf A}$ be\na $n\\times1$ vector with elements $[a_{i}]$, ${\\bf B}$ be a $m\\times1$ vector with elements $[b_{i}]$, and ${\\bf C}$\nbe a $p\\times q$ matrix with elements $[c_{ij}]$.\n\n\n\n#### Vector by a Scalar\n\n$$\n\\begin{align*}\n\\frac{\\partial{\\bf A}}{\\partial d} & =\\left[\\begin{array}{c}\n\\frac{\\partial a_{1}}{\\partial d}\\\\\n\\frac{\\partial a_{2}}{\\partial d}\\\\\n\\vdots\\\\\n\\frac{\\partial a_{n}}{\\partial d}\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n\n#### Scalar by a Vector\n\n$$\n\\begin{align*}\n\\frac{\\partial d}{\\partial{\\bf A}}\t=\\left[\\begin{array}{cccc}\n\\frac{\\partial d}{\\partial a_{1}} & \\frac{\\partial d}{\\partial a_{2}} & \\cdots & \\frac{\\partial d}{\\partial a_{n}}\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n#### Vector by a Vector\n\n$$\n\\begin{align*}\n\\frac{\\partial{\\bf A}}{\\partial{\\bf B}} & =\\left[\\begin{array}{cccc}\n\\frac{\\partial a_{1}}{\\partial b_{1}} & \\frac{\\partial a_{1}}{\\partial b_{2}} & \\cdots & \\frac{\\partial a_{1}}{\\partial b_{m}}\\\\\n\\frac{\\partial a_{2}}{\\partial b_{1}} & \\frac{\\partial a_{2}}{\\partial b_{2}} & \\cdots & \\frac{\\partial a_{2}}{\\partial b_{m}}\\\\\n\\vdots & \\vdots & \\ddots & \\vdots\\\\\n\\frac{\\partial a_{n}}{\\partial b_{1}} & \\frac{\\partial a_{n}}{\\partial b_{2}} & \\cdots & \\frac{\\partial a_{n}}{\\partial b_{m}}\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n\n#### Matrix by a Scalar\n\n$$\n\\begin{align*}\n\\frac{\\partial{\\bf C}}{\\partial d} & =\\left[\\begin{array}{cccc}\n\\frac{\\partial c_{11}}{\\partial d} & \\frac{\\partial c_{12}}{\\partial d} & \\cdots & \\frac{\\partial c_{1q}}{\\partial d}\\\\\n\\frac{\\partial c_{21}}{\\partial d} & \\frac{\\partial c_{22}}{\\partial d} & \\cdots & \\frac{\\partial c_{2q}}{\\partial d}\\\\\n\\vdots & \\vdots & \\ddots & \\vdots\\\\\n\\frac{\\partial c_{p1}}{\\partial d} & \\frac{\\partial c_{p2}}{\\partial d} & \\cdots & \\frac{\\partial c_{pq}}{\\partial d}\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n#### Scalar by a Matrix\n\n$$\n\\begin{align*}\n\\frac{\\partial d}{\\partial{\\bf C}} & =\\left[\\begin{array}{cccc}\n\\frac{\\partial d}{\\partial c_{11}} & \\frac{\\partial d}{\\partial c_{21}} & \\cdots & \\frac{\\partial d}{\\partial c_{p1}}\\\\\n\\frac{\\partial d}{\\partial c_{12}} & \\frac{\\partial d}{\\partial c_{22}} & \\cdots & \\frac{\\partial d}{\\partial c_{p2}}\\\\\n\\vdots & \\vdots & \\ddots & \\vdots\\\\\n\\frac{\\partial d}{\\partial c_{1q}} & \\frac{\\partial d}{\\partial c_{2q}} & \\cdots & \\frac{\\partial d}{\\partial c_{pq}}\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n\n\n#### Common Derivatives Involving Matrices\n\n$$\n\\begin{align*}\n& \\frac{\\partial{\\bf A}^{\\prime}{\\bf A}}{\\partial{\\bf A}}=2{\\bf A}^{\\prime}\\\\\n& \\frac{\\partial{\\bf A}^{\\prime}{\\bf B}}{\\partial{\\bf B}}=\\frac{\\partial{\\bf B}^{\\prime}{\\bf A}}{\\partial{\\bf B}}={\\bf A}^{\\prime} &  & \\text{(provided }m=n)\\\\\n& \\frac{\\partial{\\bf \\left({\\bf A}^{\\prime}{\\bf B}\\right)^{2}}}{\\partial{\\bf A}}=2{\\bf A}^{\\prime}{\\bf B}{\\bf B}^{\\prime} &  & \\text{(provided }m=n)\\\\\n& \\frac{\\partial{\\bf C}{\\bf A}}{\\partial{\\bf A}}={\\bf C} &  & \\text{(provided }q=n)\\\\\n& \\frac{\\partial{\\bf A}^{\\prime}{\\bf C}}{\\partial{\\bf A}}={\\bf C}^{\\prime} &  & \\text{(provided }p=n)\\\\\n& \\frac{\\partial{\\bf A}^{\\prime}{\\bf C}{\\bf A}}{\\partial{\\bf A}}={\\bf A}^{\\prime}\\left({\\bf C}+{\\bf C}^{\\prime}\\right) &  & \\text{(provided }n=p=q)\n\\end{align*}\n$$\n\n\n\n\n\n### Random Matrices\n\nA *random matrix* contains elements that are random variables. \n\n\n\nThus,\nthe vector of the response vector \n$$\n\\begin{align*}\n{\\bf Y} & =\\left[\\begin{array}{c}\nY_{1}\\\\\nY_{2}\\\\\n\\vdots\\\\\nY_{n}\n\\end{array}\\right]\n\\end{align*}\n$$\nis a random vector since the $Y_i$ elements are random variables.\n\n\n\n\n\n\n#### Expected Value\n\nThe *expected* *value*  of ${\\bf Y}$ is a matrix (or vector) that has\nelements that are the expected values of the elements of ${\\bf Y}$. Thus,\n$$\n\\begin{align*}\n{\\bf E}\\left[{\\bf Y}\\right] & =\\left[\\begin{array}{c}\nE\\left[Y_{1}\\right]\\\\\nE\\left[Y_{2}\\right]\\\\\n\\vdots\\\\\nE\\left[Y_{n}\\right]\n\\end{array}\\right]\n\\end{align*}\n$$\n\n\n\n#### Variance-Covariance Matrix\n\n\nWhen working with random vectors, we will be interested in the variance\nof the individual elements\n$$\n\\begin{align*}\nVar\\left[Y_{i}\\right]\n\\end{align*}\n$$\nalong with the covariance between pairs of elements\n$$\n\\begin{align*}\nCov\\left[Y_{i},Y_{j}\\right] & \\text{ }i\\ne j.\n\\end{align*}\n$$\n\nAll of these variances and covariances are given in the *variance*-*covariance*\nmatrix or simply *covariance* matrix:\n$$\n\\begin{align*}\n{\\bf Cov}\\left[{\\bf Y}\\right] & =\\left[\\begin{array}{cccc}\nVar\\left[Y_{1}\\right] & Cov\\left[Y_{1},Y_{2}\\right] & \\cdots & Cov\\left[Y_{1},Y_{n}\\right]\\\\\nCov\\left[Y_{2},Y_{1}\\right] & Var\\left[Y_{2}\\right] & \\cdots & Cov\\left[Y_{2},Y_{n}\\right]\\\\\n\\vdots & \\vdots & \\ddots & \\vdots\\\\\nCov\\left[Y_{n},Y_{1}\\right] & Cov\\left[Y_{n},Y_{2}\\right] & \\cdots & Var\\left[Y_{n}\\right]\n\\end{array}\\right]\n\\end{align*}\n$$\n\nNote that ${\\bf Cov}\\left[{\\bf Y}\\right]$ is a symmetric matrix since\n$Cov\\left[Y_{i},Y_{j}\\right]=Cov\\left[Y_{j},Y_{i}\\right]$.\n\n::: {.example title=\"Example 10.9: Independent errors and the covariance matrix\"}\n\nIn the usual regression model, the error terms are assumed to be independent with common variance $\\sigma^2$. In matrix notation, that assumption can be written as\n\n$$\n{\\bf Cov}({\\boldsymbol \\varepsilon})=\\sigma^2{\\bf I}.\n$$\n\nFor three observations, this means\n\n$$\n{\\bf Cov}({\\boldsymbol \\varepsilon})=\n\\sigma^2\n\\left[\n\\begin{array}{ccc}\n1 & 0 & 0\\\\\n0 & 1 & 0\\\\\n0 & 0 & 1\n\\end{array}\n\\right]\n=\n\\left[\n\\begin{array}{ccc}\n\\sigma^2 & 0 & 0\\\\\n0 & \\sigma^2 & 0\\\\\n0 & 0 & \\sigma^2\n\\end{array}\n\\right].\n$$\n\nThe diagonal entries are variances. The off-diagonal entries are covariances. The zeros off the diagonal represent independence between different errors.\n\n:::\n\n## Recap\n\nThis chapter introduced multiple regression and the matrix notation that will make later regression results easier to state.\n\n| Idea | Meaning |\n|---|---|\n| **Multiple regression** | A regression model with two or more predictor variables. |\n| **Linear in the parameters** | Each parameter appears to the first power and is not multiplied or divided by another parameter. |\n| **First-order model** | A model that is linear in both the parameters and the predictor variables. |\n| **Partial slope** | The expected change in the response for a one-unit change in one predictor, holding the other predictors constant. |\n| **Common partial-slope mistake** | Interpreting a multiple-regression slope as a simple bivariate relationship instead of a conditional relationship. |\n| **Multicollinearity** | Correlation among predictor variables; it can make individual predictor effects harder to estimate and interpret. |\n| **Least squares** | Chooses coefficient estimates by minimizing the sum of squared residuals. |\n| **Regression plane** | The fitted surface produced by a model with two predictors. |\n| **Design matrix** | The matrix ${\\bf X}$ containing the intercept column and predictor columns used in the regression model. |\n| **Matrix least-squares formula** | The coefficient estimates can be written as ${\\bf b}=({\\bf X}'{\\bf X})^{-1}{\\bf X}'{\\bf Y}$ when the inverse exists. |\n| **Matrix dimension** | Written as rows $\\times$ columns. |\n| **Transpose** | Interchanges rows and columns of a matrix. |\n| **Identity matrix** | A diagonal matrix with ones on the diagonal; it acts like the number 1 in matrix multiplication. |\n| **Inverse matrix** | A matrix ${\\bf A}^{-1}$ such that ${\\bf A}^{-1}{\\bf A}={\\bf A}{\\bf A}^{-1}={\\bf I}$. |\n| **Singular matrix** | A square matrix with no inverse. |\n| **Covariance matrix** | A matrix that stores variances on the diagonal and covariances off the diagonal. |\n\n## Check your understanding\n\n::: {.callout-note collapse=\"false\" title=\"Problems\"}\n\n1. Why is simple linear regression called \"simple\"?\n\n2. What does it mean for a model to be linear in the parameters?\n\n3. Can a model include $x^2$ and still be a linear regression model? Explain.\n\n4. In multiple regression, what does it mean to interpret a slope while \"holding the other predictors constant\"?\n\n5. What is a common mistake when interpreting a multiple-regression slope?\n\n6. Why can correlated predictors make interpretation harder?\n\n7. In a model with two predictors, what does the regression plane represent?\n\n8. What quantity does least squares minimize?\n\n9. Why do the least-squares formulas become cumbersome as more predictors are added?\n\n10. What is the design matrix ${\\bf X}$?\n\n11. Why should the matrix formula ${\\bf b}=({\\bf X}'{\\bf X})^{-1}{\\bf X}'{\\bf Y}$ agree with `lm()` for the same model?\n\n12. If a matrix has 10 rows and 4 columns, what is its dimension?\n\n13. What happens to the dimensions of a matrix when it is transposed?\n\n14. When is the product ${\\bf A}{\\bf B}$ defined?\n\n15. What role does the identity matrix play in matrix algebra?\n\n16. Why is a singular matrix a problem for the usual matrix formula for least-squares estimates?\n\n17. In a covariance matrix, where are the variances located?\n\n18. What does it mean if the off-diagonal entries of an error covariance matrix are 0?\n\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Solutions\"}\n\n1. **One predictor.** Simple linear regression is called \"simple\" because the model has one predictor variable.\n\n2. **Parameters appear linearly.** A model is linear in the parameters when each parameter appears to the first power and is not multiplied or divided by another parameter.\n\n3. **Yes.** A model such as $y=\\beta_0+\\beta_1x+\\beta_2x^2+\\varepsilon$ is linear in the parameters even though it is not linear in the predictor variable. It is a linear regression model, but not a first-order model.\n\n4. **Partial interpretation.** It means we interpret the effect of changing one predictor while comparing observations that have the same values of the other predictors in the model.\n\n5. **Forgetting the conditioning.** A common mistake is to interpret a multiple-regression slope as the overall relationship between one predictor and the response. In multiple regression, the slope is conditional on the other predictors in the model.\n\n6. **Effects are harder to separate.** When predictors are correlated, changes in one predictor tend to come with changes in another predictor. This makes it harder to isolate the unique contribution of each predictor.\n\n7. **The fitted surface.** The regression plane represents the fitted values from a model with two predictors. Observed points can fall above or below the plane, and those vertical differences are residuals.\n\n8. **The sum of squared residuals.** Least squares chooses estimates that minimize the sum of squared differences between observed values and fitted values.\n\n9. **More parameters create more equations.** Each additional predictor adds another coefficient and another normal equation. The algebra grows quickly, which motivates matrix notation.\n\n10. **The model-input matrix.** The design matrix ${\\bf X}$ contains the intercept column and the predictor columns used to fit the regression model.\n\n11. **They estimate the same least-squares coefficients.** The matrix formula is the algebraic expression for ordinary least squares. For the same response, predictors, and intercept convention, it gives the same estimates as `lm()`.\n\n12. **$10\\times4$.** Matrix dimensions are written as rows $\\times$ columns.\n\n13. **Rows and columns switch.** The transpose of a $10\\times4$ matrix is a $4\\times10$ matrix.\n\n14. **Inner dimensions must match.** The product ${\\bf A}{\\bf B}$ is defined when the number of columns in ${\\bf A}$ equals the number of rows in ${\\bf B}$.\n\n15. **It acts like 1.** The identity matrix plays the role of 1 in matrix multiplication: multiplying by the identity leaves a compatible matrix unchanged.\n\n16. **No inverse.** The usual matrix formula for least-squares estimates uses $({\\bf X}'{\\bf X})^{-1}$. If ${\\bf X}'{\\bf X}$ is singular, that inverse does not exist, so the usual formula cannot be used.\n\n17. **On the diagonal.** The variances are the diagonal entries of the covariance matrix.\n\n18. **Zero covariance.** Off-diagonal zeros mean the corresponding errors have covariance 0. Under the usual regression assumptions, this represents no linear association between different error terms and is tied to the independence assumption.\n\n:::\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "10_Intro_Multiple_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}