<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>3&nbsp; Properties of the Least Squares Estimators and Model Assumptions – STA 3386 Regression Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04_Sampling.html" rel="next">
<link href="./02_Fitting.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9d446ab727817792bab91d50dee4855b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>
div.callout-example.callout {
  border-left-color: #008000;
}
div.callout-example.callout-style-default > .callout-header {
  background-color: rgba(0, 128, 0, 0.13);
}
div.callout-example .callout-toggle::before {  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgb(33, 37, 41)" class="bi bi-chevron-down" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg>');}
div.callout-example.callout-style-default .callout-icon::before, div.callout-example.callout-titled .callout-icon::before {
  content: '📈';
  background-image: none;
}
</style>
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03_Properties.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Properties of the Least Squares Estimators and Model Assumptions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Regression Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_Fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fitting the Simple Linear Regression Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_Properties.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Properties of the Least Squares Estimators and Model Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_Sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling Distribution of the Least Squares Estimators and Testing the Slope</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation Coefficient and the Coefficient of Determination</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_Using.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Using the Simple Linear Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_Checking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Checking the Linearity and Constant Variance Assumptions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_Checking2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Checking the Normality and Independence Assumptions and Outliers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_Tidymodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Simple Linear Regression with Tidymodels</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_Intro_Multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">An Intro to Multiple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_Regression_Matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">The Regression Model in Matrix Terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Model Assumptions and the ANOVA F-test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_Inferences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Model Inferences and Second-Order Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_Multicollinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Multicollinearity and Principal Component Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_Indicator.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Indicator Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_Linearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">The Linearity Assumption</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_Criteria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Model Comparison Criteria</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18_Stepwise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stepwise and Best Subsets Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_Ridge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Ridge Regression and the LASSO</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20_Outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Outliers and Influential Observations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_Residual.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Residual Analysis and Remedial Measures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22_Validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Model Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23_Logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Introduction to Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24_Logistic2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Logistic Regression in Tidymodels</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25_Multinomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Multinomial Logistic Regression, Ordinal Regression, and Poisson Regression</span></span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#properties-of-the-least-squares-estimators" id="toc-properties-of-the-least-squares-estimators" class="nav-link active" data-scroll-target="#properties-of-the-least-squares-estimators"><span class="header-section-number">3.1</span> Properties of the Least Squares Estimators</a>
  <ul class="collapse">
<li><a href="#linear-estimators" id="toc-linear-estimators" class="nav-link" data-scroll-target="#linear-estimators"><span class="header-section-number">3.1.1</span> Linear Estimators</a></li>
  <li><a href="#b_1-as-a-linear-estimator" id="toc-b_1-as-a-linear-estimator" class="nav-link" data-scroll-target="#b_1-as-a-linear-estimator"><span class="header-section-number">3.1.2</span> <span class="math inline">\(b_1\)</span> as a Linear Estimator</a></li>
  <li><a href="#b_0-as-a-linear-estimator" id="toc-b_0-as-a-linear-estimator" class="nav-link" data-scroll-target="#b_0-as-a-linear-estimator"><span class="header-section-number">3.1.3</span> <span class="math inline">\(b_0\)</span> as a Linear Estimator</a></li>
  </ul>
</li>
  <li><a href="#model-assumptions" id="toc-model-assumptions" class="nav-link" data-scroll-target="#model-assumptions"><span class="header-section-number">3.2</span> Model Assumptions</a></li>
  <li><a href="#an-estimator-of-sigma2" id="toc-an-estimator-of-sigma2" class="nav-link" data-scroll-target="#an-estimator-of-sigma2"><span class="header-section-number">3.3</span> An Estimator of <span class="math inline">\(\sigma^2\)</span></a></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap"><span class="header-section-number">3.4</span> Recap</a></li>
  <li><a href="#check-your-understanding" id="toc-check-your-understanding" class="nav-link" data-scroll-target="#check-your-understanding"><span class="header-section-number">3.5</span> Check your understanding</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Properties of the Least Squares Estimators and Model Assumptions</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><blockquote class="blockquote">
<p>“The most important questions of life are, for the most part, really only problems of probability.” - Pierre Simon, Marquis de Laplace</p>
</blockquote>
<p>In the simple linear regression model <span class="math display">\[\begin{align*}
y = \beta_0 + \beta_1 x + \varepsilon
\end{align*}\]</span> we have already discussed how to estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> from sample data using least squares. In this chapter, we take the next step: we ask what kind of estimators least squares produces, what assumptions make those estimators reliable, and how we estimate the amount of random variation around the regression line.</p>
<div id="exm-3_1" class="callout callout-style-simple callout-example callout-titled theorem example">
<p><span class="theorem-title"><strong>Example 3.1</strong></span> &nbsp;</p>
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Example</span>Fitting the `mtcars` regression line in R
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>mtcars</code> data were extracted from the 1974 <em>Motor Trend</em> US magazine and contain fuel consumption and several automobile design and performance measurements for 32 automobiles from the 1973-1974 model years.</p>
<p>We first make a scatterplot of <code>mpg</code> versus <code>wt</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"mtcars"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mtcars</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">wt</span>, y <span class="op">=</span> <span class="va">mpg</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03_Properties_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>A linear relationship appears reasonable for modeling <code>mpg</code> based on <code>wt</code>.</p>
<p>Now fit the least squares line using the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function in R. The model is specified with a formula: the response variable appears to the left of <code>~</code>, and the predictor variable appears to the right.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">mpg</span> <span class="op">~</span> <span class="va">wt</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span>
<span><span class="va">fit</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt, data = mtcars)

Coefficients:
(Intercept)           wt  
     37.285       -5.344  </code></pre>
</div>
</div>
<p>The fitted line, or prediction equation, is approximately <span class="math display">\[\begin{align*}
\hat{y} = 37.285 - 5.344x
\end{align*}\]</span> where <span class="math inline">\(x\)</span> is automobile weight, measured in thousands of pounds, and <span class="math inline">\(\hat y\)</span> is the predicted miles per gallon.</p>
<p>The slope tells us that heavier cars tend to have lower fuel economy: for each additional thousand pounds of weight, the predicted fuel economy decreases by about 5.344 mpg.</p>
</div>
</div>
<section id="properties-of-the-least-squares-estimators" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="properties-of-the-least-squares-estimators">
<span class="header-section-number">3.1</span> Properties of the Least Squares Estimators</h2>
<section id="linear-estimators" class="level3" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="linear-estimators">
<span class="header-section-number">3.1.1</span> Linear Estimators</h3>
<p>The least squares estimators are <em>linear functions</em> of the observations <span class="math inline">\(y_1,\ldots,y_n\)</span>. That means both <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> can be written as linear combinations of the observed response values.</p>
<p>Since <span class="math inline">\(y\)</span> is the variable we want to model, an estimator for a parameter that takes the form of a linear combination of the <span class="math inline">\(y\)</span> values is called a <em>linear estimator</em>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Two meanings of linear">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Two meanings of linear
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>The phrase <em>linear estimator</em> does not mean the same thing as <em>linear relationship</em>.</p>
<ul>
<li>A <strong>linear relationship</strong> means the mean response follows a straight-line pattern, such as <span class="math inline">\(E(y)=\beta_0+\beta_1x\)</span>.</li>
<li>A <strong>linear estimator</strong> means an estimate can be written as a weighted sum of the observed response values, such as <span class="math inline">\(\sum a_i y_i\)</span>.</li>
</ul>
<p>In this chapter, when we say <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are linear estimators, we mean the second idea.</p>
</div>
</div>
</div>
</section><section id="b_1-as-a-linear-estimator" class="level3" data-number="3.1.2"><h3 data-number="3.1.2" class="anchored" data-anchor-id="b_1-as-a-linear-estimator">
<span class="header-section-number">3.1.2</span> <span class="math inline">\(b_1\)</span> as a Linear Estimator</h3>
<p>We can express <span class="math inline">\(b_1\)</span> as <span id="eq-w1_5"><span class="math display">\[
\begin{align}
b_1 &amp; = \sum k_i y_i
\end{align}
\tag{3.1}\]</span></span> where <span class="math display">\[\begin{align*}
k_i &amp; = \frac{x_i-\bar{x}}{\sum \left(x_i-\bar{x}\right)^2}
\end{align*}\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>For those who want to see the math:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We first note that <span class="math inline">\(\sum(x_i-\bar{x})=0\)</span>.</p>
<p>We now rewrite <span class="math inline">\(b_1\)</span> as <span class="math display">\[\begin{align*}
b_1
&amp;= \frac{\sum (x_i-\bar{x})(y_i-\bar{y})}{\sum (x_i-\bar{x})^2}\\
&amp;= \frac{\sum (x_i-\bar{x})y_i-\bar{y}\sum (x_i-\bar{x})}{\sum (x_i-\bar{x})^2}\\
&amp;= \frac{\sum (x_i-\bar{x})y_i}{\sum (x_i-\bar{x})^2}\\
&amp;= \left(\frac{1}{\sum (x_i-\bar{x})^2}\right)\sum (x_i-\bar{x})y_i.
\end{align*}\]</span></p>
</div>
</div>
</div>
<p>From <a href="#eq-w1_5" class="quarto-xref">Equation&nbsp;<span>3.1</span></a>, <span class="math inline">\(b_1\)</span> is a linear combination of the <span class="math inline">\(y\)</span> values because the <span class="math inline">\(k_i\)</span> values are known constants. In regression, the observed <span class="math inline">\(x_i\)</span> values are treated as fixed once the data have been collected.</p>
</section><section id="b_0-as-a-linear-estimator" class="level3" data-number="3.1.3"><h3 data-number="3.1.3" class="anchored" data-anchor-id="b_0-as-a-linear-estimator">
<span class="header-section-number">3.1.3</span> <span class="math inline">\(b_0\)</span> as a Linear Estimator</h3>
<p>We can write <span class="math inline">\(b_0\)</span> as <span id="eq-w1_6"><span class="math display">\[
\begin{align}
b_0 &amp; = \sum c_i y_i
\end{align}
\tag{3.2}\]</span></span> where <span class="math display">\[\begin{align*}
c_i &amp; = \frac{1}{n}-\bar{x}k_i.
\end{align*}\]</span></p>
<p>Therefore, <span class="math inline">\(b_0\)</span> is also a linear combination of the observed response values.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>For those who want to see the math:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can rewrite <span class="math inline">\(b_0\)</span> as <span class="math display">\[\begin{align*}
b_0
&amp;= \bar{y}-b_1\bar{x}\\
&amp;= \frac{1}{n}\sum y_i-\bar{x}\sum k_i y_i\\
&amp;= \sum\left(\frac{1}{n}-\bar{x}k_i\right)y_i.
\end{align*}\]</span></p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Example</span>Example 3.2: Seeing the intercept and slope as weighted sums
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we have three observations with predictor values <span class="math display">\[\begin{align*}
x_1=1,\qquad x_2=2,\qquad x_3=4.
\end{align*}\]</span></p>
<p>Then <span class="math inline">\(\bar{x}=7/3\)</span>, and <span class="math display">\[\begin{align*}
\sum (x_i-\bar{x})^2 = \frac{14}{3}.
\end{align*}\]</span></p>
<p>The weights for <span class="math inline">\(b_1\)</span> are <span class="math display">\[\begin{align*}
k_1=-\frac{2}{7},\qquad
k_2=-\frac{1}{14},\qquad
k_3=\frac{5}{14}.
\end{align*}\]</span></p>
<p>So the slope estimator is <span class="math display">\[\begin{align*}
b_1 = -\frac{2}{7}y_1-\frac{1}{14}y_2+\frac{5}{14}y_3.
\end{align*}\]</span></p>
<p>If the observed response values are <span class="math inline">\(y_1=3\)</span>, <span class="math inline">\(y_2=5\)</span>, and <span class="math inline">\(y_3=8\)</span>, then <span class="math display">\[\begin{align*}
b_1
&amp;= -\frac{2}{7}(3)-\frac{1}{14}(5)+\frac{5}{14}(8)\\
&amp;= \frac{23}{14}\\
&amp;\approx 1.64.
\end{align*}\]</span></p>
<p>For the intercept, <span class="math display">\[\begin{align*}
c_i=\frac{1}{n}-\bar{x}k_i,
\end{align*}\]</span> which gives <span class="math display">\[\begin{align*}
c_1=1,\qquad c_2=\frac{1}{2},\qquad c_3=-\frac{1}{2}.
\end{align*}\]</span></p>
<p>Thus <span class="math display">\[\begin{align*}
b_0 = y_1+\frac{1}{2}y_2-\frac{1}{2}y_3
= 3+\frac{1}{2}(5)-\frac{1}{2}(8)
= 1.5.
\end{align*}\]</span></p>
<p>The key idea is that the <span class="math inline">\(x\)</span> values determine the weights. Once those weights are fixed, <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are built from the observed <span class="math inline">\(y\)</span> values.</p>
</div>
</div>
<p>The practical payoff is that <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are themselves random variables. If we repeatedly collected new samples from the same population, the observed <span class="math inline">\(y\)</span> values would change, so the fitted intercept and slope would also change. The model assumptions below help us describe that sample-to-sample variation.</p>
</section></section><section id="model-assumptions" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="model-assumptions">
<span class="header-section-number">3.2</span> Model Assumptions</h2>
<p>Now let’s focus on the random component <span class="math inline">\(\varepsilon\)</span> in the probabilistic model and its connection to the errors in estimating <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>Specifically, we want to understand how the probability distribution of <span class="math inline">\(\varepsilon\)</span> influences how accurately the fitted model represents the true relationship between the response variable <span class="math inline">\(y\)</span> and the predictor variable <span class="math inline">\(x\)</span>.</p>
<p>We make four key assumptions about the probability distribution of <span class="math inline">\(\varepsilon\)</span>:</p>
<ol type="1">
<li><p>The mean of the error distribution is 0. This means that, on average, the errors cancel out for each value of the predictor variable <span class="math inline">\(x\)</span>. Consequently, the mean value of <span class="math inline">\(y\)</span> for a given <span class="math inline">\(x\)</span> is <span class="math display">\[\begin{align*}
E(y) = \beta_0 + \beta_1x.
\end{align*}\]</span></p></li>
<li><p>The variance of the error distribution is constant across all values of <span class="math inline">\(x\)</span>. For our linear model, this means the variance of <span class="math inline">\(\varepsilon\)</span> is the same value, <span class="math inline">\(\sigma^2\)</span>, regardless of the value of <span class="math inline">\(x\)</span>.</p></li>
<li><p>The probability distribution of <span class="math inline">\(\varepsilon\)</span> is normal.</p></li>
<li><p>The errors for different observations are independent. In other words, the error for one observation does not influence the errors for other observations.</p></li>
</ol>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Example</span>Example 3.3: Translating the model assumptions into plain language
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose <span class="math inline">\(x\)</span> is study time and <span class="math inline">\(y\)</span> is exam score. The simple linear regression model says that students with the same study time may still have different exam scores because of random error.</p>
<p>The four assumptions would mean:</p>
<ul>
<li>
<strong>Mean zero:</strong> Among all students who studied the same number of hours, the positive and negative errors balance out around the mean score.</li>
<li>
<strong>Constant variance:</strong> The spread of exam scores around the mean score is about the same for students who studied 2 hours, 6 hours, or 10 hours.</li>
<li>
<strong>Normality:</strong> At each study-time value, the errors are approximately mound-shaped and symmetric around 0.</li>
<li>
<strong>Independence:</strong> One student’s error does not determine another student’s error.</li>
</ul>
<p>The assumptions are not saying that all exam scores are normally distributed. They are statements about the errors around the regression line.</p>
</div>
</div>
<p>The implications of the first three assumptions can be seen in <a href="#fig-3_8" class="quarto-xref">Figure&nbsp;<span>3.1</span></a>, which shows distributions of errors for four particular values of <span class="math inline">\(x\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3_8" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-3_8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03_Properties_files/figure-html/fig-3_8-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3_8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: The probability distribution of <span class="math inline">\(\varepsilon\)</span>. At every value of <span class="math inline">\(x\)</span>, there is a distribution of <span class="math inline">\(y\)</span> values that satisfy the four assumptions listed above. The red points are observed values.
</figcaption></figure>
</div>
</div>
</div>
<p>From <a href="#fig-3_8" class="quarto-xref">Figure&nbsp;<span>3.1</span></a>, the error distributions are normal, centered at 0, and have constant variance <span class="math inline">\(\sigma^2\)</span>.</p>
<p>The line in the middle of each curve represents the mean value of <span class="math inline">\(y\)</span> for a given value of <span class="math inline">\(x\)</span>. The line of means is given by <span class="math display">\[
E(y) = \beta_0 + \beta_1x.
\]</span></p>
<p>These assumptions allow us to create measures of reliability for the least squares estimators and to develop hypothesis tests for evaluating the usefulness of the least squares line.</p>
<p>Various diagnostic techniques are available for checking the validity of these assumptions, and those diagnostics suggest remedies when the assumptions seem unreasonable. Therefore, it is important to use diagnostic tools in every regression analysis. We will discuss these techniques in detail later.</p>
<p>In practice, the assumptions do not need to hold exactly for least squares estimators and test statistics to have the reliability we expect from a regression analysis. The assumptions will be sufficiently satisfied for many real-world applications.</p>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Example</span>Example 3.4: Recognizing assumption problems from a residual plot
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a residual plot shows small residuals for low values of <span class="math inline">\(x\)</span> but much larger residuals for high values of <span class="math inline">\(x\)</span>. The plot has a funnel shape.</p>
<p>This pattern mainly raises concern about the <strong>constant variance</strong> assumption. The model may still capture the general direction of the relationship, but our usual formulas for standard errors, confidence intervals, and hypothesis tests may no longer be trustworthy without adjustment.</p>
<p>If the residual plot instead showed a curved pattern, the concern would be different: it would suggest that the mean relationship may not be linear. If residuals from nearby time periods tended to have the same sign, the concern would be independence.</p>
</div>
</div>
</section><section id="an-estimator-of-sigma2" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="an-estimator-of-sigma2">
<span class="header-section-number">3.3</span> An Estimator of <span class="math inline">\(\sigma^2\)</span>
</h2>
<p>The variability of random error, measured by its variance <span class="math inline">\(\sigma^2\)</span>, plays a crucial role in the accuracy of estimating model parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, as well as in the precision of predictions when using <span class="math inline">\(\hat{y}\)</span> to estimate <span class="math inline">\(y\)</span> for a given value of <span class="math inline">\(x\)</span>. As a result, <span class="math inline">\(\sigma^2\)</span> appears in the formulas for confidence intervals and test statistics.</p>
<p>In most real-world scenarios, <span class="math inline">\(\sigma^2\)</span> is unknown and must be estimated using the available data. The best estimate for <span class="math inline">\(\sigma^2\)</span> is <span class="math inline">\(s^2\)</span>, calculated by dividing the sum of squared residuals by the associated degrees of freedom. The sum of squared residuals is <span class="math display">\[
SSE = \sum \left(y_i-\hat{y}_i\right)^2.
\]</span></p>
<p>In a simple linear regression model, 2 degrees of freedom are used to estimate the y-intercept and slope, leaving <span class="math inline">\(n-2\)</span> degrees of freedom for estimating the error variance. Thus, the estimate of <span class="math inline">\(\sigma^2\)</span> is <span class="math display">\[
\begin{align*}
s^2
&amp;= \frac{SSE}{n-2}\\
&amp;= \frac{\sum \left(y_i-\hat{y}_i\right)^2}{n-2}.
\end{align*}
\]</span></p>
<p>The value of <span class="math inline">\(s^2\)</span> is called the <em>mean square error</em> (MSE).</p>
<p>The value <span class="math display">\[\begin{align*}
s &amp;= \sqrt{s^2}
\end{align*}\]</span> is called the <em>standard error of the regression model</em> or the <em>root mean square error</em> (RMSE).</p>
<div class="callout callout-style-default callout-note callout-titled" title="Units matter">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Units matter
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>SSE and MSE are measured in squared response units because residuals are squared. RMSE is measured in the original response units, which often makes it easier to interpret.</p>
<p>For example, if the response variable is mpg, then RMSE is also measured in mpg.</p>
</div>
</div>
</div>
<p>Using the empirical rule, when the model assumptions are reasonable, we expect approximately 95% of observed <span class="math inline">\(y\)</span> values to lie within about <span class="math inline">\(2s\)</span> of their respective least squares predicted values, <span class="math inline">\(\hat y\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Review: The Empirical Rule
</div>
</div>
<div class="callout-body-container callout-body">
<p>The empirical rule applies to distributions that are mound-shaped and symmetric. It states that approximately 68% of the distribution is within one standard deviation of the mean, approximately 95% is within two standard deviations of the mean, and approximately 99.7% is within three standard deviations of the mean. Since we assume <span class="math inline">\(\varepsilon\)</span> is normally distributed, the empirical rule can help us interpret the typical size of prediction errors.</p>
</div>
</div>
<div class="callout callout-style-simple callout-example callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Example</span>Example 3.5: Estimating the standard deviation with the `mtcars` model
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can use the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function with the fitted <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> object to obtain summary statistics for the regression model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">mpg</span> <span class="op">~</span> <span class="va">wt</span>, data <span class="op">=</span> <span class="va">mtcars</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5432 -2.3647 -0.1252  1.4096  6.8727 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
wt           -5.3445     0.5591  -9.559 1.29e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.046 on 30 degrees of freedom
Multiple R-squared:  0.7528,    Adjusted R-squared:  0.7446 
F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
</div>
</div>
<p>The residual standard error, or RMSE, is approximately 3.046 mpg.</p>
<p>We can obtain the ANOVA table for the fitted model with the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: mpg
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
wt         1 847.73  847.73  91.375 1.294e-10 ***
Residuals 30 278.32    9.28                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The MSE is approximately 9.28. Notice that <span class="math display">\[\begin{align*}
\sqrt{9.28} \approx 3.05,
\end{align*}\]</span> which matches the residual standard error reported by <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>.</p>
<p>In context, the fitted model’s typical prediction error is about 3 mpg. Using the rough <span class="math inline">\(2s\)</span> guideline, many observed cars would be expected to have fuel economies within about <span class="math inline">\(2(3.046)=6.092\)</span> mpg of their fitted values, assuming the model assumptions are reasonable.</p>
</div>
</div>
</section><section id="recap" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="recap">
<span class="header-section-number">3.4</span> Recap</h2>
<p>In this chapter, we moved from fitting a least squares line to understanding why that line can be used for inference.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Idea</th>
<th>Meaning</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Least squares estimators</strong></td>
<td>The formulas used to estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> from sample data.</td>
</tr>
<tr class="even">
<td><strong>Linear estimator</strong></td>
<td>An estimator that can be written as a weighted sum of the observed response values.</td>
</tr>
<tr class="odd">
<td><strong>Sampling variation</strong></td>
<td>Different samples usually produce different fitted intercepts and slopes.</td>
</tr>
<tr class="even">
<td><strong>Mean-zero error</strong></td>
<td>The regression line describes the mean response because errors average to 0 at each value of <span class="math inline">\(x\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>Constant variance</strong></td>
<td>The spread of errors is the same across values of <span class="math inline">\(x\)</span>.</td>
</tr>
<tr class="even">
<td><strong>Normal errors</strong></td>
<td>The error distribution is assumed to be approximately normal, which supports common inference procedures.</td>
</tr>
<tr class="odd">
<td><strong>Independent errors</strong></td>
<td>The error from one observation does not influence the error from another observation.</td>
</tr>
<tr class="even">
<td><strong>MSE</strong></td>
<td>The estimate <span class="math inline">\(s^2=SSE/(n-2)\)</span> of the error variance <span class="math inline">\(\sigma^2\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>RMSE</strong></td>
<td>The estimate <span class="math inline">\(s=\sqrt{s^2}\)</span> of the error standard deviation, measured in the original units of <span class="math inline">\(y\)</span>.</td>
</tr>
</tbody>
</table></section><section id="check-your-understanding" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="check-your-understanding">
<span class="header-section-number">3.5</span> Check your understanding</h2>
<div class="callout callout-style-default callout-note callout-titled" title="Problems">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Problems
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Why are <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> considered random variables, even though they are calculated from formulas?</p></li>
<li><p>What does it mean to say that <span class="math inline">\(b_1\)</span> is a linear estimator? Does this mean the relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> must be linear?</p></li>
<li><p>In the expression <span class="math inline">\(b_1=\sum k_i y_i\)</span>, why are the <span class="math inline">\(k_i\)</span> values treated as constants?</p></li>
<li><p>Explain why the assumption <span class="math inline">\(E(\varepsilon)=0\)</span> connects the regression line to the mean response <span class="math inline">\(E(y)\)</span>.</p></li>
<li><p>A residual plot has a clear funnel shape. Which regression assumption is most directly in question, and why does that matter?</p></li>
<li><p>Why is the normality assumption mainly important for inference rather than for simply drawing the least squares line?</p></li>
<li><p>Why do we divide SSE by <span class="math inline">\(n-2\)</span> rather than by <span class="math inline">\(n\)</span> when estimating <span class="math inline">\(\sigma^2\)</span> in simple linear regression?</p></li>
<li><p>A model has RMSE <span class="math inline">\(s=4.2\)</span>. Interpret this value in context-free language. Why is RMSE often easier to explain than MSE?</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solutions">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>They vary from sample to sample.</strong> Once a sample is collected, <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are fixed numbers. But before sampling, the response values are random, so the fitted intercept and slope are random too. A different sample would usually produce a different fitted line.</p></li>
<li><p><strong>A weighted sum of responses.</strong> Saying <span class="math inline">\(b_1\)</span> is a linear estimator means it can be written as a weighted sum of the observed response values, <span class="math inline">\(b_1=\sum k_i y_i\)</span>. This is different from saying the mean relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is linear. One statement is about the form of the estimator; the other is about the form of the model.</p></li>
<li><p><strong>The weights come from the predictor values.</strong> The <span class="math inline">\(k_i\)</span> values depend only on the observed <span class="math inline">\(x\)</span> values. Once the data’s predictor values are fixed, the weights are fixed, so the randomness in <span class="math inline">\(b_1\)</span> comes from the response values.</p></li>
<li><p><strong>Mean-zero error centers the model on the regression line.</strong> If <span class="math inline">\(y=\beta_0+\beta_1x+\varepsilon\)</span> and <span class="math inline">\(E(\varepsilon)=0\)</span>, then the average value of <span class="math inline">\(y\)</span> at a given <span class="math inline">\(x\)</span> is <span class="math inline">\(E(y)=\beta_0+\beta_1x\)</span>. The error term explains why individual observations vary around that mean line.</p></li>
<li><p><strong>Constant variance.</strong> A funnel shape suggests that the spread of residuals changes as <span class="math inline">\(x\)</span> changes. This matters because standard errors, confidence intervals, and hypothesis tests rely on assumptions about the variability of the errors.</p></li>
<li><p><strong>The line can be fit without normal errors.</strong> Least squares can compute a fitted line whether or not the errors are normal. The normality assumption becomes more important when we use the fitted model to make probability-based statements, such as confidence intervals and hypothesis tests.</p></li>
<li><p><strong>Two parameters have been estimated.</strong> In simple linear regression, we estimate both an intercept and a slope. That uses 2 degrees of freedom, leaving <span class="math inline">\(n-2\)</span> degrees of freedom to estimate the error variance.</p></li>
<li><p><strong>Typical error size.</strong> An RMSE of 4.2 means that observed responses typically differ from their fitted values by about 4.2 response units. RMSE is easier to explain than MSE because RMSE is in the original units of the response variable, while MSE is in squared units.</p></li>
</ol>
</div>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./02_Fitting.html" class="pagination-link" aria-label="Fitting the Simple Linear Regression Model">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fitting the Simple Linear Regression Model</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04_Sampling.html" class="pagination-link" aria-label="Sampling Distribution of the Least Squares Estimators and Testing the Slope">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sampling Distribution of the Least Squares Estimators and Testing the Slope</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>